import { readFileSync } from "node:fs";

/**
 * Server-only. Loads the subsetted TrueType faces generated by
 * scripts/build-og-fonts.ts. satori resolves per glyph across the faces it is
 * given, so a locale gets a Latin face (brand chrome is Latin on every card)
 * plus its script face where one is needed.
 *
 * Requires the OG routes to run on the Node runtime — the edge runtime cannot
 * read fonts from disk.
 */

const SCRIPT_LOCALES = new Set(["ja", "ko", "zh", "hi"]);

/**
 * Arabic cards fall back to the English card.
 *
 * satori (via next/og) cannot shape Arabic here: it throws
 * "lookupType: 5 - substFormat: 3 is not yet supported" whichever Arabic face
 * we supply. Verified against Noto Sans Arabic, Noto Naskh, Noto Kufi, Cairo,
 * Tajawal and Almarai — both Google-subsetted and the full originals, and the
 * last three contain no such lookup at all. It comes from a fallback face
 * satori loads itself, so it cannot be fixed by choosing a different font.
 *
 * English text keeps /ar/* social previews legible, which beats both the tofu
 * boxes this replaced and a 500.
 */
export function ogLocale<T extends string | null>(locale: T): T | null {
  return locale === "ar" ? null : locale;
}

function load(name: string) {
  return readFileSync(new URL(`../app/api/_og-fonts/${name}.ttf`, import.meta.url));
}

export function fontsForLocale(locale: string | null) {
  const code = ogLocale(locale) ?? "en";
  const fonts = [
    { name: "Site", data: load(`${code}-latin-400`), weight: 400 as const, style: "normal" as const },
    { name: "Site", data: load(`${code}-latin-700`), weight: 700 as const, style: "normal" as const },
  ];
  if (SCRIPT_LOCALES.has(code)) {
    fonts.push(
      { name: "Site", data: load(`${code}-script-400`), weight: 400 as const, style: "normal" as const },
      { name: "Site", data: load(`${code}-script-700`), weight: 700 as const, style: "normal" as const },
    );
  }
  return fonts;
}
