import type { ToolWorkspaceLabels } from "@/components/tool-workspace";

/**
 * English strings for the client workspace. Kept out of the client component
 * on purpose: ToolPage passes them as props for every locale, so the tool-page
 * JavaScript stays under its 200 KB budget and locales override by key.
 */
export const workspaceDefaults: Omit<ToolWorkspaceLabels, "output"> = {
  input: "Input",
  emptyResult: "Your result appears here as you type.",
  characters: "chars",
  report: "report",
  live: "Live",
  updating: "Updating…",
  copy: "Copy",
  copied: "Copied",
  download: "Download",
  share: "Copy link to result",
  shareCopied: "Share link copied",
  embed: "Embed",
  embedCopied: "Embed code copied",
  downloadImage: "Download as image",
  free: "Free",
  noSignup: "No signup",
  private: "Processing happens in your browser — text never uploaded.",
  printPdf: "Print / Save PDF",
  downloaded: "Downloaded",
  excelDownloaded: "Excel file downloaded",
  reportImageDownloaded: "Report image downloaded",
  pasteFirst: "Paste some text first",
  creatingLink: "Creating link…",
  couldNotCreateLink: "Could not create link",
  shareUnavailable: "Share unavailable",
  reportNote: "Counts mechanical artifacts only. This is not AI detection.",
  conversionOptions: "Conversion options",
  editorView: "Editor view",
  caseLabel: "Case",
  caseTitle: "Title Case",
  caseSentence: "Sentence case",
  caseUpper: "UPPERCASE",
  caseLower: "lowercase",
  dashLabel: "Replace em dashes with",
  dashComma: "Comma",
  dashSemicolon: "Semicolon",
  dashHyphen: "Hyphen",
  dashRemove: "Nothing",
  listLabel: "Convert to",
  listToParagraph: "Paragraph",
  listToBullets: "Bullet points",
  loadExample: "Load an example",
  exampleLoaded: "Example loaded",
  keepUrls: "Keep link URLs",
  listMarkersLabel: "List markers",
  listMarkersKeep: "Keep as bullets and numbers",
  listMarkersRemove: "Remove",
  keepCode: "Keep code blocks as written",
  tidySpacing: "Tidy spacing too",
  showChanges: "Show what changed",
  stripMarkdown: "Also remove Markdown symbols",
};
