import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "O ChatGPT esconde caracteres invisíveis?",
  description: "O texto da IA realmente contém Unicode invisível. Veja o que há de fato ali, de onde vem e se algo disso é uma marca d'água.",
  h1: "O ChatGPT esconde caracteres invisíveis no seu texto?",
  dek: "A teoria da marca d'água, o que os bytes realmente mostram e como verificar seu próprio texto.",
  answer: "O texto da IA de fato costuma conter Unicode invisível — mais comumente espaços inquebráveis e espaços estreitos inquebráveis. Mas esses são subprodutos corriqueiros da formatação de texto, não uma marca d'água oculta. A marca d'água de texto real existe e funciona influenciando estatisticamente a escolha de palavras, sem deixar caracteres especiais para encontrar. Você pode verificar qualquer texto por conta própria em poucos segundos.",
  sections: {
    "the-claim": {
      heading: "A alegação e por que ela se espalhou",
      body: "De tempos em tempos, um post viraliza mostrando que o texto copiado do ChatGPT contém caracteres ocultos, com a conclusão de que a OpenAI estaria colocando marcas d'água secretas no conteúdo para poder rastreá-lo.\n\nA observação é real. A conclusão não tem fundamento.\n\nO que as pessoas encontram é genuíno — cole uma resposta do chat em um inspetor de caracteres e você verá com frequência códigos que não renderizam nada. O salto acontece na interpretação. Uma marca d'água precisa sobreviver à edição, ser difícil de remover e codificar alguma informação. Caracteres que desaparecem no primeiro localizar e substituir, e que não carregam nenhum conteúdo recuperável, não atendem a nenhuma dessas condições.",
    },
    "what-is-there": {
      heading: "O que realmente está no texto",
      body: "Os caracteres invisíveis que aparecem em textos de IA são, na imensa maioria, caracteres tipográficos comuns:\n\n| Caractere | Código | Por que aparece |\n| --- | --- | --- |\n| Espaço inquebrável | U+00A0 | Mantém um número e sua unidade na mesma linha |\n| Espaço estreito inquebrável | U+202F | Espaçamento fino antes de pontuação e em números |\n| Espaço de largura zero | U+200B | Sugestões de quebra de linha, muitas vezes herdadas de texto da web |\n| Hífen suave | U+00AD | Marca onde uma palavra pode ser dividida na quebra de linha |\n| Marca de ordem de bytes | U+FEFF | Artefato de codificação vindo de um arquivo anterior |\n\nCada um tem uma finalidade tipográfica legítima e existe décadas antes dos modelos de linguagem. Eles chegam pelos mesmos caminhos de sempre: o modelo os aprendeu de textos de treinamento que os continham, a interface do chat renderiza a saída formatada como HTML e copiar de uma página renderizada carrega o que quer que a marcação contenha.\n\nEsse último caminho importa mais do que as pessoas imaginam. Boa parte do que é atribuído ao modelo é, na verdade, introduzido pela *cópia no navegador*, não pela geração. Copiar a mesma resposta pela API frequentemente produz um texto mais limpo do que copiá-la da janela do chat.",
    },
    "does-watermarking-exist": {
      heading: "A marca d'água em texto de IA existe?",
      body: "Sim — mas não funciona como os posts virais supõem.\n\nO SynthID-Text, do Google DeepMind, é a abordagem mais bem documentada, publicada na *Nature* em 2024. Ele funciona influenciando sutilmente quais palavras o modelo escolhe a cada passo, de modo que o texto final carrega uma assinatura estatística detectável por um verificador correspondente. Não há caracteres especiais envolvidos. Nada é inserido. A marca d'água vive na *escolha de palavras comuns*, e é por isso que ela sobrevive à cópia e a edições leves — e por que você não consegue encontrá-la inspecionando códigos de caracteres.\n\nA OpenAI já discutiu publicamente pesquisas sobre marca d'água em texto e não lançou uma implementação confirmada para o usuário final nas respostas do ChatGPT.\n\nA implicação prática vai contra o pânico: se um modelo que você usa tem marca d'água, remover caracteres invisíveis não a elimina. E se você encontra caracteres invisíveis, isso não é evidência de marca d'água — é evidência de formatação.",
    },
    "why-it-matters": {
      heading: "Por que os caracteres invisíveis importam mesmo assim",
      body: "Com ou sem marca d'água, normalmente você quer se livrar deles, porque eles quebram as coisas silenciosamente:\n\n- **Busca e localizar e substituir falham.** Um espaço de largura zero entre duas letras faz a busca pela palavra não encontrar nada, sem motivo visível.\n- **A validação de formulários rejeita a entrada.** Um e-mail ou chave de licença com um espaço inquebrável no final falha em uma comparação que parece correta na tela.\n- **O código não compila nem é interpretado.** Um espaço inquebrável onde deveria haver um espaço normal gera um erro de sintaxe apontando para uma linha que parece perfeita.\n- **Importações de CSV corrompem.** Uma marca de ordem de bytes gruda no cabeçalho da primeira coluna, e o primeiro campo falha silenciosamente no mapeamento.\n- **Registros duplicados aparecem.** Duas entradas que parecem idênticas são strings diferentes, e a desduplicação não as detecta.\n\nEssas falhas são especialmente irritantes porque o texto parece correto. Todo instinto de depuração aponta para o lugar errado.",
    },
    "how-to-check": {
      heading: "Como verificar e limpar seu próprio texto",
      body: "Cole o texto no [Verificador de caracteres invisíveis](/remove-invisible-characters). Ele relata cada espaço de largura zero, hífen suave, marca de ordem de bytes e marca direcional que encontrar, com a contagem de cada tipo, e os remove quando você pedir. Nada sai do seu navegador — a verificação roda localmente.\n\nSe quiser o panorama completo, a ferramenta [Limpar texto do ChatGPT e IA](/clean-ai-text) trata dos caracteres invisíveis junto com travessões, aspas curvas e emojis em uma única passada.\n\nUm hábito que vale criar: rode a verificação sempre que um texto cruzar a fronteira entre sistemas. Da janela do chat para o editor de código, da página da web para a planilha, do PDF para o formulário. É aí que os caracteres invisíveis causam estragos — e é o momento em que removê-los custa menos.\n\nPara a lista completa do que esses caracteres são e o que cada um faz, veja a [referência de Unicode invisível](/guides/invisible-unicode-characters).",
    },
  },
  faqs: [
    { question: "O ChatGPT coloca marca d'água no texto com caracteres invisíveis?", answer: "Não há evidência disso. Os caracteres invisíveis encontrados nas respostas do ChatGPT são tipográficos comuns, como espaços inquebráveis e espaços estreitos inquebráveis, que existem há décadas e não carregam nenhum conteúdo. Eles também desaparecem com qualquer limpeza básica, o que os tornaria inúteis como marca d'água." },
    { question: "É possível colocar marca d'água em texto gerado por IA?", answer: "Sim. O SynthID-Text, do Google DeepMind, publicado na Nature em 2024, influencia as escolhas de palavras do modelo para que a saída carregue uma assinatura estatística. Ele não insere caracteres especiais, então inspecionar códigos nunca o revela, e remover caracteres invisíveis não o elimina." },
    { question: "Por que o texto copiado do ChatGPT contém caracteres ocultos?", answer: "Principalmente porque você está copiando HTML renderizado de uma página da web. A interface do chat exibe a saída formatada, e a cópia carrega os caracteres de espaçamento que essa formatação usou. Obter a mesma resposta pela API costuma produzir um texto visivelmente mais limpo." },
    { question: "Como encontro caracteres invisíveis no meu texto?", answer: "Cole-o em um verificador que liste os códigos, como o nosso removedor de caracteres invisíveis. Ele identifica cada tipo de caractere invisível presente, conta quantos há e os remove quando você pedir, rodando inteiramente no seu navegador." },
    { question: "Caracteres invisíveis são perigosos?", answer: "Não são perigosos, mas atrapalham de verdade. Eles quebram buscas, fazem validações de formulário falharem, geram erros de sintaxe no código, corrompem cabeçalhos de CSV e criam registros duplicados que parecem idênticos. Como o texto parece normal, esses bugs são especialmente difíceis de diagnosticar." },
  ],
};
