import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Travessão, meia-risca e hífen: a diferença",
  description: "Três caracteres, três funções. Quando usar cada um, como digitá-los em qualquer teclado e por que trocá-los quebra coisas.",
  h1: "Travessão, meia-risca e hífen",
  dek: "Três caracteres Unicode diferentes que parecem iguais e não são intercambiáveis.",
  answer: "O hífen (-) une palavras compostas: bem-conhecido. A meia-risca (–) marca intervalos e conexões: páginas 20–24. O travessão (—) destaca uma frase dentro de um período, como uma vírgula mais forte. São três caracteres Unicode distintos, de largura crescente, e analisadores, buscas e tipografia tratam cada um de forma diferente.",
  sections: {
    "the-three-characters": {
      heading: "Os três caracteres em resumo",
      body: "Os nomes vêm da tipografia histórica: a meia-risca tinha a largura de um N maiúsculo, e o travessão a largura de um M maiúsculo.\n\n| Sinal | Nome | Ponto de código | Largura | Uso principal |\n| --- | --- | --- | --- | --- |\n| - | Hífen-menos | U+002D | Menor | Palavras compostas |\n| – | Meia-risca | U+2013 | Média | Intervalos e conexões |\n| — | Travessão | U+2014 | Maior | Desvios dentro de uma frase |\n\nO primeiro está no seu teclado. Os outros dois não estão, e essa é a raiz prática de quase toda a confusão: as pessoas digitam um hífen onde deveria haver uma meia-risca ou um travessão, porque é o único disponível sem atalho.",
    },
    "the-hyphen": {
      heading: "O hífen",
      body: "O hífen une elementos em uma unidade única.\n\n- **Modificadores compostos antes de um substantivo**: um autor *bem-conhecido*, um cachorro *de doze anos*, uma instalação *de última geração*. Note que o hífen desaparece quando a expressão vem depois do substantivo: o autor é *bem conhecido*.\n- **Alguns prefixos**, principalmente para evitar colisão ou ambiguidade: *reeleger*, *coproprietário*, *re-cobrir* uma cadeira (em oposição a *recobrar* a consciência).\n- **Quebras de palavra no fim da linha**, em texto justificado.\n- **Números compostos**: *vinte e três* (no inglês, *twenty-three*).\n\nTecnicamente, o caractere do teclado é o *hífen-menos* — um único ponto de código que funciona como hífen, sinal de menos e flag de linha de comando, herança das máquinas de escrever e do ASCII original. O Unicode tem um hífen dedicado (U+2010) e um sinal de menos próprio (U+2212), mas quase nada os usa, e você não deve começar a usar: `-` é o que analisadores, shells e URLs esperam.",
    },
    "the-en-dash": {
      heading: "A meia-risca",
      body: "A meia-risca significa *a*, *até* ou *entre*. Ela conecta em vez de unir.\n\n- **Intervalos numéricos**: páginas *20–24*, *2020–2024*, *9h–17h*. Os manuais de estilo desaconselham misturá-la com palavras: escreva *de 2020 a 2024*, não *de 2020–2024*.\n- **Conexões e conflitos entre entidades separadas**: o rali *Paris–Dakar*, a relação *médico–paciente*, o eixo *leste–oeste*. A distinção em relação ao hífen importa aqui — *franco-alemão* com hífen sugere uma coisa só, uma mistura, enquanto *França–Alemanha* com meia-risca indica duas partes em relação.\n- **Modificadores compostos em que uma parte já tem várias palavras**: um acordo *pós–Segunda Guerra Mundial*. Um hífen ali ligaria apenas a \"Segunda\".\n- **Placares e votações**: uma vitória por *3–1*.\n\nA meia-risca é a menos usada das três e a mais frequentemente substituída por um hífen. Em prosa corrida, essa troca é uma imprecisão tipográfica menor, que poucos leitores percebem. Em dados, não é menor: um intervalo de datas escrito com meia-risca não corresponde a uma expressão regular que procura um hífen.",
    },
    "the-em-dash": {
      heading: "O travessão",
      body: "O travessão destaca uma frase, criando uma pausa mais forte que a vírgula e mais suave que o ponto final.\n\n- **Em pares, em torno de um aparte**: *Os resultados — que ninguém esperava — foram claros.*\n- **Sozinho, antes de uma conclusão ou reviravolta**: *Ela conferiu tudo duas vezes — e ainda assim deixou passar.*\n- **Para marcar fala interrompida** em diálogos.\n\n**O espaçamento** é a única divergência real de estilo. A convenção editorial americana (Chicago Manual of Style) usa o travessão colado: *palavra—palavra*. A convenção britânica (Oxford e a maioria dos jornais do Reino Unido) usa a meia-risca com espaços: *palavra – palavra*. Ambas estão corretas; o que importa é a consistência dentro do documento. Textos de IA costumam usar o travessão com espaços — *palavra — palavra* — um híbrido das duas tradições, e é por isso que pode parecer sutilmente estranho para editores formados em qualquer uma delas.\n\nO travessão também é o sinal que virou uma espécie de assinatura não oficial de texto gerado por IA, porque os modelos o usam com muito mais consistência do que as pessoas. Isso é explicado em [por que o ChatGPT usa tantos travessões](/guides/why-chatgpt-uses-em-dashes).",
    },
    "typing-them": {
      heading: "Como digitar cada um",
      body: "| Plataforma | Meia-risca (–) | Travessão (—) |\n| --- | --- | --- |\n| macOS | <kbd>Option</kbd> + <kbd>-</kbd> | <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd> |\n| Windows | <kbd>Alt</kbd> + <kbd>0150</kbd> | <kbd>Alt</kbd> + <kbd>0151</kbd> |\n| Linux | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2013 | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2014 |\n| Word / Docs | Dois hífens entre palavras viram meia-risca | Dois hífens viram travessão |\n| HTML | `&ndash;` | `&mdash;` |\n| iOS / Android | Pressione e segure a tecla de hífen | Pressione e segure a tecla de hífen |\n\nOs códigos Alt do Windows exigem um teclado numérico, e é por isso que tantos usuários de notebook simplesmente nunca digitam esses caracteres.",
    },
    "when-it-breaks-things": {
      heading: "Quando a diferença realmente quebra coisas",
      body: "Em prosa, usar hífen no lugar de meia-risca é um requinte tipográfico. Fora da prosa, são três pontos de código distintos e a diferença é funcional:\n\n- **Busca e localizar e substituir** correspondem caracteres exatos. Procurar por `2020-2024` não encontra `2020–2024`.\n- **Comandos de shell** precisam de U+002D. `--force` colado de um documento em que a autocorreção o transformou em travessão não é uma flag, e a mensagem de erro não vai mencionar travessões.\n- **CSV e JSON** tratam meia-risca e travessão como texto comum, o que normalmente não é problema — até um valor que deveria corresponder a uma chave não corresponder.\n- **URLs e slugs** aceitam apenas o hífen ASCII.\n- **Ordenação e desduplicação** tratam os três como caracteres diferentes, então entradas visualmente idênticas não são agrupadas.\n\nSe você precisa normalizar travessões em um documento, o [Removedor de travessões](/remove-em-dashes) os substitui pelo caractere que você escolher e mostra a contagem, para você confirmar que o número bate com o esperado em vez de confiar em uma substituição silenciosa. A armadilha equivalente com aspas está explicada em [por que aspas curvas quebram código](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "Qual é a diferença entre travessão e meia-risca?", answer: "A meia-risca (–, U+2013) significa a ou até e marca intervalos como 2020–2024. O travessão (—, U+2014) destaca uma frase dentro de um período, como uma vírgula mais forte. O travessão tem cerca do dobro da largura, e os dois são caracteres Unicode distintos." },
    { question: "Quando devo usar hífen em vez de travessão?", answer: "Use o hífen para unir palavras em uma unidade única: bem-conhecido, vinte e três, reeleição. Se você quer indicar um intervalo, uma conexão entre duas partes ou uma pausa na frase, o certo é a meia-risca ou o travessão." },
    { question: "O travessão deve ter espaços ao redor?", answer: "Depende do manual de estilo. A convenção americana usa o travessão colado (palavra—palavra), enquanto a britânica costuma usar a meia-risca com espaços (palavra – palavra). Ambas estão corretas; o que importa é a consistência dentro do documento." },
    { question: "Como digito um travessão?", answer: "No macOS, pressione Option + Shift + hífen. No Windows, segure Alt e digite 0151 no teclado numérico. No Word e no Google Docs, digitar dois hífens entre palavras converte automaticamente. No celular, pressione e segure a tecla de hífen." },
    { question: "Faz diferença usar hífen no lugar de meia-risca?", answer: "Em prosa, é uma imprecisão menor que a maioria dos leitores não percebe. Em dados, código, URLs ou qualquer coisa pesquisada ou processada, faz muita diferença, porque os três são caracteres distintos e uma correspondência exata vai falhar." },
  ],
};
