import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Exportar conversa do ChatGPT para PDF ou Word",
  description: "Imprimir para PDF corta o chat e perde a formatação. Veja como transformar uma conversa em um PDF ou documento Word limpo e legível.",
  h1: "Como exportar uma conversa do ChatGPT para PDF ou Word",
  dek: "Por que imprimir a página não funciona, e como obter um documento que você realmente enviaria para alguém.",
  answer: "Imprimir a página do chat diretamente costuma cortar mensagens longas, perder blocos de código e carregar elementos da interface para o arquivo. Copiar a conversa como texto, reestruturá-la para que cada turno vire uma seção identificada e depois converter para PDF ou DOCX produz um documento realmente legível e editável.",
  sections: {
    "why-printing-fails": {
      heading: "Por que imprimir a página do chat não funciona",
      body: "Apertar <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>P</kbd> na janela do chat é a reação óbvia, e o resultado é decepcionante por motivos estruturais.\n\nInterfaces de chat são construídas como telas de aplicativo com rolagem, não como documentos. Isso leva a falhas de impressão previsíveis:\n\n- **Mensagens longas são cortadas.** Cada mensagem fica em seu próprio contêiner de rolagem, então a impressão captura apenas a parte visível.\n- **Blocos de código perdem conteúdo.** Código com rolagem horizontal é cortado na borda do contêiner, e o lado direito de cada linha longa simplesmente some.\n- **Elementos da interface vão junto.** Barras laterais, avatares, seletores de modelo e botões de regenerar aparecem na impressão.\n- **As quebras de página caem mal.** Nada indica ao navegador onde seria uma quebra sensata, então títulos ficam órfãos no fim das páginas.\n- **Só existem as mensagens carregadas.** Conversas longas são virtualizadas, então mensagens antigas que não foram renderizadas nem aparecem na impressão.\n\nO resultado é um arquivo que tecnicamente contém sua conversa, mas que você não anexaria a um e-mail.",
    },
    "the-reliable-route": {
      heading: "O caminho confiável: copiar, estruturar, converter",
      body: "Trate a conversa como texto, não como uma página da web.\n\n1. **Selecione a conversa e copie.** Arraste a seleção da primeira à última mensagem. Você obterá o texto dos dois lados, geralmente com a estrutura Markdown intacta.\n2. **Reestruture como um documento.** Cole no [Converter conversa do ChatGPT em documento](/chatgpt-conversation-to-document). Ele detecta os turnos de cada participante e os reconstrói como seções claras e identificadas, em vez de um bloco de texto indiferenciado.\n3. **Converta para o formato que você precisa.** Para um arquivo compartilhável, o [Converter Markdown para PDF](/markdown-to-pdf) oferece uma visualização pronta para impressão que você salva direto em PDF. Para algo editável, o [Converter Markdown para Word](/markdown-to-word) gera um `.docx` com estilos de título de verdade.\n\nO resultado é um documento com título, seções identificadas para cada participante, blocos de código e tabelas preservados, e quebras de página em lugares sensatos.",
    },
    "labelling-speakers": {
      heading: "Acertando as identificações de quem fala",
      body: "A única parte que merece um momento de atenção é como o texto copiado distingue quem disse o quê.\n\nDependendo da interface e do navegador, uma conversa copiada pode vir com identificações explícitas ou sem nada separando os turnos. Se o texto colado não tiver identificações, adicione-as antes de converter: uma linha contendo apenas `You:` ou `ChatGPT:` acima de cada turno já é suficiente para o conversor encontrar os limites.\n\nUm formato que funciona de forma consistente:\n\n```\nYou:\nSummarize the Q2 results.\n\nChatGPT:\nRevenue rose 12% year over year, driven by...\n```\n\nEm conversas técnicas longas, vale a pena apagar os becos sem saída da exploração antes de converter. Uma transcrição de quarenta trocas em que só seis importaram não fica mais útil por ser completa: fica menos útil, porque o leitor precisa encontrar as seis. Exporte a conversa que você gostaria de ler.",
    },
    "practical-notes": {
      heading: "Notas práticas sobre o arquivo final",
      body: "**Configuração de página do PDF.** Ao salvar pela janela de impressão, ative os gráficos de plano de fundo se quiser que os blocos de código mantenham o sombreamento, e confira se as margens não estão cortando tabelas largas. A orientação paisagem costuma ser a escolha certa para uma conversa cheia de dados.\n\n**Documentos Word e títulos.** Como o conversor gera estilos de título de verdade, e não texto em negrito, o painel de navegação do Word funciona e você pode inserir um sumário automático. Essa é a principal vantagem prática sobre qualquer abordagem de copiar e colar.\n\n**Código longo.** Código que rolava horizontalmente na janela do chat vai quebrar linha no documento. Se as quebras de linha exatas importam — um arquivo de configuração, um comando de shell — confira esses blocos depois de converter.\n\n**Privacidade.** Os dois conversores rodam inteiramente no seu navegador; nada é enviado. Isso importa mais do que o normal aqui, já que conversas costumam conter contexto de trabalho, dados de clientes ou material não lançado. Se você hesitaria em colar o conteúdo em um site desconhecido, o processamento local é o motivo pelo qual esta abordagem é segura.\n\n**Uma nota sobre as exportações oficiais.** O ChatGPT oferece uma exportação de dados nas configurações, que envia por e-mail um ZIP com seu histórico de conversas. É completa e útil para arquivamento, mas vem estruturada como dados brutos, e não como um documento legível, então você ainda precisaria converter para compartilhar uma conversa específica com alguém.",
    },
  },
  faqs: [
    { question: "Como salvar uma conversa do ChatGPT em PDF?", answer: "Copie a conversa, reestruture-a com o Converter conversa do ChatGPT em documento para que cada turno vire uma seção identificada, depois use o Converter Markdown para PDF e salve pela janela de impressão. Isso evita as mensagens cortadas e os blocos de código perdidos que aparecem ao imprimir a página do chat." },
    { question: "Por que imprimir a página do ChatGPT corta minhas mensagens?", answer: "As mensagens ficam dentro de seus próprios contêineres de rolagem e conversas longas são virtualizadas, então a impressão captura apenas o que está renderizado e visível no momento. Blocos de código com rolagem horizontal são cortados na borda do contêiner pelo mesmo motivo." },
    { question: "Posso exportar uma conversa do ChatGPT para o Word?", answer: "Sim. Converta a conversa copiada para .docx com o Converter Markdown para Word. Como ele gera estilos de título de verdade, e não texto em negrito, o painel de navegação funciona e você pode gerar um sumário automático." },
    { question: "O ChatGPT tem exportação integrada?", answer: "Existe uma exportação de dados nas configurações que envia por e-mail um arquivo do seu histórico de conversas. É boa para backup, mas vem estruturada como dados brutos, e não como um documento legível, então converter continua sendo o caminho prático para compartilhar uma conversa específica." },
    { question: "É seguro colar uma conversa privada em um conversor?", answer: "Depende inteiramente da ferramenta. As nossas processam o texto no seu navegador e não enviam nada, e é por isso que a conversa permanece na sua máquina. Qualquer ferramenta que envie o texto para um servidor deve ser tratada como uma publicação do conteúdo, o que importa para material de trabalho ou de clientes." },
  ],
};
