import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Por que o texto de IA colado mostra ** e ## no Word",
  description: "Aqueles asteriscos e cerquilhas são Markdown. Veja por que o Word os exibe literalmente e três formas de colar o texto de IA com a formatação intacta.",
  h1: "Por que o texto de IA colado mostra ** e ## no Word?",
  dek: "Os símbolos são instruções de formatação de verdade — o Word simplesmente não sabe lê-los.",
  answer: "Esses símbolos são Markdown, uma linguagem de formatação em texto simples que os modelos de chat usam para escrever. Asteriscos marcam negrito, cerquilhas marcam títulos e barras verticais formam tabelas. O Word não tem um interpretador de Markdown, então ele trata tudo como caracteres comuns e os exibe literalmente. Converter o texto antes de colar transforma os símbolos em formatação de verdade.",
  sections: {
    "what-the-symbols-are": {
      heading: "O que os símbolos realmente significam",
      body: "Markdown é uma convenção para descrever formatação usando apenas caracteres que você consegue digitar. Ele foi criado para que um documento faça sentido mesmo quando nada o renderiza. Os modelos de chat escrevem nele porque é compacto, sem ambiguidade, e aparece formatado corretamente na interface do chat.\n\nEste é o vocabulário completo que você provavelmente vai encontrar:\n\n| Você vê | Significa |\n| --- | --- |\n| `**bold**` | Texto em negrito |\n| `*italic*` ou `_italic_` | Texto em itálico |\n| `# Heading` | Título de nível 1 (mais cerquilhas, título menor) |\n| `- item` ou `* item` | Item de lista com marcadores |\n| `1. item` | Item de lista numerada |\n| Crases ao redor de `code` | Código em linha |\n| `> quote` | Citação em bloco |\n| `[text](url)` | Hiperlink |\n| `\\| a \\| b \\|` | Linha de tabela |\n\nNada está quebrado e nada foi corrompido no caminho. Você está olhando para instruções corretamente formadas que chegaram a um lugar sem interpretador.",
    },
    "why-word-cannot-read-it": {
      heading: "Por que o Word não consegue lê-lo",
      body: "O Word armazena a formatação como dados estruturados dentro do documento. Negrito é um atributo associado a um trecho de caracteres, não um par de asteriscos ao redor dele. Quando você cola texto simples, o Word interpreta cada caractere ao pé da letra, porque, do ponto de vista dele, um asterisco é um sinal de pontuação que alguém digitou de propósito.\n\nÉ por isso que as soluções improvisadas de sempre decepcionam:\n\n- **Colar especial → Texto formatado** não faz nada, porque não havia formatação na área de transferência para preservar. Ela continha apenas caracteres simples.\n- **Localizar e substituir** remove os asteriscos, mas deixa o texto sem negrito, então você perde a estrutura por completo em vez de ganhá-la.\n- **AutoFormatação** lida com alguns padrões, como caracteres de lista, mas não é um interpretador de Markdown e não vai mexer em `**bold**` nem em `## Heading`.\n\nO Google Docs se comporta da mesma forma pelo mesmo motivo. Notion, Obsidian e a maioria dos editores para desenvolvedores *interpretam* Markdown, e é por isso que o mesmo texto colado funciona corretamente neles, criando a impressão de que o Word é quem está fazendo algo errado.",
    },
    "three-ways-to-fix": {
      heading: "Três formas de obter o texto bem formatado",
      body: "Qual delas usar depende de você precisar da formatação ou apenas querer se livrar dela.\n\n**1. Converter para um documento Word.** A opção mais completa. [Converter Markdown para Word](/markdown-to-word) transforma a resposta em um `.docx` de verdade, com estilos de título reais, trechos em negrito, listas e tabelas — do tipo que o painel de navegação e o sumário do Word realmente reconhecem. Use quando o resultado vai virar um relatório ou qualquer coisa que outra pessoa vá editar.\n\n**2. Converter para texto formatado e colar.** [Converter Markdown para Google Docs](/markdown-to-google-docs) gera texto formatado que você pode copiar direto para o Google Docs, Word, Outlook ou qualquer editor que aceite HTML colado. Use quando você está inserindo uma seção em um documento que já existe.\n\n**3. Remover os símbolos por completo.** Às vezes você quer apenas prosa limpa, sem formatação nenhuma — para um e-mail, um campo de formulário, uma caixa de CMS ou uma mensagem de chat. [Remover formatação Markdown](/remove-markdown-formatting) apaga os caracteres de sintaxe mantendo cada palavra intacta, o que o localizar e substituir não consegue fazer com segurança.\n\nAs três ferramentas funcionam no navegador. Nada é enviado.",
    },
    "stopping-it-at-the-source": {
      heading: "Evitando o problema na origem",
      body: "Você também pode pedir ao modelo para não usar Markdown desde o início. Um prompt como *\"responda em prosa simples, sem formatação Markdown, sem asteriscos, sem cerquilhas e sem listas\"* funciona razoavelmente bem para respostas curtas.\n\nÉ menos confiável do que parece. A obediência tende a se perder ao longo de uma resposta longa, e conteúdo estruturado — qualquer coisa com passos, comparações ou dados — vai puxar o modelo de volta para listas e tabelas, porque essa é realmente a forma mais clara de apresentar a informação. Se a sua resposta contém uma tabela, você quase certamente quer a tabela; só quer que ela seja uma tabela de verdade.\n\nPara qualquer coisa longa ou estruturada, converter depois é o hábito mais confiável. Assim você mantém a versão legível na janela do chat e obtém uma versão bem formatada no seu documento.\n\nSe o seu problema específico é uma tabela, e não prosa, isso tem suas próprias particularidades — veja [como colar uma tabela do ChatGPT no Excel](/guides/paste-chatgpt-table-into-excel).",
    },
  },
  faqs: [
    { question: "Por que o texto do ChatGPT mostra asteriscos quando colo no Word?", answer: "Os asteriscos são sintaxe Markdown que marca texto em negrito e itálico. O Word não tem um interpretador de Markdown, então ele os trata como caracteres comuns e os exibe literalmente. Converter o Markdown para um documento Word ou para texto formatado primeiro transforma os símbolos em formatação de verdade." },
    { question: "Como colo a resposta do ChatGPT no Word com a formatação?", answer: "Converta primeiro. Converter Markdown para Word gera um .docx com estilos de título reais, negrito, listas e tabelas; Converter Markdown para Google Docs gera texto formatado que você pode colar diretamente em um documento existente. Colar a resposta bruta sempre vai mostrar os caracteres de sintaxe." },
    { question: "O Colar especial resolve os símbolos Markdown?", answer: "Não. O Colar especial preserva formatação que já existe na área de transferência, e o Markdown em texto simples não tem nenhuma — a formatação está codificada como caracteres, não como atributos. Não há nada para o Colar especial manter." },
    { question: "O que significa ## em um texto gerado por IA?", answer: "É a marca de um título. Uma cerquilha indica um título de primeiro nível, duas indicam um título de segundo nível, e assim por diante até seis. Em um editor que entende Markdown, as cerquilhas desaparecem e a linha aparece como um título estilizado." },
    { question: "Posso simplesmente localizar e substituir os asteriscos?", answer: "Pode, mas você vai apagar a formatação em vez de aplicá-la — o texto deixa de ser negrito e apenas perde os marcadores. Remover Markdown com segurança também significa tratar títulos, marcadores de lista, links e blocos de código, que é o que uma ferramenta dedicada faz de uma vez só." },
  ],
};
