import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Como colar uma tabela do ChatGPT no Excel",
  description: "Tabelas de IA colam em uma coluna só porque são texto simples, não células. Veja como obter linhas e colunas de verdade no Excel, Sheets ou Numbers.",
  h1: "Como colar uma tabela do ChatGPT no Excel ou Google Sheets",
  dek: "Por que a tabela inteira cai na coluna A, e as duas formas confiáveis de corrigir isso.",
  answer: "Uma tabela do ChatGPT é uma tabela Markdown com barras verticais — texto simples que usa caracteres | para sugerir colunas. Planilhas esperam limites de células, não barras, então cada linha cai em uma única coluna. Converter a tabela para XLSX ou CSV antes produz linhas e colunas de verdade, que abrem corretamente no Excel, Sheets e Numbers.",
  sections: {
    "why-it-lands-in-one-column": {
      heading: "Por que a tabela inteira cai na coluna A",
      body: "O que a janela do chat mostra é uma tabela renderizada. O que a área de transferência recebe, na maioria das vezes, é isto:\n\n```\n| Region | Q1 | Q2 |\n| --- | ---: | ---: |\n| Europe | 412 | 486 |\n| Asia | 377 | 381 |\n```\n\nIsso é uma tabela Markdown com barras verticais. As barras são caracteres comuns que *parecem* divisores de coluna para quem lê. A segunda linha, com seus traços e dois-pontos, indica a um renderizador Markdown onde o cabeçalho termina e como alinhar cada coluna.\n\nO Excel divide texto colado por tabulações, não por barras. Como não há tabulações, cada linha vira um valor único, e a tabela inteira se empilha na coluna A com as barras ainda visíveis. O Google Sheets e o Numbers se comportam exatamente igual.\n\nA linha de alinhamento é a prova de que isso nunca foi dado de planilha. Nenhuma exportação de planilha contém uma linha de hífens e dois-pontos.",
    },
    "the-fastest-fix": {
      heading: "A correção mais rápida: converter antes de colar",
      body: "Em vez de colar e reparar, converta a tabela para um formato que as planilhas já entendem.\n\n**Para Excel e Numbers**, o [Conversor de tabela Markdown para Excel](/markdown-table-to-excel) gera um arquivo `.xlsx` de verdade. Cole a tabela, baixe a planilha e abra. Números continuam números, a linha de cabeçalho continua sendo cabeçalho, e nada precisa ser dividido depois.\n\n**Para o Google Sheets**, o [Conversor de tabela Markdown para CSV](/markdown-table-to-csv) costuma ser mais prático. O CSV é importado nativamente por *Arquivo → Importar*, e você evita a viagem de ida e volta de baixar e reenviar que o XLSX exige no navegador. O conversor escapa aspas e vírgulas internas corretamente, que é onde as conversões feitas à mão normalmente quebram.\n\nAmbos rodam localmente no seu navegador, então os dados nunca saem da sua máquina — algo a considerar se a tabela contém informação que você não colaria em um site qualquer.",
    },
    "manual-methods": {
      heading: "Os métodos manuais, e quando valem a pena",
      body: "Se preferir não sair da planilha, há dois caminhos nativos que funcionam.\n\n**Texto para Colunas (Excel).** Cole a tabela bruta na coluna A, selecione-a, vá em *Dados → Texto para Colunas → Delimitado* e defina o delimitador como a barra vertical. Você ainda vai precisar apagar a linha de alinhamento e remover as colunas vazias criadas pelas barras no início e no fim de cada linha.\n\n**SPLIT (Google Sheets).** Com a tabela bruta na coluna A, use `=SPLIT(A1, \"|\")` e arraste para baixo, depois copie e cole como valores. A mesma limpeza se aplica.\n\nEsses métodos servem para uma única tabela pequena. Ficam trabalhosos rapidamente, e ambos deixam espaços em branco dentro de cada célula — os espaços que o Markdown usa para legibilidade passam a fazer parte do valor, então ` Europe ` não vai bater com `Europe` em uma fórmula de procura. Esse problema do espaço extra é a causa mais comum de uma tabela convertida parecer certa mas se comportar errado.\n\n**Uma observação sobre copiar:** se você selecionar arrastando a tabela *renderizada* na janela do chat em vez de usar o botão de copiar, alguns navegadores colocam texto separado por tabulações na área de transferência, que cola corretamente em colunas. É inconsistente entre navegadores e interfaces de chat, então vale tentar, mas não vale confiar.",
    },
    "google-sheets": {
      heading: "Levando a tabela para o Google Sheets",
      body: "O Sheets falha da mesma forma que o Excel — barras verticais não são um delimitador que ele reconhece, então cada linha cai em uma única célula da coluna A — mas os caminhos de saída são um pouco diferentes, e um deles é genuinamente conveniente.\n\n**Dividir texto em colunas.** Cole a tabela bruta em uma coluna, mantenha o intervalo colado selecionado e use *Dados → Dividir texto em colunas*. O Sheets oferece uma escolha de separador, incluindo um personalizado, então você pode defini-lo como o caractere de barra vertical. Ele também mostra um pequeno controle perto dos dados colados logo depois de qualquer colagem de texto delimitado, que faz a mesma coisa sem precisar ir ao menu. Como no Texto para Colunas do Excel, sobram a linha de alinhamento para apagar, colunas vazias em cada extremidade por causa das barras no início e no fim, e um espaço de preenchimento dentro de cada valor.\n\n**Importar um CSV.** *Arquivo → Importar* analisa um arquivo em vez de uma colagem, e permite dizer qual é o separador e se o texto deve ser convertido em números e datas. É essa a diferença que importa: uma importação decide os tipos de coluna de forma deliberada, enquanto uma colagem apenas tenta adivinhar. Passe a tabela pelo [Conversor de tabela Markdown para CSV](/markdown-table-to-csv) antes e não sobra nada para adivinhar — a linha de alinhamento desaparece, o preenchimento é removido, e as vírgulas dentro das células ficam entre aspas corretamente.\n\n**O Sheets como escala intermediária.** Depois que a tabela está em células de verdade, copiar esse intervalo carrega a grade junto. Colar do Sheets no Excel, Word, Slides, Docs ou em um e-mail mantém linhas e colunas intactas, porque a área de transferência agora contém dados tabulares em vez de uma linha de texto com barras. Se uma tabela precisa chegar a um aplicativo sem importação própria, passar primeiro por uma planilha é mais confiável do que brigar com o destino.\n\nUma coisa específica do Sheets para ficar de olho: valores como `3-4` ou `1/2` em uma célula convertida serão lidos como datas. Se uma coluna chegar cheia de datas que você não pediu, desfaça, formate a coluna de destino como texto simples e cole de novo.",
    },
    "tables-buried-in-prose": {
      heading: "Quando a tabela está no meio de uma resposta longa",
      body: "Muitas vezes a tabela que você quer é só uma parte de uma resposta muito maior, misturada com explicações acima e abaixo dela.\n\nO [Extrator de tabelas de um texto](/extract-table-from-text) encontra linhas em formato de tabela dentro do texto ao redor — delimitadas por barras ou por tabulações — e devolve apenas a tabela em CSV. Cole a resposta inteira e extraia os dados, em vez de selecionar linhas à mão na esperança de ter acertado os limites.\n\nDuas coisas valem verificar em qualquer tabela convertida antes de construir algo em cima dela:\n\n- **Números armazenados como texto.** Se uma coluna chega alinhada à esquerda no Excel, os valores são texto. Símbolos de moeda, separadores de milhar e sinais de porcentagem no original são as causas mais comuns. Selecione a coluna e use *Dados → Texto para Colunas → Concluir* para convertê-los.\n- **Células mescladas ou quebradas.** Tabelas Markdown não conseguem expressar células mescladas, então um modelo apresentando dados complexos às vezes simula isso com valores repetidos ou quebras de linha dentro da célula. Esses casos pedem uma decisão humana, não um conversor.\n\nSe o resto da resposta também precisa ir junto — títulos, listas, a explicação em volta da tabela — veja [por que texto de IA colado mostra ** e ##](/guides/markdown-symbols-in-word).",
    },
  },
  faqs: [
    { question: "Por que uma tabela do ChatGPT cola em uma coluna só no Excel?", answer: "Porque é uma tabela Markdown com barras verticais, ou seja, texto simples que usa caracteres | como divisores visuais. O Excel divide texto colado por tabulações, não por barras, então cada linha é tratada como um valor único e a tabela inteira se empilha em uma coluna só." },
    { question: "Como converter uma tabela Markdown para Excel?", answer: "Cole no conversor de tabela Markdown para Excel e baixe o arquivo .xlsx resultante. Ele produz linhas e colunas de verdade com o cabeçalho preservado, então não há nada para dividir ou limpar depois de abrir." },
    { question: "O que é a linha de traços e dois-pontos em uma tabela de IA?", answer: "É a linha de alinhamento do Markdown. Ela separa o cabeçalho do corpo e define o alinhamento das colunas — dois-pontos à direita significa alinhado à direita, dos dois lados significa centralizado. É sintaxe de formatação, não dado, e deve ser removida na conversão." },
    { question: "Por que minhas células convertidas têm espaços extras?", answer: "O Markdown preenche as células com espaços para legibilidade, e a divisão manual mantém esse preenchimento dentro do valor. Isso importa porque ' Europe ' não corresponde a 'Europe' em uma procura. Um bom conversor remove o preenchimento; se você dividir manualmente, aplique a função ARRUMAR (TRIM) aos resultados." },
    { question: "Posso colar uma tabela de IA direto no Google Sheets?", answer: "Não com as colunas intactas. Converter para CSV primeiro e importar por Arquivo → Importar é o caminho mais confiável, já que CSV é um formato que o Sheets interpreta nativamente e isso evita a viagem de baixar e reenviar o XLSX." },
  ],
};
