import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Quantos tokens tem meu prompt?",
  description: "Tokens são fragmentos menores que palavras, não palavras. Veja como funciona a tokenização, por que as contagens variam e como estimar o custo.",
  h1: "Quantos tokens tem meu prompt?",
  dek: "Por que 1.000 palavras nunca são 1.000 tokens, e o que isso significa para os limites de contexto e o custo.",
  answer: "Tokens são fragmentos menores que palavras, então as contagens nunca batem com a contagem de palavras. Em inglês comum, um token equivale em média a cerca de quatro caracteres ou três quartos de uma palavra — ou seja, 1.000 palavras dão aproximadamente 1.300 tokens. Código, escritas em outros idiomas e palavras incomuns consomem mais tokens por caractere, às vezes várias vezes mais.",
  sections: {
    "what-a-token-is": {
      heading: "O que um token realmente é",
      body: "Os modelos de linguagem não leem caracteres nem palavras. Eles leem tokens: fragmentos produzidos ao dividir o texto conforme um vocabulário fixo, aprendido a partir dos dados de treinamento.\n\nPalavras comuns costumam ser um único token. Palavras raras são quebradas em pedaços. Os espaços em branco normalmente ficam anexados ao início do token seguinte, e é por isso que a mesma palavra pode ter contagens diferentes dependendo de estar ou não no começo da frase.\n\nA palavra *unbelievable* não é um token só — provavelmente vira algo como `Un` + `believ` + `able`. Já *the* é um único token, e *international* também, porque apareceu com frequência suficiente no treinamento para ganhar sua própria entrada.\n\nÉ por isso que as contagens de tokens parecem imprevisíveis. A unidade não é linguística; é estatística. A frequência no corpus de treinamento determina se algo vira um token ou quatro.",
    },
    "rules-of-thumb": {
      heading: "Regras práticas que realmente funcionam",
      body: "Para texto em inglês:\n\n- **1 token ≈ 4 caracteres**\n- **1 token ≈ 0,75 palavras**\n- **1.000 palavras ≈ 1.300 tokens**\n- **Uma página padrão (~500 palavras) ≈ 650 tokens**\n\nEssas regras deixam de valer rapidinho fora do texto comum:\n\n| Tipo de conteúdo | Aproximadamente |\n| --- | --- |\n| Texto em inglês | 0,75 palavras por token |\n| Código | 2–3× mais tokens que texto equivalente |\n| JSON com chaves longas | Muito alto — pontuação e aspas são tokens separados |\n| Chinês, japonês, coreano | Muitas vezes 1–2 tokens *por caractere* |\n| Cirílico, devanágari, árabe | Normalmente 2–3× o inglês para o mesmo significado |\n| URLs e hashes | Altíssimo — strings aleatórias tokenizam muito mal |\n| Espaços repetidos | Cada sequência pode ser um token próprio |\n\nA diferença entre idiomas é significativa e pouco percebida: a mesma frase em japonês pode custar várias vezes mais do que em inglês, o que afeta tanto o custo quanto a quantidade de texto que cabe na janela de contexto.",
    },
    "why-models-differ": {
      heading: "Por que a contagem muda de um modelo para outro",
      body: "Cada família de modelos usa seu próprio tokenizador, com seu próprio vocabulário, então o mesmo texto gera contagens diferentes.\n\nOs modelos GPT usam variantes de byte-pair encoding — `cl100k_base` para os modelos da era GPT-4, `o200k_base` para os mais novos. O Claude usa um tokenizador diferente, com outro vocabulário. Modelos abertos como Llama e Mistral têm, cada um, o seu próprio.\n\nDiferenças de 10–20% entre famílias no mesmo texto em inglês são normais, e a distância aumenta em código e em textos em outros idiomas, onde os vocabulários divergem mais.\n\nNa prática, isso significa:\n\n- Uma contagem feita com um tokenizador é uma **estimativa** para qualquer outro modelo.\n- Só o tokenizador do próprio provedor dá o número exato usado na cobrança.\n- Planeje com margem de folga em vez de tentar encaixar exatamente no limite.\n\nNosso [Contador de tokens](/token-counter) mostra lado a lado a contagem do GPT-4o e uma estimativa para o Claude, o que normalmente basta para saber se um prompt está confortavelmente dentro do limite ou perigosamente perto dele.",
    },
    "why-it-matters": {
      heading: "Por que o número importa",
      body: "**Custo.** O preço das APIs é por token, com entrada e saída cobradas separadamente, e a saída costuma custar várias vezes mais. Dobrar o tamanho de um prompt de sistema dobra esse custo em cada chamada — o tipo de coisa que passa despercebida nos testes e fica cara em volume.\n\n**Limites de contexto.** A janela cobre *tudo*: prompt de sistema, histórico da conversa, documentos recuperados, a mensagem atual e o espaço reservado para a resposta. Conversas longas falham não porque uma mensagem específica seja longa, mas porque o histórico se acumula.\n\n**Truncamento.** Quando a entrada excede o limite, algo é descartado — muitas vezes em silêncio, e muitas vezes o conteúdo mais antigo. Um modelo que \"esqueceu\" suas instruções frequentemente apenas as teve truncadas.\n\n**Divisão para recuperação.** Dividir documentos para embeddings funciona em tokens, não em caracteres. Partes dimensionadas por contagem de caracteres ficam inconsistentes, e partes cortadas no meio de uma frase são recuperadas com baixa qualidade. Para quebrar textos longos em pedaços utilizáveis, o [Dividir texto em partes](/text-splitter) corta perto dos limites de parágrafo em vez de no meio das palavras.",
    },
    "reducing-tokens": {
      heading: "Como reduzir a contagem sem perder significado",
      body: "As reduções de maior impacto, mais ou menos nesta ordem:\n\n1. **Enxugue o histórico da conversa.** Em chats longos, ele supera todo o resto. Resuma os turnos antigos em vez de reenviá-los na íntegra.\n2. **Corte instruções redundantes.** Repetir uma regra de três jeitos não a torna três vezes mais obedecida. O que ela faz, com certeza, é triplicar o custo dessa regra.\n3. **Remova artefatos de formatação.** Caracteres invisíveis, espaços repetidos e linhas decorativas de separação tokenizam, e uma fileira de quarenta hífens pode custar mais que a frase logo acima. O [Remover caracteres invisíveis](/remove-invisible-characters) limpa os que você não consegue ver.\n4. **Encurte as chaves do JSON** em prompts estruturados. `{\"n\": ...}` em vez de `{\"customer_full_name\": ...}`, multiplicado por mil registros, faz uma diferença enorme.\n5. **Envie apenas os trechos relevantes.** Recuperar três parágrafos pertinentes é melhor do que colar o documento inteiro, e normalmente gera respostas melhores, além de mais baratas.\n\nO que *não* ajuda: remover pontuação comum, apagar artigos ou escrever em estilo telegráfico. A economia é marginal e o estrago na qualidade da resposta não é.",
    },
  },
  faqs: [
    { question: "Quantos tokens são 1.000 palavras?", answer: "Cerca de 1.300 tokens para texto comum em inglês, com base em aproximadamente 0,75 palavras por token. Código, JSON e textos em outros idiomas ficam bem acima — chinês, japonês e coreano costumam usar de um a dois tokens por caractere." },
    { question: "Por que a contagem de tokens é diferente no GPT e no Claude?", answer: "Cada família de modelos usa seu próprio tokenizador, com um vocabulário aprendido diferente, então o mesmo texto é dividido de formas distintas. Diferenças de 10–20% em texto em inglês são normais, e a distância é maior em código e em textos em outros idiomas." },
    { question: "O que é um token em um modelo de IA?", answer: "Um fragmento de texto do vocabulário fixo do modelo. Palavras comuns costumam ser um único token, enquanto palavras raras se dividem em vários pedaços — então 'unbelievable' pode virar três tokens enquanto 'international' é apenas um." },
    { question: "Espaços e pontuação contam como tokens?", answer: "Sim. Os espaços normalmente ficam anexados ao início do token seguinte, e a pontuação frequentemente vira um token próprio. Longas sequências de espaços repetidos ou linhas decorativas de separação podem consumir uma quantidade surpreendente." },
    { question: "Como posso reduzir meu uso de tokens?", answer: "Comece enxugando o histórico acumulado da conversa — em chats longos, ele domina todo o resto. Depois, remova instruções duplicadas, limpe caracteres invisíveis e espaços repetidos, encurte as chaves do JSON e envie apenas o trecho relevante do documento em vez do conteúdo inteiro." },
  ],
};
