import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "7 Sinais de que um texto foi escrito por IA",
  description: "Os sete padrões de formatação e estilo que aparecem em textos gerados por IA, como verificar cada um e por que nenhum deles é prova por si só.",
  h1: "Sete sinais de que um texto foi escrito por IA",
  dek: "Quatro que dá para medir, três que só dá para perceber — e os limites honestos dos dois.",
  answer: "Os sinais mais confiáveis são mecânicos: travessões em ritmo constante, aspas curvas tipográficas, caracteres Unicode invisíveis e listas com marcadores encabeçados por emojis. Sinais de estilo — vocabulário evasivo, a construção 'não apenas X, mas Y' e parágrafos de comprimento uniforme demais — são mais fracos. Nenhum deles prova nada isoladamente; são padrões, não evidências.",
  sections: {
    "mechanical-signs": {
      heading: "Os quatro sinais mecânicos que dá para medir de verdade",
      body: "Estes são contáveis. Você pode passá-los por uma ferramenta e obter um número em vez de uma impressão, e é isso que os torna mais úteis do que a detecção baseada em intuição.\n\n**1. Travessões em ritmo constante.** Modelos de chat produzem o travessão (—) com muito mais consistência do que as pessoas, porque digitá-lo exige um atalho de teclado que a maioria dos escritores nunca aprendeu. Um ou dois em um documento longo é normal. Mais ou menos um por parágrafo, distribuídos de forma uniforme, não é. O [guia sobre travessões](/guides/why-chatgpt-uses-em-dashes) explica por que esse hábito está tão enraizado.\n\n**2. Aspas curvas e pontuação tipográfica.** A saída de IA tende a chegar com aspas direcionais (\" \"), apóstrofos curvos (') e o caractere de reticências de verdade (…) em vez de três pontos finais. Processadores de texto também produzem isso automaticamente, então esses sinais só significam algo em contextos sem autocorreção — um campo de texto simples, um comentário de código, um arquivo CSV.\n\n**3. Caracteres Unicode invisíveis.** Espaços de largura zero, espaços inseparáveis e espaços estreitos inseparáveis frequentemente sobrevivem a um copiar e colar de uma janela de chat. São indetectáveis a olho nu e formam o marcador mecânico mais forte de todos, porque quase nada que uma pessoa digita à mão os introduz.\n\n**4. Listas com marcadores encabeçados por emojis.** Respostas estruturadas com um emoji decorativo no início de cada item, cabeçalhos de seção feitos de texto em negrito em vez de títulos de verdade e listas aninhadas em três níveis são um estilo de casa que as interfaces de chat incentivam e que a maioria dos escritores humanos não usa.",
    },
    "stylistic-signs": {
      heading: "Os três sinais de estilo — mais fracos, mas que vale conhecer",
      body: "Padrões de estilo são muito mais fáceis de interpretar errado, porque muitos textos humanos cuidadosos os compartilham. Trate-os como motivo para olhar mais de perto, nunca como conclusão.\n\n**5. Enquadramento evasivo e perfeitamente equilibrado.** Frases que apresentam toda questão como tendo dois lados razoáveis, parágrafos que abrem repetindo a pergunta e linhas finais que resumem sem acrescentar nada. Isso vem de um treinamento que recompensa ser útil e não se comprometer ao mesmo tempo.\n\n**6. A construção \"não apenas X, mas Y\".** Junto com \"vale ressaltar que\", \"mergulhar em\", \"navegar pelas complexidades de\" e \"no mundo acelerado de hoje\". Essas frases não são palavras proibidas — são português comum. O que chama atenção é a frequência com que se acumulam em um único texto curto.\n\n**7. Estrutura uniforme demais.** Parágrafos de comprimento quase idêntico, seções com um número suspeitamente igual de itens e uma conclusão que espelha a introdução. Rascunhos humanos são mais irregulares; um parágrafo fica longo porque o autor tinha mais a dizer sobre aquele assunto específico.\n\nOs sinais de vocabulário, em particular, se desgastam rápido. Toda lista de \"palavras de IA\" que circula acaba absorvida pela forma como as pessoas escrevem e pelo ajuste da próxima geração de modelos. Os sinais mecânicos são mais duradouros porque são subprodutos da codificação, não do estilo.",
    },
    "how-to-check": {
      heading: "Como verificar um documento de uma só vez",
      body: "Uma ordem prática de operações, da verificação mais barata à mais cara:\n\n1. **Procure caracteres invisíveis.** É a verificação de maior sinal e menor esforço. Cole o texto no [verificador de caracteres invisíveis](/remove-invisible-characters) — ele lista cada espaço de largura zero, hífen suave, marca de ordem de bytes e marca direcional que encontrar, com as contagens.\n2. **Conte os artefatos mecânicos juntos.** A [ferramenta de limpeza de texto de IA](/clean-ai-text) aponta travessões, aspas curvas, caracteres invisíveis e emojis em uma única passada, então dá para ver se vários sinais aparecem juntos em vez de perseguir um de cada vez.\n3. **Leia em busca dos padrões de estilo.** Só depois de ter as contagens. Números primeiro, para você não se convencer sozinho de uma conclusão.\n4. **Pese o contexto.** Texto colado do Word vai trazer aspas curvas independentemente de quem o escreveu. Texto digitado diretamente em um campo simples, não.\n\nO que importa é a coocorrência. Um único travessão não significa nada. Travessões *e* aspas curvas *e* dois espaços de largura zero *e* marcadores com emojis, em um documento digitado diretamente em um formulário de texto simples, são uma combinação genuinamente incomum.",
    },
    "why-not-proof": {
      heading: "Por que nada disso é prova",
      body: "Cada sinal acima tem uma explicação inocente.\n\nO Word e o Google Docs convertem hífens duplos em travessões e aspas retas em aspas curvas automaticamente. Copiar de qualquer site moderno pode carregar caracteres invisíveis. Editores profissionais escrevem exatamente no registro equilibrado e evasivo que parece gerado por máquina. Pessoas que escrevem em inglês como segunda língua costumam usar um estilo mais formal e estruturalmente regular, e é justamente por isso que detectores comerciais de IA sinalizam os textos delas em taxas muito maiores.\n\nHá também a circularidade óbvia: uma pessoa pode colar a saída de IA em um editor de texto, fazer uma limpeza e remover todos os sinais mecânicos em cerca de dez segundos. Os sinais mais fáceis de medir são também os mais fáceis de apagar.\n\nEntão a posição honesta é esta. A análise de formatação diz **quais caracteres estão em um documento**. Ela não pode dizer quem os colocou lá. Nossas ferramentas deliberadamente mostram contagens e nunca emitem um veredito, porque um veredito seria um palpite usando um número como disfarce. Se você precisa saber se uma pessoa escreveu algo, a resposta vem de conversar com ela sobre isso — histórico de rascunhos, fontes e a capacidade de explicar o próprio argumento — não de contar travessões.",
    },
  },
  faqs: [
    { question: "Qual é o sinal mais confiável de que um texto foi escrito por IA?", answer: "Caracteres Unicode invisíveis, como espaços de largura zero, são o marcador mecânico mais forte, porque a digitação comum quase nunca os produz, enquanto um copiar e colar de uma janela de chat frequentemente produz. Ainda assim, eles também podem vir de texto copiado de um site, então indicam a origem da colagem, não a autoria." },
    { question: "Detectores de IA realmente funcionam?", answer: "Não de forma confiável. Eles produzem falsos positivos em textos humanos — afetando desproporcionalmente quem escreve em inglês como segunda língua — e podem ser enganados com edições leves. A análise de formatação consegue contar artefatos concretos, mas nenhuma ferramenta, incluindo as nossas, consegue estabelecer autoria a partir do texto sozinho." },
    { question: "Usar travessões ou aspas curvas significa que vou ser acusado de usar IA?", answer: "Não deveria, e é uma base ruim para uma acusação. O Word e o Google Docs geram os dois automaticamente a partir da digitação comum. Se você está preocupado com a aparência de um documento, converter a pontuação para ASCII simples remove os artefatos sem mudar nenhuma palavra do seu texto." },
    { question: "Posso remover esses sinais de um texto gerado por IA?", answer: "Sim, e rapidamente — e é exatamente por isso que eles são evidências fracas. Substituir travessões, normalizar aspas e remover caracteres invisíveis leva segundos. Isso é motivo para ser cético em relação a alegações de detecção, não uma técnica para passar um trabalho como seu." },
  ],
};
