import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Por que o ChatGPT usa tantos travessões?",
  description: "O ChatGPT usa travessões porque aprendeu com textos editados. Veja por que esse hábito é tão consistente e como removê-los sem estragar o texto.",
  h1: "Por que o ChatGPT usa tantos travessões?",
  dek: "O sinal de pontuação que virou assinatura de IA — e o que fazer a respeito.",
  answer: "O ChatGPT usa travessões porque foi treinado em textos profissionalmente editados — livros, ensaios e jornalismo — onde o travessão é o recurso padrão para destacar uma frase. O modelo reproduz esse hábito com muito mais consistência do que escritores humanos comuns, que raramente digitam esse caractere. É essa diferença de consistência, e não o sinal em si, que faz o travessão parecer uma assinatura de IA.",
  sections: {
    "where-it-comes-from": {
      heading: "De onde vem esse hábito",
      body: "Grandes modelos de linguagem aprendem pontuação da mesma forma que aprendem todo o resto: absorvendo padrões dos dados de treinamento. Esses dados são fortemente concentrados em **textos publicados e profissionalmente editados** — livros, jornalismo de fôlego, ensaios e documentação. Nesse universo, o travessão é completamente comum. Revisores o usam o tempo todo para isolar um comentário, introduzir um resumo ou criar uma pausa antes da oração final.\n\nA escrita informal da internet não se parece em nada com isso. Em mensagens de chat, posts de fórum e e-mails, as pessoas usam vírgulas, parênteses e pontos finais. A maioria nunca digita um travessão, porque em um teclado padrão não existe tecla para ele.\n\nHá ainda uma segunda pressão sobre os dados de treinamento. Os modelos são ajustados para produzir textos que os leitores avaliam como claros e bem escritos, e o travessão é excepcionalmente bom nessa função. É o sinal mais flexível da pontuação em inglês — pode substituir vírgula, dois-pontos, ponto e vírgula ou um par de parênteses. Quando uma frase admitiria vários sinais diferentes, recorrer ao travessão é sempre uma escolha defensável. Um sistema otimizado para gerar texto fluente e confiante vai cair nele repetidas vezes.",
    },
    "why-it-reads-as-ai": {
      heading: "Por que o travessão virou um indício de IA",
      body: "O travessão não se tornou suspeito por ser raro. Tornou-se suspeito por **aparecer com tanta consistência**.\n\nDigitar um exige esforço deliberado. No Mac é <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>; no Windows é <kbd>Alt</kbd> + <kbd>0151</kbd> ou uma regra de autocorreção. Na maioria dos teclados de celular, ele fica escondido atrás de um toque longo. Então, quando uma pessoa escreve um travessão, em geral é uma escolha estilística consciente, e ele aparece de forma esporádica — algumas vezes em um documento longo, concentrado nos pontos em que o autor queria uma pausa dramática.\n\nUm modelo de linguagem não tem esse atrito. Cada caractere custa o mesmo. O resultado é uma impressão digital estatística bem marcada:\n\n- Os travessões aparecem em ritmo constante em todos os parágrafos, em vez de surgir em blocos.\n- São usados com frequência **em pares**, envolvendo uma frase intercalada, onde a maioria das pessoas usaria vírgulas.\n- Aparecem em registros que normalmente nunca os teriam, como uma resposta curta, um item de lista ou um relatório de bug.\n\nNenhum desses padrões está errado. Eles são apenas mais regulares do que a escrita humana costuma ser, e regularidade é exatamente o que os leitores percebem.",
    },
    "how-to-remove": {
      heading: "Como remover travessões sem quebrar as frases",
      body: "O erro é substituir todo travessão por um hífen. O hífen é um caractere diferente, com outra função, e o resultado parece erro de digitação, não texto limpo. Combine a substituição com o papel que o travessão estava desempenhando.\n\n**Um par de travessões envolvendo um comentário** geralmente vira um par de vírgulas. Se o comentário for uma digressão de verdade, os parênteses funcionam melhor.\n\n**Um travessão único antes de uma conclusão** está fazendo o papel de dois-pontos. Troque por dois-pontos, ou encerre a frase e comece outra.\n\n**Um travessão único no meio da frase** muitas vezes marca uma quebra mais forte do que a frase realmente precisa. Dividir em duas frases quase sempre soa melhor do que qualquer sinal substituto.\n\n| O que o travessão está fazendo | Substituição melhor |\n| --- | --- |\n| Envolver um comentário leve | Vírgulas |\n| Envolver uma digressão | Parênteses |\n| Introduzir um resumo | Dois-pontos |\n| Marcar uma quebra forte | Ponto final, divida a frase |\n| Indicar um intervalo (2020—2024) | En dash, não travessão |\n\nSe você estiver trabalhando em um documento longo, a ferramenta [Remover travessões do texto](/remove-em-dashes) substitui todos os travessões pela alternativa que você escolher e informa quantas substituições foram feitas, para você conferir a contagem com a sua própria leitura em vez de confiar em uma substituição silenciosa.",
    },
    "when-to-keep": {
      heading: "Quando vale a pena manter o travessão",
      body: "Eliminar todos os travessões da sua escrita é um exagero na correção. O sinal existe porque faz algo que as alternativas não fazem: cria uma pausa com mais força que uma vírgula e menos finalidade que um ponto final, sem o ar burocrático do ponto e vírgula.\n\nMantenha-o quando:\n\n- A frase realmente precisa de uma interrupção forte, e a vírgula seria suave demais.\n- Você está citando uma fonte que usou travessão. Editar a pontuação dentro de uma citação altera a citação.\n- O estilo da casa pede o uso. A maioria das editoras de livros e muitas redações usam travessões livremente.\n- Você está escrevendo ficção ou ensaios pessoais, onde o ritmo importa mais do que parecer neutro em relação a máquinas.\n\nO objetivo realista não é zero travessões. É que os travessões apareçam porque você os escolheu, em uma frequência que reflita a sua própria voz. Um ou dois em um artigo longo soam deliberados. Um em cada parágrafo soa como padrão automático.",
    },
    "not-proof": {
      heading: "Travessões não são prova de texto gerado por IA",
      body: "Isso merece ser dito com clareza, porque muita orientação na internet erra nesse ponto: **a presença de travessões não prova nada.**\n\nMuitos textos escritos por pessoas estão cheios deles. O Microsoft Word e o Google Docs convertem hífen duplo em travessão automaticamente, então escritores os produzem sem nunca escolher o caractere. Quem foi treinado em redação editorial os usa por instinto. Publicações inteiras os tornam obrigatórios.\n\nNão existe forma confiável de detectar texto gerado por IA pela pontuação, e as ferramentas comerciais que afirmam o contrário têm taxas de falso positivo bem documentadas — com falantes não nativos de inglês afetados de forma desproporcional. Tratar um travessão como evidência tem custos reais quando a acusação recai sobre um estudante ou um colega.\n\nO que a análise de formatação pode dizer com honestidade é mecânico: quantos travessões há neste documento, quantas aspas curvas, quantos caracteres invisíveis. São contagens, não vereditos. Nossa ferramenta [Limpar texto do ChatGPT e IA](/clean-ai-text) informa exatamente esses números e não faz nenhuma afirmação sobre quem ou o quê escreveu o texto, que é a única postura defensável para uma ferramenta de formatação.\n\nSe você quiser o panorama completo de quais artefatos de formatação acompanham textos de IA, o guia sobre os [sinais de texto escrito por IA](/guides/signs-of-ai-written-text) cobre o restante.",
    },
  },
  faqs: [
    { question: "Usar travessões faz meu texto parecer gerado por IA?", answer: "Não por si só. Travessões são padrão em textos editados em inglês e aparecem em toda a escrita humana, em parte porque o Word e o Google Docs os criam automaticamente a partir de hífens duplos. O que soa artificial é uma frequência alta e uniformemente espaçada — cerca de um por parágrafo ao longo de todo o documento — geralmente acompanhada de outros artefatos, como aspas curvas e listas com emojis como marcadores." },
    { question: "Pelo que devo substituir um travessão?", answer: "Combine a substituição com a função do sinal. Um par que envolve um comentário vira vírgulas ou parênteses; um travessão único que introduz uma conclusão vira dois-pontos; um travessão que marca uma quebra forte geralmente fica melhor como duas frases separadas. Evite substituir o travessão por um hífen, que é um caractere diferente com outra finalidade." },
    { question: "Por que o ChatGPT usa travessões em vez de vírgulas?", answer: "O travessão é o sinal mais flexível da pontuação em inglês, capaz de substituir vírgula, dois-pontos, ponto e vírgula ou parênteses. Quando vários sinais seriam gramaticalmente aceitáveis, ele é sempre uma escolha segura, então um modelo ajustado para produzir prosa fluente o seleciona com frequência desproporcional." },
    { question: "Posso impedir o ChatGPT de usar travessões?", answer: "Você pode pedir diretamente no prompt, por exemplo 'do not use em dashes; use commas or separate sentences'. A obediência é imperfeita e tende a se perder ao longo de uma resposta extensa, então em geral é mais rápido escrever normalmente e remover os travessões depois." },
    { question: "Travessão é a mesma coisa que hífen?", answer: "Não. O hífen (-, U+002D) une palavras compostas. O en dash (–, U+2013) marca intervalos como 2020–2024. O travessão (—, U+2014) destaca uma frase dentro de um período. São três caracteres distintos, de largura crescente, e não são intercambiáveis." },
  ],
};
