import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Gedankenstrich, Bis-Strich oder Bindestrich: Der Unterschied",
  description: "Drei Zeichen, drei Aufgaben. Wann du welchen Strich verwendest, wie du ihn tippst und warum Verwechslungen Probleme verursachen.",
  h1: "Gedankenstrich vs. Bis-Strich vs. Bindestrich",
  dek: "Drei verschiedene Unicode-Zeichen, die ähnlich aussehen und nicht austauschbar sind.",
  answer: "Ein Bindestrich (-) verbindet zusammengesetzte Wörter: bekannt-bekannt. Ein Bis-Strich (–) kennzeichnet Bereiche und Verbindungen: Seiten 20–24. Ein Gedankenstrich (—) grenzt einen Einschub im Satz ab, wie ein stärkeres Komma. Es sind drei eigenständige Unicode-Zeichen mit zunehmender Breite, und Parser, Suche und Satzprogramme behandeln sie jeweils unterschiedlich.",
  sections: {
    "the-three-characters": {
      heading: "Die drei Zeichen im Überblick",
      body: "Die englischen Namen stammen aus dem historischen Bleisatz: Ein En Dash war so breit wie ein Großbuchstabe N, ein Em Dash so breit wie ein M.\n\n| Zeichen | Name | Codepunkt | Breite | Hauptverwendung |\n| --- | --- | --- | --- | --- |\n| - | Hyphen-Minus (Bindestrich-Minus) | U+002D | Kürzester | Zusammengesetzte Wörter |\n| – | En Dash (Bis-Strich) | U+2013 | Mittel | Bereiche und Verbindungen |\n| — | Em Dash (Gedankenstrich) | U+2014 | Längster | Einschübe im Satz |\n\nDas erste Zeichen liegt auf deiner Tastatur. Die beiden anderen nicht – und genau das ist die praktische Wurzel der meisten Verwechslungen: Viele tippen einen Bindestrich, wo eigentlich ein Bis- oder Gedankenstrich hingehört, weil es das einzige Zeichen ist, das ohne Tastenkombination verfügbar ist.",
    },
    "the-hyphen": {
      heading: "Der Bindestrich",
      body: "Der Bindestrich verbindet Dinge zu einer Einheit.\n\n- **Zusammengesetzte Wörter und Mehrwortverbindungen**: ein *state-of-the-art*-Verfahren, ein *well-known* author. Im Englischen entfällt der Bindestrich oft, wenn die Wortgruppe hinter dem Nomen steht: the author is *well known*.\n- **Manche Präfixe**, besonders um Kollisionen oder Mehrdeutigkeiten zu vermeiden: *re-elect*, *co-owner*.\n- **Worttrennung am Zeilenende** im Blocksatz.\n- **Zusammengesetzte Zahlen**: *twenty-three*.\n\nTechnisch gesehen ist das Tastaturzeichen das *Hyphen-Minus* – ein einziger Codepunkt, der als Bindestrich, Minuszeichen und Kommandozeilen-Flag dient, geerbt von Schreibmaschinen und frühem ASCII. Unicode hat zwar ein eigenes Hyphen (U+2010) und Minuszeichen (U+2212), aber praktisch nichts verwendet sie, und du solltest auch nicht damit anfangen: `-` ist das, was Parser, Shells und URLs erwarten.",
    },
    "the-en-dash": {
      heading: "Der Bis-Strich (En Dash)",
      body: "Der Bis-Strich bedeutet *bis*, *von … bis* oder *zwischen*. Er verknüpft, statt zu verbinden.\n\n- **Zahlenbereiche**: Seiten *20–24*, *2020–2024*, *9–17 Uhr*. Stilvorgaben raten davon ab, ihn mit Wörtern zu mischen: Schreibe *von 2020 bis 2024*, nicht *von 2020–2024*.\n- **Verbindungen und Gegenüberstellungen eigenständiger Größen**: die Rallye *Paris–Dakar*, eine *Arzt–Patient*-Beziehung, die *Ost–West*-Achse. Der Unterschied zum Bindestrich zählt hier: *Franco-German* mit Bindestrich suggeriert eine verschmolzene Einheit, während *France–Germany* mit Bis-Strich zwei Parteien in Beziehung meint.\n- **Zusammengesetzte Attribute, bei denen ein Teil bereits mehrteilig ist**: eine *post–World War II*-Vereinbarung. Ein Bindestrich würde sich dort nur auf „World“ beziehen.\n- **Spielstände und Abstimmungsergebnisse**: ein *3:1*-Sieg bzw. englisch *3–1*.\n\nBis-Striche werden am seltensten verwendet und am häufigsten durch Bindestriche ersetzt. In Fließtext ist das eine geringfügige typografische Ungenauigkeit, die kaum jemand bemerkt. In Daten ist sie nicht geringfügig: Ein Datumsbereich mit Bis-Strich wird von einem regulären Ausdruck, der nach einem Bindestrich sucht, nicht gefunden.",
    },
    "the-em-dash": {
      heading: "Der Gedankenstrich (Em Dash)",
      body: "Der Gedankenstrich grenzt einen Einschub ab und erzeugt einen stärkeren Bruch als ein Komma, aber einen weicheren als ein Punkt.\n\n- **Als Paar um einen Einschub**: *The results — which nobody expected — were clear.*\n- **Einzeln vor einer Pointe oder Wendung**: *She checked everything twice — and still missed it.*\n- **Zur Kennzeichnung abgebrochener Rede** in Dialogen.\n\n**Die Leerzeichenfrage** ist die einzige echte Stildifferenz. Die US-amerikanische Konvention (Chicago Manual of Style) setzt Gedankenstriche ohne Leerzeichen: *word—word*. Die britische Konvention (Oxford und die meisten britischen Zeitungen) verwendet stattdessen einen Bis-Strich mit Leerzeichen: *word – word*. Beides ist korrekt; entscheidend ist die Einheitlichkeit innerhalb eines Dokuments. Im Deutschen ist übrigens der Bis-Strich mit Leerzeichen (*Wort – Wort*) die Standardform für Gedankenstriche. KI-Ausgaben verwenden typischerweise den englischen Em Dash mit Leerzeichen – *word — word* – eine Mischform beider Traditionen, die für geschulte Lektoren subtil falsch aussieht.\n\nDer Gedankenstrich ist außerdem das Zeichen, das zum inoffiziellen Erkennungsmerkmal von KI-Texten geworden ist, weil Modelle ihn viel konsequenter einsetzen als Menschen. Mehr dazu in [warum ChatGPT so viele Gedankenstriche verwendet](/guides/why-chatgpt-uses-em-dashes).",
    },
    "typing-them": {
      heading: "So tippst du die einzelnen Striche",
      body: "| Plattform | Bis-Strich (–) | Gedankenstrich (—) |\n| --- | --- | --- |\n| macOS | <kbd>Option</kbd> + <kbd>-</kbd> | <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd> |\n| Windows | <kbd>Alt</kbd> + <kbd>0150</kbd> | <kbd>Alt</kbd> + <kbd>0151</kbd> |\n| Linux | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2013 | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2014 |\n| Word / Docs | Zwei Bindestriche zwischen Wörtern werden automatisch umgewandelt | Zwei Bindestriche werden automatisch umgewandelt |\n| HTML | `&ndash;` | `&mdash;` |\n| iOS / Android | Bindestrich-Taste lange drücken | Bindestrich-Taste lange drücken |\n\nDie Windows-Alt-Codes erfordern einen Ziffernblock – ein Grund, warum so viele Laptop-Nutzer diese Zeichen schlicht nie tippen.",
    },
    "when-it-breaks-things": {
      heading: "Wann der Unterschied wirklich Probleme macht",
      body: "In Fließtext ist ein Bindestrich an Stelle eines Bis-Strichs eine typografische Kleinigkeit. Außerhalb von Fließtext sind es drei eigenständige Codepunkte, und der Unterschied ist funktional:\n\n- **Suchen und Ersetzen** gleicht Zeichen exakt ab. Eine Suche nach `2020-2024` findet `2020–2024` nicht.\n- **Shell-Befehle** benötigen U+002D. Ein `--force`, das aus einem Dokument eingefügt wurde, in dem die Autokorrektur es in einen Gedankenstrich verwandelt hat, ist kein Flag – und die Fehlermeldung wird Striche nicht einmal erwähnen.\n- **CSV und JSON** behandeln Bis- und Gedankenstriche als normalen Text, was meist harmlos ist – bis ein Wert nicht mit einem Schlüssel übereinstimmt, obwohl er es sollte.\n- **URLs und Slugs** akzeptieren nur den ASCII-Bindestrich.\n- **Sortierung und Deduplizierung** behandeln die drei Zeichen als unterschiedlich, sodass scheinbar identische Einträge nicht gruppiert werden.\n\nWenn du Striche in einem Dokument vereinheitlichen musst, ersetzt [Gedankenstriche aus Text entfernen](/remove-em-dashes) sie durch ein Ersatzzeichen deiner Wahl und zeigt die Anzahl an – so kannst du prüfen, ob die Zahl deiner Erwartung entspricht, statt einem stillen Ersetzen zu vertrauen. Die verwandte Falle mit Anführungszeichen behandelt [warum typografische Anführungszeichen Code zerstören](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "Was ist der Unterschied zwischen Gedankenstrich und Bis-Strich?", answer: "Ein Bis-Strich (–, U+2013) bedeutet „bis“ und kennzeichnet Bereiche wie 2020–2024. Ein Gedankenstrich (—, U+2014) grenzt einen Einschub im Satz ab, wie ein stärkeres Komma. Der Gedankenstrich ist ungefähr doppelt so breit, und beide sind eigenständige Unicode-Zeichen." },
    { question: "Wann verwende ich einen Bindestrich statt eines Gedankenstrichs?", answer: "Verwende einen Bindestrich, um Wörter zu einer Einheit zu verbinden: well-known, twenty-three, re-elect. Wenn du einen Bereich, eine Verbindung zweier Parteien oder einen Einschub im Satz meinst, brauchst du stattdessen einen Bis- oder Gedankenstrich." },
    { question: "Kommen um Gedankenstriche Leerzeichen?", answer: "Das hängt vom Stil ab. Die US-Konvention setzt sie ohne Leerzeichen (word—word), die britische verwendet meist einen Bis-Strich mit Leerzeichen (word – word). Im Deutschen ist der Bis-Strich mit Leerzeichen üblich. Beides ist korrekt; entscheidend ist die Einheitlichkeit im Dokument." },
    { question: "Wie tippe ich einen Gedankenstrich?", answer: "Unter macOS drückst du Option + Shift + Bindestrich. Unter Windows hältst du Alt und tippst 0151 auf dem Ziffernblock. In Word und Google Docs werden zwei Bindestriche zwischen Wörtern automatisch umgewandelt. Auf Smartphones drückst du die Bindestrich-Taste lange." },
    { question: "Ist es schlimm, wenn ich statt eines Bis-Strichs einen Bindestrich verwende?", answer: "In Fließtext ist es eine kleine Ungenauigkeit, die die meisten Leser nicht bemerken. In Daten, Code, URLs oder allem, was durchsucht oder geparst wird, ist es sehr wohl relevant – denn es sind drei unterschiedliche Zeichen, und ein exakter Abgleich schlägt fehl." },
  ],
};
