import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "ChatGPT-Unterhaltung als PDF oder Word exportieren",
  description: "Drucken zu PDF schneidet den Chat ab und verliert Formatierung. So wandelst du eine Unterhaltung in ein sauberes PDF- oder Word-Dokument um.",
  h1: "ChatGPT-Unterhaltung als PDF oder Word exportieren",
  dek: "Warum das Drucken der Seite scheitert und wie du ein Dokument erhältst, das du wirklich verschicken würdest.",
  answer: "Das direkte Drucken der Chat-Seite schneidet meist lange Nachrichten ab, lässt Codeblöcke verschwinden und übernimmt die Benutzeroberfläche in die Datei. Kopierst du die Unterhaltung als Text, strukturierst sie so um, dass jeder Sprecherwechsel ein beschrifteter Abschnitt wird, und konvertierst sie anschließend in PDF oder DOCX, erhältst du ein Dokument, das tatsächlich lesbar und bearbeitbar ist.",
  sections: {
    "why-printing-fails": {
      heading: "Warum das Drucken der Chat-Seite scheitert",
      body: "<kbd>Strg</kbd>/<kbd>Cmd</kbd> + <kbd>P</kbd> im Chatfenster zu drücken liegt nahe, liefert aber aus strukturellen Gründen enttäuschende Ergebnisse.\n\nChat-Oberflächen sind als scrollende Anwendungsansichten gebaut, nicht als Dokumente. Das führt zu vorhersehbaren Druckproblemen:\n\n- **Lange Nachrichten werden abgeschnitten.** Einzelne Nachrichten liegen in eigenen Scroll-Containern, sodass der Druck nur den sichtbaren Bereich erfasst.\n- **Codeblöcke verlieren ihren Inhalt.** Horizontal scrollender Code wird am Containerrand abgeschnitten, sodass die rechte Seite jeder langen Zeile einfach verschwindet.\n- **Die Oberfläche wird mitgedruckt.** Seitenleisten, Avatare, Modellauswahl und Schaltflächen zum Neugenerieren erscheinen alle im Druck.\n- **Seitenumbrüche fallen ungünstig.** Nichts sagt dem Browser, wo ein sinnvoller Umbruch liegt, sodass Überschriften am Seitenende verwaist stehen.\n- **Es existieren nur geladene Nachrichten.** Lange Unterhaltungen werden virtualisiert, sodass frühere, noch nicht gerenderte Nachrichten im Druck komplett fehlen.\n\nDas Ergebnis ist eine Datei, die deine Unterhaltung technisch gesehen enthält, die du aber niemandem per E-Mail schicken würdest.",
    },
    "the-reliable-route": {
      heading: "Der zuverlässige Weg: kopieren, strukturieren, konvertieren",
      body: "Behandle die Unterhaltung als Text, nicht als Webseite.\n\n1. **Markiere die Unterhaltung und kopiere sie.** Ziehe die Auswahl von der ersten bis zur letzten Nachricht. Du erhältst den Text beider Seiten, meist mit intakter Markdown-Struktur.\n2. **Strukturiere sie als Dokument um.** Füge den Text in [ChatGPT-Unterhaltung als Dokument exportieren](/chatgpt-conversation-to-document) ein. Das Werkzeug erkennt Sprecherwechsel und baut sie als klare, beschriftete Abschnitte neu auf – statt als undifferenzierte Textwand.\n3. **Konvertiere in das gewünschte Format.** Für eine teilbare Datei liefert [Markdown in PDF umwandeln](/markdown-to-pdf) eine druckfertige Ansicht, die du direkt als PDF speichern kannst. Für etwas Bearbeitbares erzeugt [Markdown in Word umwandeln](/markdown-to-word) eine `.docx` mit echten Überschriftenformaten.\n\nDas Ergebnis ist ein Dokument mit Titel, überschriebenen Sprecherabschnitten, erhaltenen Codeblöcken und Tabellen sowie Seitenumbrüchen an sinnvollen Stellen.",
    },
    "labelling-speakers": {
      heading: "Die Sprecher-Beschriftungen richtig hinbekommen",
      body: "Der eine Punkt, der einen Moment Aufmerksamkeit verdient, ist, wie der kopierte Text unterscheidet, wer was gesagt hat.\n\nJe nach Oberfläche und Browser kommt eine kopierte Unterhaltung mit expliziten Beschriftungen an – oder ohne jede Trennung zwischen den Beiträgen. Wenn dein eingefügter Text keine Beschriftungen hat, füge sie vor dem Konvertieren hinzu: Eine Zeile mit nur `You:` oder `ChatGPT:` über jedem Beitrag genügt, damit der Konverter die Grenzen findet.\n\nEin Format, das zuverlässig funktioniert:\n\n```\nYou:\nSummarize the Q2 results.\n\nChatGPT:\nRevenue rose 12% year over year, driven by...\n```\n\nBei langen technischen Unterhaltungen lohnt es sich, explorative Sackgassen vor dem Konvertieren zu löschen. Ein Protokoll von vierzig Austauschen, von denen sechs relevant waren, ist nicht nützlicher, nur weil es vollständig ist – es ist weniger nützlich, weil der Leser die sechs erst finden muss. Exportiere die Unterhaltung, die du selbst lesen wollen würdest.",
    },
    "practical-notes": {
      heading: "Praktische Hinweise zur fertigen Datei",
      body: "**PDF-Seiteneinrichtung.** Beim Speichern aus dem Druckdialog solltest du Hintergrundgrafiken aktivieren, wenn Codeblöcke ihre Schattierung behalten sollen, und prüfen, ob die Ränder breite Tabellen abschneiden. Querformat ist bei einer Unterhaltung voller Daten oft die richtige Wahl.\n\n**Word-Dokumente und Überschriften.** Da der Konverter echte Überschriftenformate statt Fettdruck erzeugt, funktioniert der Navigationsbereich in Word, und du kannst ein automatisches Inhaltsverzeichnis einfügen. Das ist der wichtigste praktische Vorteil gegenüber jedem Copy-and-paste-Ansatz.\n\n**Langer Code.** Code, der im Chatfenster horizontal gescrollt hat, wird im Dokument umbrochen. Wenn exakte Zeilenumbrüche wichtig sind – etwa bei einer Konfigurationsdatei oder einem Shell-Befehl –, prüfe diese Blöcke nach dem Konvertieren.\n\n**Privatsphäre.** Beide Konverter laufen vollständig in deinem Browser; nichts wird hochgeladen. Das ist hier wichtiger als sonst, da Unterhaltungen oft Arbeitskontext, Kundendaten oder unveröffentlichtes Material enthalten. Wenn du zögern würdest, den Text in eine unbekannte Website einzufügen, ist die lokale Verarbeitung der Grund, warum dieser Ansatz sicher ist.\n\n**Ein Hinweis zu offiziellen Exporten.** ChatGPT bietet in den Einstellungen einen Datenexport an, der dir ein ZIP-Archiv mit deinem Unterhaltungsverlauf per E-Mail schickt. Das ist gründlich und fürs Archivieren nützlich, aber als Rohdaten strukturiert und nicht als lesbares Dokument – zum Teilen einer einzelnen Unterhaltung musst du also trotzdem konvertieren.",
    },
  },
  faqs: [
    { question: "Wie speichere ich eine ChatGPT-Unterhaltung als PDF?", answer: "Kopiere die Unterhaltung, strukturiere sie mit ChatGPT-Unterhaltung als Dokument exportieren so um, dass jeder Sprecherwechsel ein beschrifteter Abschnitt wird, und nutze dann Markdown in PDF umwandeln und speichere aus dem Druckdialog. So vermeidest du abgeschnittene Nachrichten und fehlende Codeblöcke, die beim Drucken der Chat-Seite entstehen." },
    { question: "Warum schneidet der Druck der ChatGPT-Seite meine Nachrichten ab?", answer: "Nachrichten liegen in eigenen Scroll-Containern, und lange Unterhaltungen werden virtualisiert. Der Druck erfasst daher nur, was gerade gerendert und sichtbar ist. Horizontal scrollende Codeblöcke werden aus demselben Grund am Containerrand abgeschnitten." },
    { question: "Kann ich eine ChatGPT-Unterhaltung nach Word exportieren?", answer: "Ja. Wandle die kopierte Unterhaltung mit Markdown in Word umwandeln in eine .docx um. Da dabei echte Überschriftenformate statt Fettdruck entstehen, funktioniert der Navigationsbereich, und du kannst ein automatisches Inhaltsverzeichnis erzeugen." },
    { question: "Hat ChatGPT einen eingebauten Export?", answer: "In den Einstellungen gibt es einen Datenexport, der dir ein Archiv deines Unterhaltungsverlaufs per E-Mail schickt. Das eignet sich gut als Backup, ist aber als Rohdaten strukturiert und nicht als lesbares Dokument – zum Teilen einer einzelnen Unterhaltung bleibt das Konvertieren der praktische Weg." },
    { question: "Ist es sicher, eine private Unterhaltung in einen Konverter einzufügen?", answer: "Das hängt vollständig vom Werkzeug ab. Unsere verarbeiten Text in deinem Browser und laden nichts hoch, weshalb die Unterhaltung auf deinem Gerät bleibt. Jedes Werkzeug, das Text an einen Server sendet, solltest du als Veröffentlichung behandeln – was bei Arbeits- oder Kundenmaterial entscheidend ist." },
  ],
};
