import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Unsichtbare Unicode-Zeichen: Referenz",
  description: "Referenz zu Nullbreitenzeichen, weichen Trennzeichen, BOMs und Richtungsmarken – was jedes tut, woher es kommt und wie man es entfernt.",
  h1: "Unsichtbare Unicode-Zeichen: was sie sind und was sie kaputt machen",
  dek: "Eine praktische Referenz zu den Zeichen, die in deinem Text stecken, aber nicht auf deinem Bildschirm.",
  answer: "Unsichtbare Unicode-Zeichen belegen keinen sichtbaren Platz, sind aber trotzdem Teil des Strings. Die häufigsten sind Nullbreitenzeichen, weiche Trennzeichen, Byte-Order-Marks, geschützte Leerzeichen und Richtungsmarken. Jedes hat einen legitimen typografischen Zweck – und jedes zerstört Suche, Validierung, Parsing und Deduplizierung, wenn es ein Copy-and-paste überlebt.",
  sections: {
    "the-reference": {
      heading: "Die Zeichen, denen du tatsächlich begegnest",
      body: "| Zeichen | Codepunkt | Zweck | Was es kaputt macht |\n| --- | --- | --- | --- |\n| Nullbreiten-Leerzeichen | U+200B | Schlägt einen Umbruchpunkt vor | Suche, String-Vergleich |\n| Zero Width Non-Joiner | U+200C | Verhindert das Verbinden von Buchstaben | Ligaturen, arabische und indische Schriften |\n| Zero Width Joiner | U+200D | Erzwingt das Verbinden von Zeichen | Emoji-Sequenzen, Textlänge |\n| Weiches Trennzeichen | U+00AD | Bindestrich nur beim Umbruch sichtbar | Suche, kopierter Text |\n| Geschütztes Leerzeichen | U+00A0 | Leerzeichen, das nie umbricht | Trimmen, CSV-Parsing, Code |\n| Schmales geschütztes Leerzeichen | U+202F | Schmales Leerzeichen vor Satzzeichen | Wie oben |\n| Byte-Order-Mark | U+FEFF | Markiert die Kodierung am Dateianfang | Erste CSV-Spalte, JSON-Parsing |\n| Word Joiner | U+2060 | Verhindert Umbruch, ohne Breite | Suche |\n| Links-nach-rechts-Marke | U+200E | Setzt die Textrichtung | Anzeigereihenfolge, Trimmen |\n| Rechts-nach-links-Marke | U+200F | Setzt die Textrichtung | Anzeigereihenfolge |\n| RTL-Override | U+202E | Erzwingt Rechts-nach-links-Anzeige | Dateinamen-Spoofing |\n| Zeilentrennzeichen | U+2028 | Unicode-Zeilenumbruch | JavaScript-String-Literale |\n| Absatztrennzeichen | U+2029 | Unicode-Absatzumbruch | JSON in älteren Parsern |\n\nJedes dieser Zeichen hat eine echte Aufgabe. Das Problem ist nie ihre Existenz – sondern dass sie lautlos zwischen Systemen reisen, die sie unterschiedlich behandeln.",
    },
    "where-they-come-from": {
      heading: "Woher sie kommen",
      body: "- **Kopieren von Webseiten.** Seiten fügen Nullbreiten-Leerzeichen ein, um zu steuern, wo lange Strings umbrechen, und weiche Trennzeichen für Blocksatz. Beides wird mitkopiert.\n- **Textverarbeitung.** Geschützte Leerzeichen werden automatisch eingefügt, damit eine Zahl bei ihrer Einheit bleibt oder ein Name in einer Zeile.\n- **PDF-Extraktion.** Beim Kopieren aus einem PDF entstehen häufig weiche Trennzeichen, wo der Satz Wörter über Zeilen getrennt hat, plus geschützte Leerzeichen aus dem Blocksatz.\n- **KI-Chat-Oberflächen.** Die Ausgabe wird als HTML gerendert, sodass das Kopieren alle verwendeten Abstandszeichen mitnimmt – meist U+00A0 und U+202F.\n- **Kodierungsumwandlungen.** Eine Byte-Order-Mark entsteht, wenn eine Datei als UTF-8 mit BOM gespeichert wird – unter Windows üblich.\n- **Absichtliches Einfügen.** Nullbreitenzeichen wurden genutzt, um Dokumente für die Leak-Verfolgung zu markieren und Text an Keyword-Filtern vorbeizuschmuggeln.\n\nDas Muster ist konsistent: Sie schleichen sich ein, wenn Text aus einem *Darstellungs*-Kontext in einen *Daten*-Kontext wechselt.",
    },
    "how-they-break-things": {
      heading: "Wie sie Dinge kaputt machen",
      body: "**Die Suche schlägt lautlos fehl.** Ein Nullbreiten-Leerzeichen in einem Wort bedeutet: Die Suche danach liefert nichts. Nichts erklärt warum – das Wort ist sichtbar genau da.\n\n**Die Validierung lehnt korrekte Eingaben ab.** Eine E-Mail-Adresse mit einem nachgestellten geschützten Leerzeichen scheitert an der Formatprüfung. Der Nutzer sieht eine korrekte Adresse und eine Fehlermeldung, die keinen Sinn ergibt.\n\n**Vergleiche schlagen fehl.** `\"Ada\" === \"Ada\\u200B\"` ist false. Deduplizierung übersieht offensichtliche Dubletten, Lookups liefern nichts, Joins verlieren Zeilen.\n\n**Trimmen hilft nicht.** Die meisten `trim()`-Implementierungen entfernen nur ASCII-Leerraum. Ein geschütztes Leerzeichen überlebt `.trim()` in vielen Sprachen – darum ist „Ich habe es doch schon getrimmt“ eine so häufige Sackgasse.\n\n**Code kompiliert nicht – in manchen Sprachen.** Ein geschütztes Leerzeichen, wo ein normales Leerzeichen hingehört, ist in Python, Go, Ruby, Shell und JSON ein Syntaxfehler, in einer Zeile, die perfekt aussieht. JavaScript, TypeScript und C behandeln U+00A0 als gewöhnlichen Leerraum und kompilieren es anstandslos, sodass es im Quelltext bleibt, bis etwas Strengeres die Datei liest.\n\n**CSV-Importe werden korrupt.** Eine Byte-Order-Mark hängt am ersten Header, sodass aus `id` ein `\\uFEFFid` wird und die erste Spalte lautlos nicht zugeordnet werden kann.\n\n**Die Länge stimmt nicht.** Zero Width Joiner in Emoji-Sequenzen bedeuten: Ein einziges sichtbares Emoji kann aus mehreren Codepunkten bestehen, sodass Zeichenlimits Eingaben ablehnen, die scheinbar locker darunter liegen.\n\n**Dateinamen können täuschen.** U+202E kehrt den angezeigten Text um, sodass `report\\u202Egnp.exe` als `reportexe.png` erscheinen kann. Das ist ein echtes Sicherheitsproblem, keine Kuriosität.",
    },
    "finding-and-removing": {
      heading: "Finden und entfernen",
      body: "**Zuerst scannen.** Füge den Text in den [Scanner für unsichtbare Zeichen](/remove-invisible-characters) ein. Er meldet die Gesamtzahl der gefundenen Zeichen sowie getrennte Zählungen für Nullbreitenzeichen und weiche Trennstriche, und entfernt sie auf Wunsch. Um zu sehen, welches Zeichen wo sitzt, nutze [Unsichtbare Zeichen anzeigen](/show-invisible-characters) – dort wird jedes einzelne an Ort und Stelle gekennzeichnet. Die Zählung vorab zeigt dir, ob du es mit einem einzelnen streunenden Zeichen oder einer systematischen Kontamination zu tun hast.\n\n**Im Editor.** VS Code hebt die meisten unsichtbaren Zeichen standardmäßig über die Einstellung unicode-highlight hervor. Für regexfähiges Suchen und Ersetzen fängt dieses Muster den gängigen Satz ab:\n\n```\n[\\u200B-\\u200F\\u00AD\\uFEFF\\u2060\\u202A-\\u202E\\u2028\\u2029]\n```\n\n**Im Code** normalisierst du an der Grenze – wenn Daten ankommen, nicht wenn sie verwendet werden:\n\n```js\nconst clean = input\n  .replace(/[\\u200B-\\u200F\\u2060\\uFEFF\\u00AD\\u202A-\\u202E]/g, \"\")\n  .replace(/[\\u00A0\\u202F]/g, \" \")\n  .normalize(\"NFC\")\n  .trim();\n```\n\nBeachte die zweistufige Behandlung: Nullbreitenzeichen werden *gelöscht*, geschützte Leerzeichen aber *in normale Leerzeichen umgewandelt* – löschen würde Wörter zusammenziehen.\n\n**Nicht blind entfernen.** Zero Width Joiner sind tragend in Emoji-Sequenzen und in Arabisch, Persisch und vielen indischen Schriften, wo ihr Entfernen die Darstellung von Wörtern verändert. Entferne aggressiv in Bezeichnern, Schlüsseln und Code; entferne zurückhaltend in nutzersichtbarem Inhalt.\n\nZur speziellen Frage, ob KI-Werkzeuge diese Zeichen absichtlich einfügen, siehe [Versteckt ChatGPT unsichtbare Zeichen?](/guides/chatgpt-invisible-characters). Das sichtbare, aber ebenso störende Gegenstück behandelt [Warum typografische Anführungszeichen Code kaputt machen](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "Was ist ein Nullbreiten-Leerzeichen?", answer: "U+200B, ein Zeichen ohne sichtbare Breite, das trotzdem Teil des Strings ist. Webseiten nutzen es, um vorzuschlagen, wo ein langes Wort umbrechen darf. Es zerstört Suche und String-Vergleiche, weil der Text identisch aussieht, die zugrunde liegenden Bytes aber abweichen." },
    { question: "Warum schlägt meine Suche bei Text fehl, der eindeutig da ist?", answer: "Fast sicher steckt ein unsichtbares Zeichen im Wort – meist ein Nullbreiten-Leerzeichen oder ein weiches Trennzeichen aus einer Webseite oder PDF. Der gerenderte Text entspricht deiner Eingabe, der zugrunde liegende String aber nicht." },
    { question: "Entfernt trim() geschützte Leerzeichen?", answer: "Meist nicht. Die meisten Trim-Implementierungen entfernen nur ASCII-Leerraum, sodass ein geschütztes Leerzeichen (U+00A0) überlebt. Darum scheitern Eingaben, die scheinbar kein führendes oder nachgestelltes Leerzeichen haben, nach dem Trimmen weiter an der Validierung." },
    { question: "Wie entferne ich unsichtbare Zeichen aus Text?", answer: "Füge den Text in einen Scanner ein, der sie auflistet und entfernt, oder nutze einen Regex über U+200B–U+200F, U+00AD, U+FEFF, U+2060 und U+202A–U+202E. Lösche Nullbreitenzeichen, wandle geschützte Leerzeichen aber in normale Leerzeichen um, statt sie zu löschen – sonst laufen Wörter zusammen." },
    { question: "Sind unsichtbare Zeichen jemals nützlich?", answer: "Ja. Weiche Trennzeichen steuern Worttrennungen im Blocksatz, geschützte Leerzeichen halten Werte bei ihren Einheiten, und Zero Width Joiner sind essenziell für Emoji-Sequenzen sowie für Arabisch, Persisch und indische Schriften. Entferne aggressiv in Code und Bezeichnern, zurückhaltend in Fließtext." },
  ],
};
