import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Warum eingefügter KI-Text in Word ** und ## anzeigt",
  description: "Diese Sternchen und Rauten sind Markdown. Warum Word sie wörtlich anzeigt und drei Wege, KI-Text mit intakter Formatierung einzufügen.",
  h1: "Warum zeigt eingefügter KI-Text ** und ## in Word?",
  dek: "Die Zeichen sind echte Formatierungsanweisungen – Word weiß nur nicht, wie es sie lesen soll.",
  answer: "Diese Zeichen sind Markdown, eine Formatierungssprache in reinem Text, in der Chat-Modelle schreiben. Sternchen markieren Fettdruck, Rauten Überschriften und senkrechte Striche Tabellen. Word hat keinen Markdown-Parser und behandelt sie daher als gewöhnliche Zeichen, die es wörtlich ausgibt. Wandelt man den Text vor dem Einfügen um, werden daraus echte Formatierungen.",
  sections: {
    "what-the-symbols-are": {
      heading: "Was die Zeichen tatsächlich bedeuten",
      body: "Markdown ist eine Konvention, um Formatierung ausschließlich mit tippbaren Zeichen zu beschreiben. Es wurde so entworfen, dass ein Dokument auch dann sinnvoll lesbar bleibt, wenn nichts es rendert. Chat-Modelle schreiben darin, weil es kompakt und eindeutig ist und in der Chat-Oberfläche korrekt dargestellt wird.\n\nHier das gesamte Vokabular, dem du wahrscheinlich begegnest:\n\n| Du siehst | Es bedeutet |\n| --- | --- |\n| `**bold**` | Fetter Text |\n| `*italic*` oder `_italic_` | Kursiver Text |\n| `# Heading` | Überschrift Ebene 1 (mehr Rauten, kleinere Überschrift) |\n| `- item` oder `* item` | Aufzählungspunkt |\n| `1. item` | Nummerierter Listeneintrag |\n| Backticks um `code` | Inline-Code |\n| `> quote` | Blockzitat |\n| `[text](url)` | Hyperlink |\n| `\\| a \\| b \\|` | Tabellenzeile |\n\nNichts ist kaputt und nichts wurde unterwegs beschädigt. Du siehst korrekt geformte Anweisungen, die an einem Ort ohne Interpreter gelandet sind.",
    },
    "why-word-cannot-read-it": {
      heading: "Warum Word es nicht lesen kann",
      body: "Word speichert Formatierung als strukturierte Daten im Dokument. Fettdruck ist ein Attribut, das an eine Zeichenfolge angehängt ist – kein Paar Sternchen drumherum. Wenn du reinen Text einfügst, nimmt Word jedes Zeichen wörtlich, denn aus seiner Sicht ist ein Sternchen ein Satzzeichen, das jemand absichtlich getippt hat.\n\nDeshalb enttäuschen die üblichen Behelfe:\n\n- **Inhalte einfügen → Formatierten Text** bewirkt nichts, weil in der Zwischenablage keine Formatierung vorlag, die man erhalten könnte. Sie enthielt nur reine Zeichen.\n- **Suchen und Ersetzen** entfernt die Sternchen, lässt den Text aber nicht fett – du verlierst die Struktur also vollständig, statt sie zu gewinnen.\n- **AutoFormat** beherrscht ein paar Muster wie Aufzählungszeichen, ist aber kein Markdown-Parser und rührt `**bold**` oder `## Heading` nicht an.\n\nGoogle Docs verhält sich aus demselben Grund genauso. Notion, Obsidian und die meisten Entwickler-Editoren *können* Markdown dagegen verarbeiten – deshalb klappt derselbe Kopiervorgang dort und erweckt den Eindruck, Word mache etwas falsch.",
    },
    "three-ways-to-fix": {
      heading: "Drei Wege zu korrekt formatiertem Text",
      body: "Welcher der richtige ist, hängt davon ab, ob du die Formatierung brauchst oder sie einfach loswerden willst.\n\n**1. In ein Word-Dokument umwandeln.** Die vollständigste Option. [Markdown in Word umwandeln](/markdown-to-word) verwandelt die Antwort in ein echtes `.docx` mit echten Überschriftenformaten, fetten Textabschnitten, Listen und Tabellen – der Art, die Words Navigationsbereich und Inhaltsverzeichnis tatsächlich erkennen. Nutze dies, wenn aus dem Ergebnis ein Bericht oder etwas werden soll, das andere bearbeiten.\n\n**2. In Rich Text umwandeln und einfügen.** [Markdown in Google Docs umwandeln](/markdown-to-google-docs) erzeugt formatierten Rich Text, den du direkt in Google Docs, Word, Outlook oder jeden Editor kopieren kannst, der eingefügtes HTML akzeptiert. Nutze dies, wenn du einen Abschnitt in ein bereits bestehendes Dokument einfügst.\n\n**3. Die Zeichen komplett entfernen.** Manchmal willst du sauberen Fließtext ganz ohne Formatierung – für eine E-Mail, ein Formularfeld, ein CMS-Feld oder eine Chat-Nachricht. [Markdown-Formatierung entfernen](/remove-markdown-formatting) löscht die Syntaxzeichen und lässt jedes Wort intakt – genau das, was Suchen und Ersetzen nicht sicher leistet.\n\nAlle drei Werkzeuge laufen in deinem Browser. Nichts wird hochgeladen.",
    },
    "stopping-it-at-the-source": {
      heading: "Das Problem an der Quelle abstellen",
      body: "Du kannst das Modell auch bitten, von vornherein kein Markdown zu verwenden. Ein Prompt wie *\"antworte in reinem Fließtext ohne Markdown-Formatierung, ohne Sternchen, ohne Rauten und ohne Aufzählungslisten\"* funktioniert bei kurzen Antworten recht gut.\n\nZuverlässiger ist das allerdings nicht. Die Befolgung lässt bei langen Antworten nach, und strukturierte Inhalte – alles mit Schritten, Vergleichen oder Daten – drängen das Modell zurück zu Listen und Tabellen, weil das schlicht die klarste Darstellung ist. Wenn deine Antwort eine Tabelle enthält, willst du diese Tabelle fast sicher – nur eben als echte Tabelle.\n\nBei allem Langen oder Strukturierten ist das nachträgliche Umwandeln die verlässlichere Gewohnheit. Du behältst außerdem die lesbare Version im Chatfenster und erhältst eine korrekt formatierte in deinem Dokument.\n\nWenn es konkret um eine Tabelle statt Fließtext geht, gelten eigene Eigenheiten – siehe [ChatGPT-Tabelle in Excel einfügen](/guides/paste-chatgpt-table-into-excel).",
    },
  },
  faqs: [
    { question: "Warum zeigt ChatGPT-Text Sternchen an, wenn ich ihn in Word einfüge?", answer: "Die Sternchen sind Markdown-Syntax für fetten und kursiven Text. Word hat keinen Markdown-Parser und behandelt sie daher als gewöhnliche Zeichen, die wörtlich angezeigt werden. Wandelt man das Markdown vorher in ein Word-Dokument oder in Rich Text um, werden daraus echte Formatierungen." },
    { question: "Wie füge ich ChatGPT-Ausgaben mit Formatierung in Word ein?", answer: "Wandle sie zuerst um. Markdown in Word umwandeln erzeugt ein .docx mit echten Überschriftenformaten, fetten Textabschnitten, Listen und Tabellen; Markdown in Google Docs umwandeln erzeugt Rich Text, den du direkt in ein bestehendes Dokument einfügen kannst. Beim Einfügen der rohen Antwort erscheinen immer die Syntaxzeichen." },
    { question: "Behebt Inhalte einfügen die Markdown-Zeichen?", answer: "Nein. Inhalte einfügen bewahrt Formatierung, die bereits in der Zwischenablage vorliegt – und reines Text-Markdown hat keine, denn die Formatierung steckt als Zeichen im Text, nicht als Attribute. Es gibt schlicht nichts, das Inhalte einfügen bewahren könnte." },
    { question: "Was bedeutet ## in KI-generiertem Text?", answer: "Es markiert eine Überschrift. Eine Raute steht für eine Überschrift oberster Ebene, zwei für die zweite Ebene und so weiter bis sechs. In einem Editor mit Markdown-Unterstützung verschwinden die Rauten und die Zeile wird als formatierte Überschrift dargestellt." },
    { question: "Kann ich die Sternchen nicht einfach suchen und ersetzen?", answer: "Kannst du, aber du löschst damit die Formatierung, statt sie anzuwenden – der Text ist dann nicht mehr fett und verliert nur die Markierungen. Sicheres Entfernen von Markdown umfasst außerdem Überschriften, Listenzeichen, Links und Codeblöcke, was ein spezialisiertes Werkzeug in einem Durchgang erledigt." },
  ],
};
