import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "ChatGPT-Tabelle in Excel einfügen: So geht's",
  description: "KI-Tabellen landen in einer Spalte, weil sie reiner Text sind. So erhältst du echte Zeilen und Spalten in Excel, Sheets oder Numbers.",
  h1: "Eine ChatGPT-Tabelle in Excel oder Google Sheets einfügen",
  dek: "Warum die ganze Tabelle in Spalte A landet – und die zwei zuverlässigen Lösungen.",
  answer: "Eine ChatGPT-Tabelle ist eine Markdown-Pipe-Tabelle – reiner Text, der mit |-Zeichen Spalten andeutet. Tabellenkalkulationen erwarten echte Zellgrenzen statt Pipes, deshalb landet jede Zeile in einer einzigen Spalte. Wenn du die Tabelle vorher in XLSX oder CSV umwandelst, entstehen echte Zeilen und Spalten, die sich in Excel, Sheets und Numbers korrekt öffnen lassen.",
  sections: {
    "why-it-lands-in-one-column": {
      heading: "Warum die ganze Tabelle in Spalte A landet",
      body: "Was das Chatfenster dir zeigt, ist eine gerenderte Tabelle. Was in deiner Zwischenablage landet, ist meist Folgendes:\n\n```\n| Region | Q1 | Q2 |\n| --- | ---: | ---: |\n| Europe | 412 | 486 |\n| Asia | 377 | 381 |\n```\n\nDas ist eine Markdown-Pipe-Tabelle. Die senkrechten Striche sind gewöhnliche Zeichen, die für ein menschliches Auge nur *wie* Spaltentrenner aussehen. Die zweite Zeile mit ihren Bindestrichen und Doppelpunkten sagt einem Markdown-Renderer, wo die Kopfzeile endet und wie jede Spalte ausgerichtet wird.\n\nExcel zerlegt eingefügten Text an Tabulatorzeichen, nicht an Pipes. Da es keine Tabulatoren gibt, ist jede Zeile ein einzelner Wert, und die gesamte Tabelle stapelt sich in Spalte A – die Pipes bleiben sichtbar. Google Sheets und Numbers verhalten sich genauso.\n\nDie Ausrichtungszeile ist das verräterische Zeichen dafür, dass es sich nie um Tabellendaten gehandelt hat. Kein Tabellenexport enthält eine Zeile aus Bindestrichen und Doppelpunkten.",
    },
    "the-fastest-fix": {
      heading: "Die schnellste Lösung: vor dem Einfügen umwandeln",
      body: "Statt einzufügen und nachzubessern, wandelst du die Tabelle in ein Format um, das Tabellenkalkulationen bereits verstehen.\n\n**Für Excel und Numbers** erzeugt [Markdown-Tabelle in Excel umwandeln](/markdown-table-to-excel) eine echte `.xlsx`-Datei. Tabelle einfügen, Datei herunterladen, öffnen. Zahlen bleiben Zahlen, die Kopfzeile bleibt eine Kopfzeile, und danach muss nichts mehr aufgeteilt werden.\n\n**Für Google Sheets** ist [Markdown-Tabelle in CSV umwandeln](/markdown-table-to-csv) meist der glattere Weg. CSV lässt sich direkt über *Datei → Importieren* einlesen, und du sparst dir den Umweg über Herunterladen und Hochladen, den XLSX im Browser erfordert. Der Konverter maskiert Anführungszeichen und eingebettete Kommas korrekt – genau daran scheitern selbstgebaute Lösungen typischerweise.\n\nBeide Werkzeuge laufen lokal in deinem Browser, die Daten verlassen dein Gerät also nicht – erwähnenswert, falls die Tabelle Inhalte enthält, die du nicht auf irgendeine beliebige Website einfügen würdest.",
    },
    "manual-methods": {
      heading: "Die manuellen Methoden – und wann sie sich lohnen",
      body: "Wenn du die Tabellenkalkulation lieber nicht verlassen willst, funktionieren zwei eingebaute Wege.\n\n**Text in Spalten (Excel).** Füge die Rohtabelle in Spalte A ein, markiere sie, dann *Daten → Text in Spalten → Getrennt* und setze das Trennzeichen auf die Pipe. Danach musst du noch die Ausrichtungszeile löschen und die leeren Spalten entfernen, die durch die Pipes am Zeilenanfang und -ende entstehen.\n\n**SPLIT (Google Sheets).** Mit der Rohtabelle in Spalte A verwendest du `=SPLIT(A1; \"|\")`, ziehst die Formel nach unten und fügst das Ergebnis als Werte ein. Die gleiche Nacharbeit gilt auch hier.\n\nFür eine einzelne kleine Tabelle ist das in Ordnung. Es wird schnell mühsam, und beide Methoden lassen Leerzeichen-Polster in jeder Zelle zurück – die Leerzeichen, die Markdown der Lesbarkeit halber einfügt, werden Teil des Werts, sodass ` Europe ` in einer Verweisformel nicht zu `Europe` passt. Dieses Problem mit den Leerzeichen am Ende ist der häufigste Grund, warum eine umgewandelte Tabelle richtig aussieht, sich aber falsch verhält.\n\n**Ein Hinweis zum Kopieren:** Wenn du die *gerenderte* Tabelle im Chatfenster per Maus markierst statt die Kopieren-Schaltfläche zu nutzen, legen manche Browser tabulatorgetrennten Text in die Zwischenablage, der sich korrekt in Spalten einfügt. Das ist je nach Browser und Chat-Oberfläche uneinheitlich – einen Versuch wert, aber nicht verlässlich.",
    },
    "google-sheets": {
      heading: "Die Tabelle in Google Sheets bekommen",
      body: "Sheets scheitert auf die gleiche Weise wie Excel – Pipes sind kein Trennzeichen, das es erkennt, also landet jede Zeile in einer einzigen Zelle von Spalte A –, aber die Auswege daraus unterscheiden sich leicht, und einer davon ist wirklich praktisch.\n\n**Text in Spalten aufteilen.** Füge die Rohtabelle in eine Spalte ein, lasse den eingefügten Bereich markiert und verwende *Daten → Text in Spalten aufteilen*. Sheets bietet eine Auswahl an Trennzeichen an, darunter ein benutzerdefiniertes, sodass du es auf das Pipe-Zeichen setzen kannst. Direkt nach jedem Einfügen von getrenntem Text zeigt es zudem ein kleines Steuerelement neben den eingefügten Daten, das dasselbe ohne den Umweg über das Menü erledigt. Wie bei Excels Text in Spalten bleiben dir danach die Ausrichtungszeile zum Löschen, leere Spalten an beiden Rändern durch die führenden und abschließenden Pipes sowie ein Leerzeichen-Polster in jedem Wert.\n\n**Stattdessen eine CSV-Datei importieren.** *Datei → Importieren* liest eine Datei ein statt eines Einfügevorgangs und lässt dich festlegen, welches Trennzeichen gilt und ob Text in Zahlen und Datumswerte umgewandelt werden soll. Das ist der entscheidende Unterschied: Ein Import legt die Spaltentypen bewusst fest, während ein Einfügevorgang rät. Führe die Tabelle vorher durch [Markdown-Tabelle in CSV umwandeln](/markdown-table-to-csv), und es bleibt nichts mehr zu raten – die Ausrichtungszeile ist weg, das Polster ist entfernt, und Kommas innerhalb von Zellen sind korrekt in Anführungszeichen gesetzt.\n\n**Sheets als Zwischenstation.** Sobald eine Tabelle in echten Zellen steht, nimmt das Kopieren dieses Bereichs das Raster mit. Das Einfügen aus Sheets in Excel, Word, Slides, Docs oder eine E-Mail erhält Zeilen und Spalten, weil die Zwischenablage jetzt tabellarische Daten enthält statt einer Textzeile mit Strichen darin. Muss eine Tabelle eine App ohne eigenen Import erreichen, ist der Umweg über eine Tabellenkalkulation zuverlässiger, als mit dem Ziel zu kämpfen.\n\nEine Google-Sheets-spezifische Falle: Werte wie `3-4` oder `1/2` werden in einer umgewandelten Zelle als Datum gelesen. Landet eine Spalte voller Datumswerte, die du nicht wolltest, mach die Aktion rückgängig, formatiere die Zielspalte als Klartext und füge erneut ein.",
    },
    "tables-buried-in-prose": {
      heading: "Wenn die Tabelle in einer längeren Antwort versteckt ist",
      body: "Oft ist die gewünschte Tabelle nur ein Teil einer viel längeren Antwort, eingebettet in Erklärungen davor und danach.\n\n[Tabellen aus Text extrahieren](/extract-table-from-text) findet tabellenähnliche Zeilen inmitten von Fließtext – mit Pipe- oder Tabulator-Trennung – und gibt nur die Tabelle als CSV zurück. Füge die komplette Antwort ein und hole dir die Daten heraus, statt Zeilen von Hand zu markieren und zu hoffen, dass du die Grenzen erwischt hast.\n\nZwei Dinge solltest du bei jeder umgewandelten Tabelle prüfen, bevor du darauf aufbaust:\n\n- **Als Text gespeicherte Zahlen.** Wenn eine Spalte in Excel linksbündig ankommt, sind die Werte Text. Währungssymbole, Tausendertrennzeichen und Prozentzeichen im Original sind die üblichen Ursachen. Markiere die Spalte und nutze *Daten → Text in Spalten → Fertig stellen*, um sie umzuwandeln.\n- **Verbundene oder umbrochene Zellen.** Markdown-Tabellen können keine verbundenen Zellen ausdrücken, deshalb simuliert ein Modell bei komplexen Daten manchmal mit wiederholten Werten oder Zeilenumbrüchen innerhalb einer Zelle. Das erfordert eine menschliche Entscheidung, keinen Konverter.\n\nWenn auch der Rest der Antwort mitreisen soll – Überschriften, Listen, die Erklärungen rund um die Tabelle –, lies [warum eingefügter KI-Text ** und ## anzeigt](/guides/markdown-symbols-in-word).",
    },
  },
  faqs: [
    { question: "Warum landet eine ChatGPT-Tabelle in einer einzigen Excel-Spalte?", answer: "Weil es sich um eine Markdown-Pipe-Tabelle handelt – reinen Text, der |-Zeichen als optische Trenner nutzt. Excel zerlegt eingefügten Text an Tabulatoren, nicht an Pipes, sodass jede Zeile als ein Wert behandelt wird und die ganze Tabelle in einer Spalte stapelt." },
    { question: "Wie wandle ich eine Markdown-Tabelle in Excel um?", answer: "Füge sie in das Werkzeug Markdown-Tabelle in Excel umwandeln ein und lade die entstehende .xlsx-Datei herunter. Sie erzeugt echte Zeilen und Spalten mit erhaltener Kopfzeile, sodass nach dem Öffnen nichts mehr aufgeteilt oder bereinigt werden muss." },
    { question: "Was ist die Zeile aus Bindestrichen und Doppelpunkten in einer KI-Tabelle?", answer: "Das ist die Markdown-Ausrichtungszeile. Sie trennt die Kopfzeile vom Tabellenkörper und legt die Spaltenausrichtung fest – ein Doppelpunkt rechts bedeutet rechtsbündig, auf beiden Seiten zentriert. Sie ist Formatierungssyntax, keine Daten, und sollte bei der Umwandlung entfernt werden." },
    { question: "Warum haben meine umgewandelten Zellen zusätzliche Leerzeichen?", answer: "Markdown polstert Zellen der Lesbarkeit halber mit Leerzeichen, und das manuelle Aufteilen behält diese Polster im Wert. Das ist relevant, weil ' Europe ' in einem Verweis nicht zu 'Europe' passt. Ein guter Konverter entfernt die Polster; wenn du manuell aufteilst, umschließe die Ergebnisse mit GLÄTTEN." },
    { question: "Kann ich eine KI-Tabelle direkt in Google Sheets einfügen?", answer: "Nicht mit intakten Spalten. Die zuverlässigste Lösung ist die vorherige Umwandlung in CSV und der Import über Datei → Importieren, da CSV ein Format ist, das Sheets nativ verarbeitet, und der Umweg über XLSX-Download und -Upload entfällt." },
  ],
};
