import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Wie viele Tokens hat mein Prompt?",
  description: "Tokens sind Wortfragmente, keine Wörter. So funktioniert Tokenisierung, warum Zählungen je nach Modell abweichen und wie du Kosten schätzt.",
  h1: "Wie viele Tokens hat mein Prompt?",
  dek: "Warum 1.000 Wörter nie 1.000 Tokens sind – und was das für Kontextlimits und Kosten bedeutet.",
  answer: "Tokens sind Fragmente kleiner als Wörter, daher stimmen Token- und Wortzahlen nie überein. Bei normalem Englisch entspricht ein Token im Schnitt etwa vier bis fünf Zeichen – 1.000 Wörter liegen also irgendwo zwischen 1.050 und 1.350 Tokens, je nachdem, wie fachlich der Text ist. Code, nichtenglische Schriften und ungewöhnliche Wörter verbrauchen mehr Tokens pro Zeichen, teils um ein Mehrfaches.",
  sections: {
    "what-a-token-is": {
      heading: "Was ein Token wirklich ist",
      body: "Sprachmodelle lesen weder Zeichen noch Wörter. Sie lesen Tokens: Fragmente, die entstehen, wenn Text anhand eines festen, aus Trainingsdaten gelernten Vokabulars zerlegt wird.\n\nHäufige Wörter sind meist ein einziges Token. Seltene Wörter werden in Teile zerlegt. Leerzeichen hängen typischerweise am Anfang des folgenden Tokens – deshalb kann dasselbe Wort unterschiedlich zählen, je nachdem, ob es am Satzanfang steht.\n\nMit dem Tokenizer von GPT-4o gemessen ergibt das Wort *unbelievable* allein stehend drei Tokens: `un` + `bel` + `ievable`. So geschrieben, wie es tatsächlich im Satz vorkommt, also mit vorangestelltem Leerzeichen, ist es ein einziges Token: ` unbelievable`. Hier wirkt die Regel des führenden Leerzeichens – der Eintrag, den das Modell gelernt hat, ist die Form mit Leerzeichen davor, weil das Wort im laufenden Text fast immer so auftritt. *the* und *international* verhalten sich genauso: jeweils ein Token, das Leerzeichen inklusive.\n\nDeshalb wirken Token-Zählungen so unberechenbar. Die Einheit ist nicht sprachlich, sondern statistisch. Die Häufigkeit im Trainingskorpus entscheidet, ob etwas ein Token oder vier ist.",
    },
    "rules-of-thumb": {
      heading: "Faustregeln, die wirklich stimmen",
      body: "Für englischen Fließtext, gemessen mit dem Tokenizer von GPT-4o über Register hinweg – von umgangssprachlichen Texten bis zu technischen Nachschlagewerken:\n\n- **1 Token ≈ 4,3–5,9 Zeichen**\n- **1 Token ≈ 0,75–0,95 Wörter**\n- **1.000 Wörter ≈ 1.050–1.350 Tokens**\n- **Eine Standardseite (~500 Wörter) ≈ 530–680 Tokens**\n\nDas Register zählt mehr, als die meisten Faustregeln zugeben. Lockere, gesprochensprachliche Texte liegen am unteren Ende dieser Spanne, bei rund 1.060 Tokens pro tausend Wörter, weil sie immer wieder auf einen kleinen Wortschatz häufiger Wörter zurückgreifen, die jeweils in ein einziges Token passen. Dichte Fachprosa – auch die Guides dieser Website – liegt mit etwa 1.310 am oberen Ende, weil Fachbegriffe in Teile zerlegt werden. Der geläufige Einzelwert von 1.300 Tokens pro tausend Wörter markiert also das fachliche Ende der Spanne, nicht die Mitte, und überschätzt gewöhnliche Texte damit um rund ein Fünftel. Für die Planung eines Kontextfensters ist das die sichere Richtung, in die man sich irren kann.\n\nAußerhalb normalen Fließtexts fallen diese Werte schnell auseinander:\n\n| Inhaltstyp | Ungefähr |\n| --- | --- |\n| Englischer Fließtext | 0,75–0,95 Wörter pro Token, je nach Register |\n| Code | Rund 1,2× so viele Tokens pro Zeichen wie Fließtext, und etwa 1,5× für denselben Sachverhalt in beiden Formen ausgedrückt |\n| JSON mit langen Schlüsseln | Sehr hoch – Satzzeichen und Anführungszeichen sind eigene Tokens |\n| Chinesisch, Japanisch, Koreanisch | Etwa 0,6–0,7 Tokens *pro Zeichen* – also weniger als ein Token je Zeichen, aber ein Mehrfaches dessen, was Englisch für dieselbe Zeichenzahl braucht |\n| Kyrillisch, Devanagari, Arabisch | Etwa 1,4–1,6× so viel wie Englisch beim selben Text |\n| URLs und Hashes | Extrem hoch – Zufallszeichenfolgen lassen sich schlecht tokenisieren |\n| Wiederholte Leerzeichen | Günstig statt teuer – Byte-Pair-Kodierung fasst lange Folgen zusammen, vierzig aufeinanderfolgende Leerzeichen sind also ein Token |\n\nDie mehrsprachige Lücke ist real, aber deutlich kleiner, als es die verbreitete Erzählung nahelegt. Gemessen an den englischen Seiten dieser Website gegenüber ihren professionellen Übersetzungen kostet die japanische Fassung etwa 1,7× so viel wie die englische, die koreanische etwa 1,5×, die chinesische etwa 1,2×, die hindi-sprachige etwa 1,6× und die arabische etwa 1,4×. Unter dem älteren Tokenizer `cl100k_base` lagen dieselben Paare bei 2,3×, 2,3×, 1,7×, 4,7× und 2,9× – daher stammt die oft wiederholte Angabe „zwei- bis dreimal so viel wie Englisch“. Damals stimmte sie; die neueren Vokabulare haben die Lücke weitgehend geschlossen.",
    },
    "why-models-differ": {
      heading: "Warum die Zählung je nach Modell abweicht",
      body: "Jede Modellfamilie nutzt ihren eigenen Tokenizer mit eigenem Vokabular – derselbe Text ergibt also unterschiedliche Zählungen.\n\nGPT-Modelle verwenden Varianten der Byte-Pair-Kodierung – `cl100k_base` bei Modellen der GPT-4-Ära, `o200k_base` bei neueren. Claude nutzt einen anderen Tokenizer mit anderem Vokabular. Offene Modelle wie Llama und Mistral haben wiederum jeweils eigene.\n\nAm stärksten unterscheiden sich die Vokabulare bei Code und nichtenglischem Text – dort weichen folglich auch die Zählungen am weitesten voneinander ab.\n\nPraktisch heißt das:\n\n- Eine Zählung eines Tokenizers ist für jedes andere Modell eine **Schätzung**.\n- Nur der eigene Tokenizer des Anbieters liefert die exakte Zahl für dessen Abrechnung.\n- Plane mit Puffer statt exakt bis ans Limit.\n\nUnser [Token-Zähler](/token-counter) zeigt eine GPT-4o-Zählung und eine Claude-Schätzung nebeneinander. Die GPT-4o-Zahl ist eine echte Tokenizer-Zählung. Die Claude-Zahl ist es bewusst nicht: Anthropic veröffentlicht keinen Tokenizer, den wir in deinem Browser ausführen könnten, daher handelt es sich um eine zeichenbasierte Schätzung von einem Token je 3,5 Zeichen. Bei englischem Fließtext liegt diese Schätzung 22–50 % über der GPT-4o-Zählung – bei üblichen Texten etwa ein Drittel darüber. Lies den Abstand also als Breite einer Schätzung, nicht als gemessenen Unterschied zwischen den beiden Modellfamilien. Zusammen reichen die beiden Zahlen weiterhin, um zu erkennen, ob ein Prompt bequem innerhalb des Limits liegt oder unangenehm knapp daran; muss die Zahl exakt sein, nimm den Zähler des jeweiligen Anbieters.",
    },
    "why-it-matters": {
      heading: "Warum die Zahl wichtig ist",
      body: "**Kosten.** API-Preise gelten pro Token, Eingabe und Ausgabe werden getrennt abgerechnet, und die Ausgabe ist typischerweise um ein Mehrfaches teurer. Ein doppelt so langer System-Prompt verdoppelt diese Kosten bei jedem einzelnen Aufruf – so etwas fällt im Test nicht auf, wird aber bei Volumen teuer.\n\n**Kontextlimits.** Das Fenster umfasst *alles*: System-Prompt, Gesprächsverlauf, abgerufene Dokumente, die aktuelle Nachricht und den reservierten Platz für die Antwort. Lange Chats scheitern nicht, weil eine einzelne Nachricht lang ist, sondern weil sich der Verlauf ansammelt.\n\n**Abschneiden.** Wenn die Eingabe das Limit überschreitet, fällt etwas weg – oft stillschweigend, und oft der früheste Inhalt. Ein Modell, das deine Anweisungen „vergessen“ hat, hatte sie häufig schlicht herausgeschnitten.\n\n**Chunking für Retrieval.** Das Aufteilen von Dokumenten für Embeddings erfolgt in Tokens, nicht in Zeichen. Nach Zeichenzahl bemessene Abschnitte werden uneinheitlich, und Abschnitte, die mitten im Satz enden, liefern schlechte Treffer – eine Retrieval-Pipeline braucht also einen Splitter, der Satz- und Absatzstruktur berücksichtigt. Unser [Text-Splitter](/text-splitter) ist dieses Werkzeug nicht: Er schneidet Abschnitte fester Größe von bis zu 2.000 Zeichen und trennt dabei am nächstgelegenen Leerraum, sodass kein Wort in der Mitte zerteilt wird – ein Abschnitt kann dadurch aber mitten im Satz enden. Nutze ihn, um ein langes Dokument durch ein Kontextfenster oder ein Einfügelimit zu bekommen – nicht, um Embedding-Abschnitte für Retrieval zu erzeugen.",
    },
    "reducing-tokens": {
      heading: "Die Zahl senken, ohne Bedeutung zu verlieren",
      body: "Die wirksamsten Maßnahmen, ungefähr in dieser Reihenfolge:\n\n1. **Gesprächsverlauf kürzen.** In langen Chats überwiegt er alles andere. Fasse alte Runden zusammen, statt sie wortwörtlich erneut zu senden.\n2. **Redundante Anweisungen streichen.** Eine Regel dreifach zu formulieren macht es nicht dreimal wahrscheinlicher, dass sie befolgt wird. Es verdreifacht aber zuverlässig ihre Kosten.\n3. **Formatierungsartefakte entfernen.** Unsichtbare Zeichen, wiederholte Leerzeichen und dekorative Trennlinien werden alle tokenisiert. Einzeln betrachtet sind sie günstiger, als man denkt, denn die Byte-Pair-Kodierung fasst lange Folgen zusammen: Vierzig aufeinanderfolgende Leerzeichen sind ein Token und eine Trennlinie aus vierzig Bindestrichen zwei – gegenüber dreizehn für den Satz darüber. Reiner Ballast bleiben sie trotzdem, und in einem Dokument mit einer Trennlinie zwischen jedem Abschnitt summiert sich das. [Unsichtbare Zeichen entfernen](/remove-invisible-characters) beseitigt die, die du nicht sehen kannst.\n4. **JSON-Schlüssel kürzen** in strukturierten Prompts. `{\"n\": ...}` statt `{\"customer_full_name\": ...}` macht über tausend Datensätze hinweg einen großen Unterschied.\n5. **Nur relevante Auszüge senden.** Drei passende Absätze abzurufen schlägt das Einfügen des ganzen Dokuments – und liefert meist auch bessere, nicht nur günstigere Antworten.\n\nWas *nicht* hilft: gewöhnliche Satzzeichen entfernen, Artikel streichen oder in abgehacktem Telegrammstil schreiben. Die Einsparung ist marginal, der Schaden für die Ausgabequalität nicht.",
    },
  },
  faqs: [
    { question: "Wie viele Tokens sind 1.000 Wörter?", answer: "Zwischen etwa 1.050 und 1.350 Tokens, gemessen mit dem Tokenizer von GPT-4o. Gesprochensprachliche Texte landen bei rund 1.060, weil sie auf häufige Wörter zurückgreifen, die je ein einziges Token belegen; dichte Fachprosa landet bei etwa 1.310. Code und JSON liegen höher. Chinesisch, Japanisch und Koreanisch verbrauchen etwa 0,6 bis 0,7 Tokens pro Zeichen: weniger Tokens als Zeichen, aber ein Mehrfaches dessen, was Englisch für dieselbe Zeichenzahl braucht." },
    { question: "Warum unterscheidet sich die Token-Zahl bei GPT und Claude?", answer: "Jede Modellfamilie nutzt ihren eigenen Tokenizer mit einem anderen gelernten Vokabular, daher wird derselbe Text unterschiedlich zerlegt, und am größten ist der Unterschied bei Code und nichtenglischem Text. Beachte: Die Claude-Zahl in unserem Token-Zähler ist eine zeichenbasierte Schätzung von einem Token je 3,5 Zeichen und keine echte Tokenizer-Zählung – deshalb liegt sie bei englischem Fließtext rund ein Drittel über der GPT-4o-Zählung." },
    { question: "Was ist ein Token in einem KI-Modell?", answer: "Ein Textfragment aus dem festen Vokabular des Modells. Häufige Wörter sind meist ein einziges Token, seltene Wörter werden in mehrere Teile zerlegt – „unbelievable“ kann so drei Tokens werden, während „international“ nur eines ist." },
    { question: "Zählen Leerzeichen und Satzzeichen als Tokens?", answer: "Ja. Leerzeichen hängen normalerweise am Anfang des folgenden Tokens, und Satzzeichen sind häufig eigene Tokens. Lange Folgen sind die Ausnahme: Die Byte-Pair-Kodierung fasst sie zusammen, sodass vierzig aufeinanderfolgende Leerzeichen ein einziges Token sind und eine Trennlinie aus vierzig Bindestrichen zwei." },
    { question: "Wie kann ich meinen Token-Verbrauch senken?", answer: "Kürze zuerst den angesammelten Gesprächsverlauf – in langen Chats dominiert er alles andere. Entferne dann doppelte Anweisungen, unsichtbare Zeichen und wiederholte Leerzeichen, kürze JSON-Schlüssel und sende nur den relevanten Auszug eines Dokuments statt des Ganzen." },
  ],
};
