import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Wie viele Tokens hat mein Prompt?",
  description: "Tokens sind Wortfragmente, keine Wörter. So funktioniert Tokenisierung, warum Zählungen je nach Modell abweichen und wie du Kosten schätzt.",
  h1: "Wie viele Tokens hat mein Prompt?",
  dek: "Warum 1.000 Wörter nie 1.000 Tokens sind – und was das für Kontextlimits und Kosten bedeutet.",
  answer: "Tokens sind Fragmente kleiner als Wörter, daher stimmen Token- und Wortzahlen nie überein. Bei normalem Englisch entspricht ein Token im Schnitt etwa vier Zeichen oder drei Vierteln eines Wortes – 1.000 Wörter sind also grob 1.300 Tokens. Code, nichtenglische Schriften und ungewöhnliche Wörter verbrauchen mehr Tokens pro Zeichen, teils um ein Mehrfaches.",
  sections: {
    "what-a-token-is": {
      heading: "Was ein Token wirklich ist",
      body: "Sprachmodelle lesen weder Zeichen noch Wörter. Sie lesen Tokens: Fragmente, die entstehen, wenn Text anhand eines festen, aus Trainingsdaten gelernten Vokabulars zerlegt wird.\n\nHäufige Wörter sind meist ein einziges Token. Seltene Wörter werden in Teile zerlegt. Leerzeichen hängen typischerweise am Anfang des folgenden Tokens – deshalb kann dasselbe Wort unterschiedlich zählen, je nachdem, ob es am Satzanfang steht.\n\nDas Wort *unbelievable* ist kein einzelnes Token – es wird wahrscheinlich in etwas wie `Un` + `believ` + `able` aufgeteilt. *the* dagegen ist ein einziges Token, und *international* ebenfalls, weil es im Training oft genug vorkam, um einen eigenen Eintrag zu erhalten.\n\nDeshalb wirken Token-Zählungen so unberechenbar. Die Einheit ist nicht sprachlich, sondern statistisch. Die Häufigkeit im Trainingskorpus entscheidet, ob etwas ein Token oder vier ist.",
    },
    "rules-of-thumb": {
      heading: "Faustregeln, die wirklich stimmen",
      body: "Für englischen Fließtext:\n\n- **1 Token ≈ 4 Zeichen**\n- **1 Token ≈ 0,75 Wörter**\n- **1.000 Wörter ≈ 1.300 Tokens**\n- **Eine Standardseite (~500 Wörter) ≈ 650 Tokens**\n\nAußerhalb normalen Fließtexts fallen diese Werte schnell auseinander:\n\n| Inhaltstyp | Ungefähr |\n| --- | --- |\n| Englischer Fließtext | 0,75 Wörter pro Token |\n| Code | 2–3× mehr Tokens als vergleichbarer Fließtext |\n| JSON mit langen Schlüsseln | Sehr hoch – Satzzeichen und Anführungszeichen sind eigene Tokens |\n| Chinesisch, Japanisch, Koreanisch | Oft 1–2 Tokens *pro Zeichen* |\n| Kyrillisch, Devanagari, Arabisch | Typischerweise 2–3× so viel wie Englisch bei gleicher Bedeutung |\n| URLs und Hashes | Extrem hoch – Zufallszeichenfolgen lassen sich schlecht tokenisieren |\n| Wiederholte Leerzeichen | Jede Folge kann ein eigenes Token sein |\n\nDie mehrsprachige Lücke ist erheblich und wird oft unterschätzt: Derselbe Satz auf Japanisch kann ein Mehrfaches dessen kosten, was er auf Englisch kostet – mit Auswirkungen sowohl auf den Preis als auch darauf, wie viel ins Kontextfenster passt.",
    },
    "why-models-differ": {
      heading: "Warum die Zählung je nach Modell abweicht",
      body: "Jede Modellfamilie nutzt ihren eigenen Tokenizer mit eigenem Vokabular – derselbe Text ergibt also unterschiedliche Zählungen.\n\nGPT-Modelle verwenden Varianten der Byte-Pair-Kodierung – `cl100k_base` bei Modellen der GPT-4-Ära, `o200k_base` bei neueren. Claude nutzt einen anderen Tokenizer mit anderem Vokabular. Offene Modelle wie Llama und Mistral haben wiederum jeweils eigene.\n\nAbweichungen von 10–20 % zwischen den Familien sind bei englischem Text normal, und die Lücke wird bei Code und nichtenglischem Text größer, wo sich die Vokabulare am stärksten unterscheiden.\n\nPraktisch heißt das:\n\n- Eine Zählung eines Tokenizers ist für jedes andere Modell eine **Schätzung**.\n- Nur der eigene Tokenizer des Anbieters liefert die exakte Zahl für dessen Abrechnung.\n- Plane mit Puffer statt exakt bis ans Limit.\n\nUnser [Token-Zähler](/token-counter) zeigt eine GPT-4o-Zählung und eine Claude-Schätzung nebeneinander – das reicht meist, um zu erkennen, ob ein Prompt bequem innerhalb des Limits liegt oder unangenehm knapp daran.",
    },
    "why-it-matters": {
      heading: "Warum die Zahl wichtig ist",
      body: "**Kosten.** API-Preise gelten pro Token, Eingabe und Ausgabe werden getrennt abgerechnet, und die Ausgabe ist typischerweise um ein Mehrfaches teurer. Ein doppelt so langer System-Prompt verdoppelt diese Kosten bei jedem einzelnen Aufruf – so etwas fällt im Test nicht auf, wird aber bei Volumen teuer.\n\n**Kontextlimits.** Das Fenster umfasst *alles*: System-Prompt, Gesprächsverlauf, abgerufene Dokumente, die aktuelle Nachricht und den reservierten Platz für die Antwort. Lange Chats scheitern nicht, weil eine einzelne Nachricht lang ist, sondern weil sich der Verlauf ansammelt.\n\n**Abschneiden.** Wenn die Eingabe das Limit überschreitet, fällt etwas weg – oft stillschweigend, und oft der früheste Inhalt. Ein Modell, das deine Anweisungen „vergessen“ hat, hatte sie häufig schlicht herausgeschnitten.\n\n**Chunking für Retrieval.** Das Aufteilen von Dokumenten für Embeddings erfolgt in Tokens, nicht in Zeichen. Nach Zeichenzahl bemessene Abschnitte werden uneinheitlich, und Abschnitte, die mitten im Satz enden, liefern schlechte Treffer. Um langen Text in brauchbare Teile zu zerlegen, schneidet der [Text-Splitter](/text-splitter) in der Nähe von Absatzgrenzen statt mitten im Wort.",
    },
    "reducing-tokens": {
      heading: "Die Zahl senken, ohne Bedeutung zu verlieren",
      body: "Die wirksamsten Maßnahmen, ungefähr in dieser Reihenfolge:\n\n1. **Gesprächsverlauf kürzen.** In langen Chats überwiegt er alles andere. Fasse alte Runden zusammen, statt sie wortwörtlich erneut zu senden.\n2. **Redundante Anweisungen streichen.** Eine Regel dreifach zu formulieren macht es nicht dreimal wahrscheinlicher, dass sie befolgt wird. Es verdreifacht aber zuverlässig ihre Kosten.\n3. **Formatierungsartefakte entfernen.** Unsichtbare Zeichen, wiederholte Leerzeichen und dekorative Trennlinien werden alle tokenisiert, und eine Reihe von vierzig Bindestrichen kann mehr kosten als der Satz darüber. [Unsichtbare Zeichen entfernen](/remove-invisible-characters) beseitigt die, die du nicht sehen kannst.\n4. **JSON-Schlüssel kürzen** in strukturierten Prompts. `{\"n\": ...}` statt `{\"customer_full_name\": ...}` macht über tausend Datensätze hinweg einen großen Unterschied.\n5. **Nur relevante Auszüge senden.** Drei passende Absätze abzurufen schlägt das Einfügen des ganzen Dokuments – und liefert meist auch bessere, nicht nur günstigere Antworten.\n\nWas *nicht* hilft: gewöhnliche Satzzeichen entfernen, Artikel streichen oder in abgehacktem Telegrammstil schreiben. Die Einsparung ist marginal, der Schaden für die Ausgabequalität nicht.",
    },
  },
  faqs: [
    { question: "Wie viele Tokens sind 1.000 Wörter?", answer: "Etwa 1.300 Tokens bei normalem englischem Fließtext, basierend auf grob 0,75 Wörtern pro Token. Code, JSON und nichtenglischer Text liegen deutlich höher – Chinesisch, Japanisch und Koreanisch verbrauchen oft ein bis zwei Tokens pro Zeichen." },
    { question: "Warum unterscheidet sich die Token-Zahl bei GPT und Claude?", answer: "Jede Modellfamilie nutzt ihren eigenen Tokenizer mit einem anderen gelernten Vokabular, daher wird derselbe Text unterschiedlich zerlegt. Abweichungen von 10–20 % sind bei englischem Fließtext normal, bei Code und nichtenglischem Text ist die Lücke größer." },
    { question: "Was ist ein Token in einem KI-Modell?", answer: "Ein Textfragment aus dem festen Vokabular des Modells. Häufige Wörter sind meist ein einziges Token, seltene Wörter werden in mehrere Teile zerlegt – „unbelievable“ kann so drei Tokens werden, während „international“ nur eines ist." },
    { question: "Zählen Leerzeichen und Satzzeichen als Tokens?", answer: "Ja. Leerzeichen hängen normalerweise am Anfang des folgenden Tokens, und Satzzeichen sind häufig eigene Tokens. Lange Folgen wiederholter Leerzeichen oder dekorative Trennlinien können überraschend viele verbrauchen." },
    { question: "Wie kann ich meinen Token-Verbrauch senken?", answer: "Kürze zuerst den angesammelten Gesprächsverlauf – in langen Chats dominiert er alles andere. Entferne dann doppelte Anweisungen, unsichtbare Zeichen und wiederholte Leerzeichen, kürze JSON-Schlüssel und sende nur den relevanten Auszug eines Dokuments statt des Ganzen." },
  ],
};
