import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "7 Anzeichen, dass ein Text von einer KI stammt",
  description: "Die sieben Formatierungs- und Stilmuster in KI-Texten, wie du jedes einzelne prüfst – und warum keines davon allein ein Beweis ist.",
  h1: "Sieben Anzeichen, dass ein Text von einer KI stammt",
  dek: "Vier davon sind messbar, drei nur spürbar – und die ehrlichen Grenzen von beidem.",
  answer: "Die verlässlichsten Anzeichen sind mechanischer Natur: lange Gedankenstriche in gleichmäßiger Verteilung, typografische Anführungszeichen, unsichtbare Unicode-Zeichen und Aufzählungen mit Emojis. Stilistische Anzeichen – absichernde Formulierungen, die Konstruktion „nicht nur X, sondern Y“ und ungewöhnlich gleichmäßige Absatzlängen – sind schwächer. Keines davon beweist für sich allein etwas; es sind Muster, keine Beweise.",
  sections: {
    "mechanical-signs": {
      heading: "Die vier mechanischen Anzeichen, die sich wirklich messen lassen",
      body: "Diese Anzeichen sind zählbar. Du kannst sie mit einem Werkzeug prüfen und erhältst eine Zahl statt eines Eindrucks – genau das macht sie nützlicher als Erkennung aus dem Bauchgefühl.\n\n**1. Lange Gedankenstriche in gleichmäßiger Verteilung.** Chat-Modelle setzen den langen Gedankenstrich (—) deutlich konsistenter ein als Menschen, weil dafür eine Tastenkombination nötig ist, die die meisten Schreibenden nie gelernt haben. Ein oder zwei in einem langen Dokument sind normal. Ungefähr einer pro Absatz, gleichmäßig verteilt, ist es nicht. Der [Leitfaden zu Gedankenstrichen](/guides/why-chatgpt-uses-em-dashes) erklärt, warum diese Angewohnheit so tief verankert ist.\n\n**2. Typografische Anführungszeichen und Satzzeichen.** KI-Ausgaben enthalten häufig gerichtete Anführungszeichen (\" \"), geschwungene Apostrophe (') und ein echtes Auslassungszeichen (…) statt drei Punkten. Textverarbeitungen erzeugen diese Zeichen ebenfalls automatisch – aussagekräftig sind sie daher nur dort, wo keine Autokorrektur im Spiel war: in einem Klartext-Feld, einem Code-Kommentar, einer CSV-Datei.\n\n**3. Unsichtbare Unicode-Zeichen.** Nullbreiten-Leerzeichen, geschützte Leerzeichen und schmale geschützte Leerzeichen überstehen das Kopieren aus einem Chat-Fenster häufig. Mit bloßem Auge sind sie nicht erkennbar, und sie sind der stärkste mechanische Marker, weil sie bei normaler Tastatureingabe praktisch nie entstehen.\n\n**4. Aufzählungen mit Emojis.** Strukturierte Antworten mit einem dekorativen Emoji am Anfang jedes Punkts, Zwischenüberschriften aus Fettdruck statt echten Überschriften und dreifach verschachtelte Listen – das ist ein Haussstil, den Chat-Oberflächen fördern und den die wenigsten menschlichen Autoren verwenden.",
    },
    "stylistic-signs": {
      heading: "Die drei stilistischen Anzeichen – schwächer, aber wissenswert",
      body: "Stilmuster lassen sich leicht falsch deuten, denn viele sorgfältig geschriebene menschliche Texte teilen sie. Behandle sie als Anlass genauer hinzusehen, niemals als Befund.\n\n**5. Absichernde, ausgewogene Rahmung.** Sätze, die jede Frage als zwei gleichermaßen vernünftige Seiten darstellen, Absätze, die mit der Wiederholung der Frage beginnen, und Schlusssätze, die zusammenfassen, ohne etwas hinzuzufügen. Das stammt aus einem Training, das Hilfsbereitschaft und Unverbindlichkeit zugleich belohnt.\n\n**6. Die Konstruktion „nicht nur X, sondern Y“.** Dazu Formulierungen wie „es ist erwähnenswert, dass“, „eintauchen in“, „sich durch die Komplexität von … navigieren“ und „in der heutigen schnelllebigen Welt“. Das sind keine verbotenen Wörter – es ist ganz normales Deutsch. Auffällig ist, wie oft sie in einem einzigen kurzen Text gebündelt auftreten.\n\n**7. Ungewöhnlich gleichmäßige Struktur.** Absätze von nahezu identischer Länge, Abschnitte mit verdächtig gleicher Anzahl an Aufzählungspunkten und ein Fazit, das die Einleitung spiegelt. Menschliche Entwürfe sind ungleichmäßiger; ein Absatz wird lang, weil der Schreibende zu genau diesem Punkt mehr zu sagen hatte.\n\nGerade die Vokabelsignale veralten schnell. Jede Liste vermeintlicher „KI-Wörter“, die kursiert, fließt in den allgemeinen Schreibstil und in die Abstimmung der nächsten Modellgeneration ein. Mechanische Anzeichen sind beständiger, weil sie Nebenprodukte der Kodierung sind, nicht des Stils.",
    },
    "how-to-check": {
      heading: "So prüfst du ein Dokument in einem Durchgang",
      body: "Eine praktische Reihenfolge, die günstigste Prüfung zuerst:\n\n1. **Nach unsichtbaren Zeichen suchen.** Das ist die Prüfung mit dem höchsten Signalwert bei geringstem Aufwand. Füge den Text in das Werkzeug [Unsichtbare Zeichen entfernen](/remove-invisible-characters) ein – es listet jedes Nullbreiten-Leerzeichen, jeden weichen Trennstrich, jede Byte-Reihenfolge-Marke und Richtungsmarke mit Anzahl auf.\n2. **Die mechanischen Artefakte gemeinsam zählen.** Der [KI-Text-Cleaner](/clean-ai-text) erfasst Gedankenstriche, typografische Anführungszeichen, unsichtbare Zeichen und Emojis in einem Durchgang. So siehst du, ob mehrere Signale gemeinsam auftreten, statt jedem einzeln hinterherzulaufen.\n3. **Nach den Stilmustern lesen.** Erst wenn du die Zahlen hast. Zahlen zuerst verhindern, dass du dich selbst in eine Schlussfolgerung hineinredest.\n4. **Den Kontext abwägen.** Aus Word kopierter Text enthält typografische Anführungszeichen, egal wer ihn geschrieben hat. Direkt in ein Klartext-Feld getippter Text nicht.\n\nEntscheidend ist das gemeinsame Auftreten. Ein einzelner Gedankenstrich bedeutet nichts. Gedankenstriche *und* typografische Anführungszeichen *und* zwei Nullbreiten-Leerzeichen *und* Emoji-Aufzählungen in einem Dokument, das direkt in ein Klartext-Formular getippt wurde, sind eine wirklich ungewöhnliche Kombination.",
    },
    "why-not-proof": {
      heading: "Warum all das kein Beweis ist",
      body: "Für jedes der genannten Anzeichen gibt es eine harmlose Erklärung.\n\nWord und Google Docs wandeln doppelte Bindestriche automatisch in Gedankenstriche und gerade Anführungszeichen in geschwungene um. Beim Kopieren von einer modernen Website können unsichtbare Zeichen mitkommen. Professionelle Redakteure schreiben genau in dem ausgewogenen, absichernden Register, das maschinell klingt. Und Nicht-Muttersprachler schreiben häufig formeller und strukturell regelmäßiger – genau deshalb markieren kommerzielle KI-Detektoren deren Texte deutlich häufiger.\n\nDazu kommt die offensichtliche Zirkularität: Wer KI-Ausgaben in einen Texteditor kopiert und eine Bereinigung durchführt, entfernt jedes mechanische Anzeichen in etwa zehn Sekunden. Die Signale, die am leichtesten zu messen sind, sind auch am leichtesten zu beseitigen.\n\nDie ehrliche Position lautet daher: Formatierungsanalyse sagt dir, **welche Zeichen in einem Dokument stehen**. Sie kann nicht sagen, wer sie dort hineingebracht hat. Unsere Werkzeuge melden bewusst nur Zählwerte und sprechen niemals ein Urteil – denn ein Urteil wäre eine Vermutung, die sich eine Zahl als Verkleidung übergezogen hat. Wenn du wissen willst, ob ein Mensch einen Text geschrieben hat, bekommst du die Antwort im Gespräch mit ihm – über Entwurfsverläufe, Quellen und die Fähigkeit, das eigene Argument zu erklären –, nicht durch das Zählen von Strichen.",
    },
  },
  faqs: [
    { question: "Was ist das verlässlichste Anzeichen für einen KI-Text?", answer: "Unsichtbare Unicode-Zeichen wie Nullbreiten-Leerzeichen sind der stärkste mechanische Marker, weil sie bei normaler Tastatureingabe praktisch nie entstehen, beim Kopieren aus einem Chat-Fenster aber häufig. Allerdings können sie auch beim Kopieren von einer Website mitkommen – sie weisen also auf die Herkunft des Einfügens hin, nicht auf die Urheberschaft." },
    { question: "Funktionieren KI-Detektoren wirklich?", answer: "Nicht zuverlässig. Sie erzeugen falsch-positive Treffer bei menschlichen Texten – Nicht-Muttersprachler sind überproportional betroffen – und lassen sich durch leichte Überarbeitung austricksen. Formatierungsanalyse kann konkrete Artefakte zählen, aber kein Werkzeug, auch unseres nicht, kann allein aus dem Text die Urheberschaft feststellen." },
    { question: "Bedeuten Gedankenstriche oder typografische Anführungszeichen, dass mir KI-Nutzung vorgeworfen wird?", answer: "Das sollte nicht so sein, und es wäre eine schlechte Grundlage für einen Vorwurf. Word und Google Docs erzeugen beides automatisch aus normaler Eingabe. Wenn du dir Gedanken über die Wirkung eines Dokuments machst, kannst du die Satzzeichen in einfache ASCII-Zeichen umwandeln – das entfernt die Artefakte, ohne ein einziges Wort deines Textes zu ändern." },
    { question: "Kann ich diese Anzeichen aus KI-Texten entfernen?", answer: "Ja, und zwar schnell – genau deshalb sind sie schwache Beweise. Gedankenstriche ersetzen, Anführungszeichen vereinheitlichen und unsichtbare Zeichen entfernen dauert Sekunden. Das ist ein Grund, Erkennungsversprechen skeptisch zu begegnen – keine Technik, um fremde Arbeit als eigene auszugeben." },
  ],
};
