import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Warum verwendet ChatGPT so viele Gedankenstriche?",
  description: "ChatGPT setzt viele Gedankenstriche, weil es aus redigierten Texten gelernt hat. Warum das so auffällig ist – und wie man sie sauber entfernt.",
  h1: "Warum verwendet ChatGPT so viele Gedankenstriche?",
  dek: "Das Satzzeichen, das zur KI-Signatur wurde – und was man dagegen tun kann.",
  answer: "ChatGPT verwendet Gedankenstriche, weil es mit professionell redigierten Texten trainiert wurde – Büchern, Essays und Journalismus –, in denen der Gedankenstrich zum Standard gehört, um Einschübe abzugrenzen. Das Modell reproduziert diese Gewohnheit weitaus gleichmäßiger als menschliche Gelegenheitsschreiber, die das Zeichen kaum je tippen. Nicht das Zeichen selbst, sondern diese Gleichmäßigkeit lässt es als KI-Merkmal wirken.",
  sections: {
    "where-it-comes-from": {
      heading: "Woher die Gewohnheit stammt",
      body: "Große Sprachmodelle lernen Zeichensetzung so wie alles andere: indem sie Muster aus ihren Trainingsdaten aufnehmen. Diese Daten sind stark auf **veröffentlichte, professionell redigierte Texte** ausgerichtet – Bücher, lange Reportagen, Essays und Dokumentationen. In dieser Welt ist der Gedankenstrich völlig alltäglich. Lektorinnen und Redakteure setzen ihn ständig ein, um einen Einschub abzugrenzen, eine Zusammenfassung einzuleiten oder vor dem letzten Satzteil eine Zäsur zu setzen.\n\nLockeres Schreiben im Internet sieht ganz anders aus. In Chats, Forenbeiträgen und E-Mails verwenden Menschen Kommas, Klammern und Punkte. Die meisten tippen nie einen Gedankenstrich, weil es auf einer Standardtastatur keine Taste dafür gibt.\n\nHinzu kommt ein zweiter Effekt. Modelle werden darauf optimiert, Texte zu erzeugen, die Leser als klar und gut geschrieben bewerten – und der Gedankenstrich ist für diese Aufgabe ungewöhnlich gut geeignet. Er ist das flexibelste Zeichen der englischen Zeichensetzung: Er kann ein Komma, einen Doppelpunkt, ein Semikolon oder ein Klammerpaar ersetzen. Wenn mehrere Zeichen in Frage kommen, ist der Griff zum Gedankenstrich immer vertretbar. Ein System, das auf flüssig und souverän klingende Texte optimiert ist, landet daher immer wieder bei ihm.",
    },
    "why-it-reads-as-ai": {
      heading: "Warum der Gedankenstrich zum KI-Merkmal wurde",
      body: "Der Gedankenstrich wurde nicht verdächtig, weil er selten ist. Er wurde verdächtig wegen der **Gleichmäßigkeit, mit der er auftritt**.\n\nEinen Gedankenstrich zu tippen kostet bewusste Mühe. Auf einem Mac ist es <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>; unter Windows <kbd>Alt</kbd> + <kbd>0151</kbd> oder eine Autokorrekturregel. Auf den meisten Smartphone-Tastaturen versteckt er sich hinter einem langen Tastendruck. Wenn ein Mensch also einen Gedankenstrich setzt, ist das meist eine bewusste stilistische Entscheidung – und das Zeichen taucht sporadisch auf: ein paarmal in einem langen Dokument, dort gehäuft, wo der Schreiber eine dramatische Pause wollte.\n\nEin Sprachmodell kennt diese Hürde nicht. Jedes Zeichen kostet gleich viel. Das Ergebnis ist ein charakteristischer statistischer Fingerabdruck:\n\n- Gedankenstriche erscheinen in jedem Absatz in gleichmäßigem Rhythmus statt in Schüben.\n- Sie treten häufig **paarweise** auf und umschließen einen Einschub, für den die meisten Menschen Kommas verwenden würden.\n- Sie tauchen in Textsorten auf, in denen sie sonst nie vorkämen – etwa in einer kurzen Antwort, einem Listenpunkt oder einem Fehlerbericht.\n\nKeines dieser Muster ist falsch. Sie sind nur regelmäßiger, als menschliches Schreiben es typischerweise ist – und genau diese Regelmäßigkeit fällt Lesern auf.",
    },
    "how-to-remove": {
      heading: "Gedankenstriche entfernen, ohne Sätze zu zerstören",
      body: "Der häufigste Fehler ist, jeden Gedankenstrich durch einen Bindestrich zu ersetzen. Ein Bindestrich ist ein anderes Zeichen mit einer anderen Aufgabe – das Ergebnis wirkt wie ein Tippfehler, nicht wie saubere Prosa. Richte den Ersatz nach der Funktion des Strichs.\n\n**Ein Gedankenstrichpaar um einen Einschub** wird meist zu einem Kommapaar. Handelt es sich um einen echten Exkurs, passen Klammern besser.\n\n**Ein einzelner Gedankenstrich vor einer Schlussfolgerung** ersetzt eigentlich einen Doppelpunkt. Tausche ihn gegen einen aus – oder beende den Satz und beginne einen neuen.\n\n**Ein einzelner Gedankenstrich mitten im Satz** markiert oft eine härtere Zäsur, als der Satz braucht. Zwei getrennte Sätze lesen sich fast immer besser als jedes Ersatzzeichen.\n\n| Funktion des Strichs | Bessere Alternative |\n| --- | --- |\n| Umschließt einen leichten Einschub | Kommas |\n| Umschließt einen Exkurs | Klammern |\n| Leitet eine Zusammenfassung ein | Doppelpunkt |\n| Markiert eine harte Zäsur | Punkt, Satz teilen |\n| Zeigt einen Bereich (2020—2024) | Bis-Strich, kein Gedankenstrich |\n\nBei langen Dokumenten hilft das Werkzeug [Gedankenstriche entfernen](/remove-em-dashes): Es ersetzt jeden Gedankenstrich durch die von dir gewählte Alternative und meldet, wie viele Stellen geändert wurden – so kannst du die Zahl mit deinem eigenen Eindruck abgleichen, statt einem stillen Suchen-und-Ersetzen zu vertrauen.",
    },
    "when-to-keep": {
      heading: "Wann du den Gedankenstrich behalten solltest",
      body: "Jeden Gedankenstrich aus dem eigenen Text zu entfernen, wäre eine Überkorrektur. Das Zeichen existiert, weil es etwas leistet, das die Alternativen nicht können: Es erzeugt eine Pause mit mehr Nachdruck als ein Komma und weniger Endgültigkeit als ein Punkt – ohne den bürokratischen Beiklang eines Semikolons.\n\nBehalte ihn, wenn:\n\n- der Satz wirklich eine harte Unterbrechung braucht und ein Komma zu weich wäre,\n- du eine Quelle zitierst, die einen verwendet. Zeichensetzung innerhalb eines Zitats zu ändern, verändert das Zitat,\n- es der Hausstil verlangt. Die meisten Buchverlage und viele Redaktionen setzen Gedankenstriche großzügig ein,\n- du literarische oder persönliche Texte schreibst, bei denen Rhythmus wichtiger ist als ein maschinenneutrales Erscheinungsbild.\n\nDas realistische Ziel sind nicht null Gedankenstriche. Es sind Gedankenstriche, die erscheinen, weil du sie gewählt hast – in einer Häufigkeit, die zu deiner eigenen Stimme passt. Ein oder zwei in einem langen Artikel wirken bewusst gesetzt. Einer pro Absatz wirkt wie eine Voreinstellung.",
    },
    "other-habits": {
      heading: "Der Gedankenstrich ist nur eine Angewohnheit unter mehreren",
      body: "Der Strich bekommt die Aufmerksamkeit, weil er ein einzelnes Zeichen ist, nach dem man suchen kann. Er ist nicht die einzige Regelmäßigkeit, und die anderen entstehen aus denselben zwei Kräften: Trainingsdaten voller redigierter, strukturierter Texte, und eine Abstimmung auf Antworten, die Leser als klar bewerten.\n\n- **Fettdruck bei Schlüsselphrasen.** Keine Überschriften, sondern eine oder zwei hervorgehobene Phrasen mitten in einem Absatz, oft die ersten Worte eines Listenpunkts. Das macht eine Antwort überfliegbar, worauf eine Chat-Oberfläche optimiert.\n- **Aufzählungen, wo Fließtext reichen würde.** Ein Gedanke, der drei Sätze braucht, kommt als drei Aufzählungspunkte. Listen schneiden als Antworten gut ab, also greifen Modelle standardmäßig darauf zurück, selbst wenn die Punkte gar nicht wirklich parallel sind.\n- **Überschriften bei kurzen Antworten.** Eine vierabsätzige Antwort mit zwei Zwischenüberschriften darüber. Die Struktur ist aus der Dokumentation entliehen, wo sie ihren Platz verdient, und wird auf Text angewendet, der viel zu kurz für eine Navigation ist.\n- **Emoji als Ausstattung.** Verwendet als Aufzählungszeichen oder Abschnittssymbole statt als Ausdruck – ein Häkchen vor jedem Punkt, eine Rakete über dem Block „Nächste Schritte“.\n- **„Es ist nicht nur X – es ist Y.“** Der Korrektur-und-Steigerung-Zug, dazu „es ist erwähnenswert, dass“ und „entscheidend ist“. Für sich genommen gewöhnliche Konstruktionen; auffällig ist, wie oft sie sich in einem kurzen Text häufen.\n- **Die Regel der Drei.** Drei Beispiele, drei Aufzählungspunkte, drei Adjektive, weil drei vollständig klingt. Menschliche Entwürfe sind unregelmäßiger – zwei Gründe, oder fünf, je nachdem, wie viele es tatsächlich gab.\n\nKeines davon ist ein Wasserzeichen. Kein Anbieter stempelt ein verstecktes Signal in gewöhnlichen Text, und keine dieser Angewohnheiten wurde als Erkennungsmerkmal entworfen. Es sind Stil-Voreinstellungen, und sie lassen sich entfernen oder wegbitten wie jede andere Stil-Voreinstellung. Willst du sie aus einem vorhandenen Dokument entfernen, streift [KI-Text humanisieren](/humanize-ai-text) die mechanische Schicht ab – die Zeichensetzung, die unsichtbaren Zeichen, das dekorative Emoji –, und [Aufzählungspunkte in Fließtext](/bullet-points-to-paragraph) verwandelt überlisteten Text zurück in Prosa. Keines der beiden behauptet, einen Detektor zu überlisten, und du solltest allem misstrauen, das das behauptet.\n\nDie vollständige Liste, einschließlich der zählbaren, steht im Leitfaden [Anzeichen für KI-geschriebene Texte](/guides/signs-of-ai-written-text).",
    },
    "not-proof": {
      heading: "Gedankenstriche sind kein Beweis für KI-Texte",
      body: "Das muss klar gesagt werden, weil viele Ratschläge im Netz hier falsch liegen: **Das Vorkommen von Gedankenstrichen beweist nichts.**\n\nViele von Menschen geschriebene Texte stecken voller Gedankenstriche. Microsoft Word wandelt zwei Bindestriche schon beim Tippen automatisch in einen Gedankenstrich um – Schreiber erzeugen sie also, ohne das Zeichen je bewusst zu wählen. Wer redaktionell schreiben gelernt hat, setzt sie instinktiv. Ganze Publikationen schreiben sie vor.\n\nEs gibt keine verlässliche Methode, KI-generierte Texte an der Zeichensetzung zu erkennen – und die kommerziellen Werkzeuge, die das behaupten, haben gut dokumentierte Falsch-Positiv-Raten, von denen nicht muttersprachliche Schreiber überdurchschnittlich betroffen sind. Einen Gedankenstrich als Beweis zu werten, hat reale Konsequenzen, wenn der Vorwurf eine Studentin oder einen Kollegen trifft.\n\nWas eine Formatierungsanalyse ehrlich sagen kann, ist mechanisch: wie viele Gedankenstriche in diesem Dokument stehen, wie viele typografische Anführungszeichen, wie viele unsichtbare Zeichen. Das sind Zählungen, keine Urteile. Unser [KI-Text-Bereiniger](/clean-ai-text) meldet genau diese Zahlen und trifft keine Aussage darüber, wer oder was den Text geschrieben hat – das Einzige, was ein Formatierungswerkzeug seriös leisten kann.\n\nWenn du das Gesamtbild sehen willst, welche Formatierungsartefakte mit KI-Ausgaben einhergehen, behandelt der Leitfaden [Anzeichen für KI-geschriebene Texte](/guides/signs-of-ai-written-text) den Rest.",
    },
  },
  faqs: [
    { question: "Bedeuten Gedankenstriche, dass mein Text nach KI aussieht?", answer: "Nicht für sich genommen. Gedankenstriche sind in redigiertem Englisch Standard und kommen in menschlichen Texten häufig vor – auch weil Word sie automatisch aus zwei Bindestrichen erzeugt. Was maschinell wirkt, ist eine hohe, gleichmäßig verteilte Häufigkeit – ungefähr einer pro Absatz im gesamten Dokument –, meist zusammen mit anderen Artefakten wie typografischen Anführungszeichen und Listen mit Emoji-Symbolen." },
    { question: "Wodurch sollte ich einen Gedankenstrich ersetzen?", answer: "Richte den Ersatz nach der Funktion. Ein Paar um einen Einschub wird zu Kommas oder Klammern; ein einzelner Strich vor einer Schlussfolgerung wird zum Doppelpunkt; ein Strich, der eine harte Zäsur markiert, liest sich meist als zwei getrennte Sätze besser. Ersetze einen Gedankenstrich nicht durch einen Bindestrich – das ist ein anderes Zeichen mit einer anderen Aufgabe." },
    { question: "Warum verwendet ChatGPT Gedankenstriche statt Kommas?", answer: "Der Gedankenstrich ist das flexibelste Zeichen des Englischen und kann Komma, Doppelpunkt, Semikolon oder Klammern ersetzen. Wenn mehrere Zeichen grammatisch vertretbar wären, ist er immer eine sichere Wahl – ein Modell, das auf flüssige Prosa optimiert ist, wählt ihn daher überdurchschnittlich oft." },
    { question: "Kann ich ChatGPT daran hindern, Gedankenstriche zu verwenden?", answer: "Du kannst es direkt im Prompt verlangen, etwa: „Verwende keine Gedankenstriche; nutze Kommas oder getrennte Sätze.“ Die Befolgung ist unzuverlässig und lässt bei langen Antworten nach – meist ist es schneller, normal schreiben zu lassen und die Striche anschließend zu entfernen." },
    { question: "Ist ein Gedankenstrich dasselbe wie ein Bindestrich?", answer: "Nein. Ein Bindestrich (-, U+002D) verbindet Wortteile. Ein Bis-Strich (–, U+2013) markiert Bereiche wie 2020–2024. Ein Gedankenstrich (—, U+2014) grenzt einen Einschub im Satz ab. Es sind drei verschiedene Zeichen mit zunehmender Breite, die nicht austauschbar sind." },
  ],
};
