import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "ChatGPT nasconde caratteri invisibili?",
  description: "L'output dell'IA contiene davvero Unicode invisibili. Ecco cosa c'è dentro, da dove arriva e se si tratta di una filigrana.",
  h1: "ChatGPT nasconde caratteri invisibili nel tuo testo?",
  dek: "La teoria della filigrana, cosa mostrano davvero i byte e come controllare il tuo testo.",
  answer: "L'output dell'IA contiene spesso Unicode invisibili, soprattutto spazi non separabili e spazi non separabili stretti. Ma si tratta di normali sottoprodotti della formattazione del testo, non di una filigrana nascosta. La vera filigrana del testo esiste e funziona orientando statisticamente la scelta delle parole, senza lasciare caratteri speciali da trovare. Puoi controllare qualsiasi testo da solo in pochi secondi.",
  sections: {
    "the-claim": {
      heading: "L'affermazione, e perché si è diffusa",
      body: "Ogni pochi mesi un post diventa virale mostrando che il testo copiato da ChatGPT contiene caratteri nascosti, con la conclusione che OpenAI starebbe inserendo di nascosto una filigrana nell'output per renderlo rintracciabile.\n\nL'osservazione è vera. La conclusione non è supportata.\n\nCiò che le persone trovano è reale: incolla una risposta della chat in un ispettore di caratteri e vedrai spesso code point che non visualizzano nulla. Il salto avviene nell'interpretazione. Una filigrana deve sopravvivere alle modifiche, essere difficile da rimuovere e codificare qualcosa. Caratteri che svaniscono appena qualcuno esegue un trova e sostituisci, e che non contengono alcun contenuto recuperabile, non soddisfano nessuna di queste condizioni.",
    },
    "what-is-there": {
      heading: "Cosa c'è davvero nel testo",
      body: "I caratteri invisibili che compaiono nell'output dell'IA sono in gran parte normali caratteri tipografici:\n\n| Carattere | Code point | Perché compare |\n| --- | --- | --- |\n| Spazio non separabile | U+00A0 | Tiene un numero e la sua unità sulla stessa riga |\n| Spazio non separabile stretto | U+202F | Spaziatura sottile prima della punteggiatura e nei numeri |\n| Spazio a larghezza zero | U+200B | Suggerimenti per l'interruzione di riga, spesso ereditati da testo web |\n| Trattino morbido | U+00AD | Indica dove una parola può essere spezzata quando va a capo |\n| Byte-order mark | U+FEFF | Artefatto di codifica proveniente da un file a monte |\n\nOgnuno ha uno scopo tipografico legittimo e ognuno esiste da decenni prima dei modelli linguistici. Arrivano attraverso le stesse vie di sempre: il modello li ha appresi dal testo di addestramento che li conteneva, l'interfaccia della chat visualizza l'output formattato come HTML, e copiare da una pagina web renderizzata porta con sé qualsiasi cosa il markup contenesse.\n\nQuest'ultima via conta più di quanto ci si aspetti. Gran parte di ciò che viene attribuito al modello è in realtà introdotto dalla *copia dal browser*, non dalla generazione. Copiare la stessa risposta tramite l'API produce spesso un testo più pulito rispetto a copiarla dalla finestra della chat.",
    },
    "does-watermarking-exist": {
      heading: "La filigrana dei testi IA esiste davvero?",
      body: "Sì, ma non funziona come ipotizzano i post virali.\n\nSynthID-Text di Google DeepMind è l'approccio meglio documentato, pubblicato su *Nature* nel 2024. Funziona orientando sottilmente quali parole il modello campiona a ogni passo, così il testo finito porta una firma statistica rilevabile da un verificatore corrispondente. Non ci sono caratteri speciali coinvolti. Nulla viene inserito. La filigrana vive nella *scelta di parole normali*, ed è per questo che sopravvive alla copia e alle piccole modifiche, e perché non puoi trovarla ispezionando i code point.\n\nOpenAI ha discusso pubblicamente di ricerca sulle filigrane del testo e non ha rilasciato un'implementazione confermata rivolta agli utenti per l'output di ChatGPT.\n\nL'implicazione pratica va contro il panico: se un modello che usi ha una filigrana, rimuovere i caratteri invisibili non la eliminerà. E se trovi caratteri invisibili, non è una prova di filigrana: è una prova di formattazione.",
    },
    "why-it-matters": {
      heading: "Perché i caratteri invisibili contano comunque",
      body: "Filigrana o no, di solito è meglio eliminarli, perché rompono le cose in silenzio:\n\n- **La ricerca e il trova e sostituisci falliscono.** Uno spazio a larghezza zero tra due lettere fa sì che la ricerca della parola non trovi nulla, senza alcun motivo visibile.\n- **La convalida dei moduli rifiuta l'input.** Un indirizzo email o una chiave di licenza con uno spazio non separabile finale fallisce un confronto che a schermo sembra corretto.\n- **Il codice si rompe in alcuni linguaggi e in altri no.** Uno spazio non separabile al posto di uno spazio normale è un errore di sintassi in Python, Go, Ruby, shell e JSON, e punta a una riga che sembra perfetta. JavaScript, TypeScript e C accettano U+00A0 come spaziatura ordinaria e compilano senza protestare: il che è un problema a sé, perché il carattere sopravvive così nel file finché non arriva a uno strumento che invece si oppone.\n- **Le importazioni CSV si corrompono.** Un byte-order mark si attacca all'intestazione della prima colonna, così il primo campo non viene mappato senza alcun avviso.\n- **Compaiono record duplicati.** Due voci che sembrano identiche sono stringhe diverse, quindi la deduplicazione le ignora.\n\nQuesti errori sono particolarmente fastidiosi perché il testo sembra corretto. Ogni istinto di debug punta da un'altra parte.",
    },
    "how-to-check": {
      heading: "Come controllare e pulire il tuo testo",
      body: "Incolla il testo nello [Scanner di caratteri invisibili](/remove-invisible-characters). Li rimuove su richiesta e riporta tre numeri: il totale dei caratteri nascosti trovati, quanti di questi erano a larghezza zero e quanti erano trattini morbidi. Il dato sui caratteri a larghezza zero comprende anche i segni direzionali sinistra-destra e destra-sinistra, e un byte-order mark rientra nel totale senza avere una riga propria. Quando hai bisogno di sapere quale carattere si trova esattamente dove, [Mostra caratteri invisibili](/show-invisible-characters) etichetta ognuno al suo posto invece di eliminarlo. Nulla lascia il tuo browser: entrambi funzionano in locale.\n\nSe vuoi un quadro più ampio, il [Pulitore di testo IA](/clean-ai-text) copre i caratteri invisibili insieme a trattini lunghi, virgolette curve ed emoji in un solo passaggio.\n\nUn'abitudine che vale la pena prendere: esegui il controllo ogni volta che il testo attraversa un confine tra sistemi. Dalla finestra della chat a un editor di codice, da una pagina web a un foglio di calcolo, da un PDF a un modulo. È lì che i caratteri invisibili fanno danni, ed è il momento in cui costano meno rimuoverli.\n\nPer l'elenco completo di cosa sono questi caratteri e cosa fa ognuno, vedi il [riferimento sui caratteri Unicode invisibili](/guides/invisible-unicode-characters).",
    },
  },
  faqs: [
    { question: "ChatGPT inserisce una filigrana nel testo con caratteri invisibili?", answer: "Non ci sono prove in questo senso. I caratteri invisibili trovati nell'output di ChatGPT sono normali caratteri tipografici come spazi non separabili e spazi non separabili stretti, che esistono da decenni e non contengono alcun contenuto. Inoltre scompaiono con qualsiasi pulizia di base, il che li renderebbe inutili come filigrana." },
    { question: "Il testo generato dall'IA può avere una filigrana?", answer: "Sì. SynthID-Text di Google DeepMind, pubblicato su Nature nel 2024, orienta le scelte di parole del modello in modo che l'output porti una firma statistica. Non inserisce alcun carattere speciale, quindi ispezionare i code point non lo rivelerà mai, e rimuovere i caratteri invisibili non lo elimina." },
    { question: "Perché il testo copiato da ChatGPT contiene caratteri nascosti?", answer: "Soprattutto perché stai copiando HTML renderizzato da una pagina web. L'interfaccia della chat mostra output formattato, e la copia porta con sé i caratteri di spaziatura usati da quella formattazione. Recuperare la stessa risposta tramite l'API produce spesso un testo notevolmente più pulito." },
    { question: "Come trovo i caratteri invisibili nel mio testo?", answer: "Incollalo in uno scanner. Il nostro Scanner di caratteri invisibili riporta quanti caratteri nascosti sono presenti, quanti sono a larghezza zero e quanti sono trattini morbidi, poi li rimuove su richiesta. Per vedere quale carattere si trova dove, Mostra caratteri invisibili etichetta ognuno al suo posto. Entrambi funzionano interamente nel tuo browser." },
    { question: "I caratteri invisibili sono pericolosi?", answer: "Non pericolosi, ma davvero problematici. Rompono la ricerca, fanno fallire la convalida dei moduli, producono errori di sintassi nel codice, corrompono le intestazioni CSV e creano record duplicati che sembrano identici. Poiché il testo appare normale, questi bug sono insolitamente difficili da diagnosticare." },
  ],
};
