import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Trattino lungo, medio e breve: le differenze",
  description: "Tre caratteri, tre compiti. Quando usare ogni trattino, come digitarli su qualsiasi tastiera e perché confonderli crea problemi.",
  h1: "Trattino lungo, trattino medio e trattino",
  dek: "Tre caratteri Unicode diversi che si somigliano e non sono intercambiabili.",
  answer: "Il trattino (-) unisce parole composte: ben noto. Il trattino medio (–) indica intervalli e connessioni: pagine 20–24. Il trattino lungo (—) isola una frase all'interno di un periodo, come una virgola più forte. Sono tre caratteri Unicode distinti di larghezza crescente, e parser, ricerche e impaginazione li trattano in modo diverso.",
  sections: {
    "the-three-characters": {
      heading: "I tre caratteri a colpo d'occhio",
      body: "I nomi derivano dalla tipografia storica: il trattino medio era largo quanto una N maiuscola, il trattino lungo quanto una M maiuscola.\n\n| Segno | Nome | Code point | Larghezza | Uso principale |\n| --- | --- | --- | --- | --- |\n| - | Trattino-meno | U+002D | Il più corto | Parole composte |\n| – | Trattino medio | U+2013 | Media | Intervalli e connessioni |\n| — | Trattino lungo | U+2014 | Il più lungo | Incisi dentro una frase |\n\nIl primo è sulla tastiera. Gli altri due no, ed è questa la radice pratica di quasi tutta la confusione: si digita un trattino dove servirebbe un trattino medio o lungo, perché è l'unico disponibile senza scorciatoie.",
    },
    "the-hyphen": {
      heading: "Il trattino",
      body: "Il trattino unisce elementi in una singola unità.\n\n- **Modificatori composti prima di un sostantivo**: un autore *ben noto*, una struttura *all'avanguardia*. In molte lingue il trattino scompare quando la frase segue il sostantivo.\n- **Alcuni prefissi**, soprattutto per evitare collisioni o ambiguità: in inglese *re-elect*, *co-owner*, *re-cover* una sedia (a differenza di *recover*, guarire).\n- **Spezzare le parole a fine riga**, nell'impaginazione giustificata.\n- **Numeri composti**: in inglese *twenty-three*.\n\nTecnicamente il carattere della tastiera è il *trattino-meno*: un unico code point che funge da trattino, segno meno e flag da riga di comando, ereditato dalle macchine da scrivere e dai primi ASCII. Unicode ha un trattino dedicato (U+2010) e un segno meno (U+2212), ma quasi nulla li usa, e non dovresti iniziare tu: `-` è ciò che parser, shell e URL si aspettano.",
    },
    "the-en-dash": {
      heading: "Il trattino medio",
      body: "Il trattino medio significa *da... a*, *fino a* o *tra*. Connette invece di unire.\n\n- **Intervalli numerici**: pagine *20–24*, *2020–2024*, *9–17*. I manuali di stile sconsigliano di mescolarlo con le parole: scrivi *dal 2020 al 2024*, non *dal 2020–2024*.\n- **Connessioni e conflitti tra entità distinte**: il rally *Parigi–Dakar*, la relazione *medico–paziente*, l'asse *est–ovest*. Qui la distinzione dal trattino conta: *franco-tedesco* con il trattino suggerisce una cosa unica e fusa, mentre *Francia–Germania* con il trattino medio indica due parti in relazione.\n- **Modificatori composti in cui una parte è già formata da più parole**: un accordo *post–Seconda guerra mondiale*. Un trattino si attaccherebbe solo a \"Seconda\".\n- **Punteggi e votazioni**: una vittoria per *3–1*.\n\nIl trattino medio è il meno usato dei tre e quello più spesso sostituito da un trattino semplice. Nel testo corrente questa sostituzione è una piccola imprecisione tipografica che pochi lettori notano. Nei dati non è affatto piccola: un intervallo di date scritto con un trattino medio non corrisponderà a un'espressione regolare che cerca un trattino.",
    },
    "the-em-dash": {
      heading: "Il trattino lungo",
      body: "Il trattino lungo isola una frase, creando una pausa più forte di una virgola e più morbida di un punto.\n\n- **In coppia, attorno a un inciso**: *I risultati — che nessuno si aspettava — erano chiari.*\n- **Da solo, prima di una conclusione o di un ribaltamento**: *Ha controllato tutto due volte — e le è sfuggito lo stesso.*\n- **Per segnare un discorso interrotto** nei dialoghi.\n\nLa **spaziatura** è l'unico vero punto di disaccordo tra gli stili, e il disaccordo corre su tre binari. Chicago, APA e MLA usano il trattino lungo senza spazi: *parola—parola*. L'AP Stylebook mette uno spazio da entrambi i lati: *parola — parola*. Gli stili editoriali britannici che seguono le New Hart's Rules usano invece il trattino medio spaziato: *parola – parola*. Tutte e tre le convenzioni sono corrette; ciò che conta è la coerenza all'interno di un documento. L'output dell'IA usa tipicamente il trattino lungo spaziato, che è stile AP e non un ibrido: sembra fuori posto solo agli editor che considerano Chicago l'unica convenzione americana.\n\nIl trattino lungo è anche il segno diventato una firma non ufficiale del testo generato dall'IA, perché i modelli lo usano con molta più costanza delle persone. Ne parliamo in [perché ChatGPT usa così tanti trattini lunghi](/guides/why-chatgpt-uses-em-dashes).",
    },
    "typing-them": {
      heading: "Come digitare ciascuno",
      body: "| Piattaforma | Trattino medio (–) | Trattino lungo (—) |\n| --- | --- | --- |\n| macOS | <kbd>Opzione</kbd> + <kbd>-</kbd> | <kbd>Opzione</kbd> + <kbd>Maiusc</kbd> + <kbd>-</kbd> |\n| Windows | <kbd>Alt</kbd> + <kbd>0150</kbd> | <kbd>Alt</kbd> + <kbd>0151</kbd> |\n| Linux | <kbd>Ctrl</kbd> + <kbd>Maiusc</kbd> + <kbd>u</kbd>, 2013 | <kbd>Ctrl</kbd> + <kbd>Maiusc</kbd> + <kbd>u</kbd>, 2014 |\n| Microsoft Word | `parola - parola` seguito da uno spazio viene corretto automaticamente | `parola--parola` seguito da uno spazio viene corretto automaticamente |\n| Google Docs | Inserisci &rarr; Caratteri speciali | Nessuna conversione predefinita; Inserisci &rarr; Caratteri speciali, oppure aggiungi una tua sostituzione `--` |\n| HTML | `&ndash;` | `&mdash;` |\n| iOS / Android | Pressione prolungata sul tasto del trattino | Pressione prolungata sul tasto del trattino |\n\nI codici Alt di Windows richiedono un tastierino numerico: ecco perché tantissimi utenti di portatili non digitano mai questi caratteri.",
    },
    "when-it-breaks-things": {
      heading: "Quando la differenza rompe davvero qualcosa",
      body: "In prosa, usare un trattino al posto di un trattino medio è una raffinatezza tipografica. Fuori dalla prosa, questi sono tre code point distinti e la differenza è funzionale:\n\n- **Ricerca e trova-e-sostituisci** corrispondono ai caratteri esatti. Cercare `2020-2024` non troverà `2020–2024`.\n- **I comandi shell** richiedono U+002D. `--force` incollato da un documento in cui la correzione automatica lo ha trasformato in un trattino lungo non è un flag, e il messaggio di errore non menzionerà i trattini.\n- **CSV e JSON** trattano i trattini medi e lunghi come testo qualsiasi, il che di solito va bene — finché un valore che dovrebbe corrispondere a una chiave non corrisponde.\n- **URL e slug** accettano solo il trattino ASCII.\n- **Ordinamento e deduplicazione** trattano i tre come caratteri diversi, quindi voci che sembrano identiche non vengono raggruppate.\n\nSe devi normalizzare i trattini in un documento, [Rimuovere i trattini lunghi](/remove-em-dashes) li sostituisce con l'alternativa che scegli e ne riporta il conteggio, così puoi verificare che il numero corrisponda a quanto ti aspettavi invece di fidarti di una sostituzione silenziosa. La trappola analoga con le virgolette è trattata in [perché le virgolette curve rompono il codice](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "Qual è la differenza tra trattino lungo e trattino medio?", answer: "Il trattino medio (–, U+2013) significa da... a e indica intervalli come 2020–2024. Il trattino lungo (—, U+2014) isola una frase dentro un periodo, come una virgola più forte. Il trattino lungo è circa il doppio in larghezza, e sono due caratteri Unicode distinti." },
    { question: "Quando devo usare un trattino invece di un trattino medio o lungo?", answer: "Usa il trattino per unire parole in una singola unità: ben noto, ri-eleggere. Se intendi un intervallo, una connessione tra due parti o una pausa in una frase, ti serve invece un trattino medio o lungo." },
    { question: "I trattini lunghi vanno spaziati?", answer: "Dipende dal manuale di stile. Chicago, APA e MLA li usano senza spazi (parola—parola). Lo stile AP mette uno spazio da entrambi i lati (parola — parola). Gli stili editoriali britannici che seguono le New Hart's Rules usano invece il trattino medio spaziato (parola – parola). Sono tutte corrette; conta la coerenza all'interno dello stesso documento." },
    { question: "Come si digita un trattino lungo?", answer: "Su macOS premi Opzione + Maiusc + trattino. Su Windows tieni premuto Alt e digita 0151 sul tastierino numerico. In Word, digitando due trattini tra le parole la conversione avviene automaticamente; Google Docs non ha una scorciatoia integrata né una conversione predefinita, quindi usa Inserisci > Caratteri speciali oppure aggiungi una tua regola di sostituzione. Sui telefoni, tieni premuto il tasto del trattino." },
    { question: "È grave se uso un trattino al posto di un trattino medio?", answer: "In prosa è un'imprecisione minore che la maggior parte dei lettori non noterà. Nei dati, nel codice, negli URL o in qualsiasi cosa venga cercata o analizzata conta molto, perché i tre sono caratteri distinti e una corrispondenza esatta fallirà." },
  ],
};
