import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Esportare una conversazione ChatGPT in PDF o Word",
  description: "La stampa in PDF taglia la chat e perde la formattazione. Ecco come trasformare una conversazione in un documento PDF o Word pulito e leggibile.",
  h1: "Come esportare una conversazione ChatGPT in PDF o Word",
  dek: "Perché stampare la pagina non funziona e come ottenere un documento che invieresti davvero a qualcuno.",
  answer: "Stampare direttamente la pagina della chat di solito taglia i messaggi lunghi, elimina i blocchi di codice e porta con sé gli elementi dell'interfaccia nel file. Copiare la conversazione come testo, ristrutturarla in modo che ogni intervento diventi una sezione con etichetta e poi convertirla in PDF o DOCX produce un documento davvero leggibile e modificabile.",
  sections: {
    "why-printing-fails": {
      heading: "Perché stampare la pagina della chat non funziona",
      body: "Premere <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>P</kbd> sulla finestra della chat è la mossa più ovvia, e produce risultati deludenti per ragioni strutturali.\n\nLe interfacce di chat sono costruite come viste di un'applicazione a scorrimento, non come documenti. Da qui derivano errori di stampa prevedibili:\n\n- **I messaggi lunghi vengono tagliati.** Ogni messaggio sta nel proprio contenitore a scorrimento, quindi la stampa cattura solo la parte visibile.\n- **I blocchi di codice perdono il contenuto.** Il codice con scorrimento orizzontale viene troncato al bordo del contenitore, quindi la parte destra di ogni riga lunga sparisce semplicemente.\n- **Gli elementi dell'interfaccia vengono stampati.** Barre laterali, avatar, selettori del modello e pulsanti di rigenerazione finiscono tutti nella stampa.\n- **Le interruzioni di pagina cadono male.** Nulla indica al browser dove sia sensato interrompere, quindi i titoli restano orfani in fondo alle pagine.\n- **Esistono solo i messaggi caricati.** Le conversazioni lunghe sono virtualizzate, quindi i messaggi precedenti non ancora renderizzati sono del tutto assenti dalla stampa.\n\nIl risultato è un file che tecnicamente contiene la tua conversazione, ma che non allegheresti mai a un'email.",
    },
    "the-reliable-route": {
      heading: "Il percorso affidabile: copia, struttura, converti",
      body: "Tratta la conversazione come testo, non come pagina web.\n\n1. **Seleziona la conversazione e copiala.** Trascina la selezione dal primo all'ultimo messaggio. Otterrai il testo di entrambe le parti, di solito con la struttura Markdown intatta.\n2. **Ristrutturala in un documento.** Incolla in [Convertire conversazioni ChatGPT in documento](/chatgpt-conversation-to-document). Lo strumento rileva i turni dei parlanti e li ricostruisce come sezioni chiare ed etichettate, invece di un muro di testo indistinto.\n3. **Converti nel formato che ti serve.** Per un file condivisibile, [Convertire Markdown in PDF](/markdown-to-pdf) offre una vista pronta per la stampa da salvare direttamente in PDF. Per qualcosa di modificabile, [Convertire Markdown in Word](/markdown-to-word) produce un `.docx` con veri stili di titolo.\n\nIl risultato è un documento con un titolo, sezioni dei parlanti con intestazioni, blocchi di codice e tabelle conservati, e interruzioni di pagina che cadono nei punti giusti.",
    },
    "labelling-speakers": {
      heading: "Come sistemare le etichette dei parlanti",
      body: "L'unico aspetto che merita un momento di attenzione è come il testo copiato distingue chi ha detto cosa.\n\nA seconda dell'interfaccia e del browser, una conversazione copiata può arrivare con etichette esplicite oppure senza nulla che separi i turni. Se il tuo testo incollato non ha etichette, aggiungile prima di convertire: una riga contenente solo `You:` o `ChatGPT:` sopra ogni turno è sufficiente perché il convertitore trovi i confini.\n\nUn formato che funziona in modo affidabile:\n\n```\nYou:\nSummarize the Q2 results.\n\nChatGPT:\nRevenue rose 12% year over year, driven by...\n```\n\nPer conversazioni tecniche lunghe, vale la pena eliminare i vicoli ciechi esplorativi prima di convertire. Una trascrizione di quaranta scambi di cui solo sei contano non è più utile per il fatto di essere completa: è meno utile, perché il lettore deve andare a cercare quei sei. Esporta la conversazione che vorresti leggere.",
    },
    "practical-notes": {
      heading: "Note pratiche sul file finale",
      body: "**Impostazioni di pagina del PDF.** Quando salvi dalla finestra di stampa, attiva la grafica di sfondo se vuoi che i blocchi di codice mantengano l'ombreggiatura, e controlla che i margini non taglino le tabelle larghe. L'orientamento orizzontale è spesso la scelta giusta per una conversazione piena di dati.\n\n**Documenti Word e titoli.** Poiché il convertitore produce veri stili di titolo invece di testo in grassetto, il riquadro di spostamento di Word funziona e puoi inserire un sommario automatico. Questo è il principale vantaggio pratico rispetto a qualsiasi approccio di copia e incolla.\n\n**Codice lungo.** Il codice che scorreva orizzontalmente nella finestra della chat andrà a capo nel documento. Se le interruzioni di riga esatte contano — un file di configurazione, un comando di shell — controlla quei blocchi dopo la conversione.\n\n**Privacy.** Entrambi i convertitori funzionano interamente nel browser; nulla viene caricato. Questo conta più del solito qui, dato che le conversazioni spesso contengono contesto lavorativo, dettagli sui clienti o materiale non pubblicato. Se esiteresti a incollarlo in un sito sconosciuto, l'elaborazione locale è il motivo per cui questo approccio è sicuro.\n\n**Una nota sulle esportazioni ufficiali.** ChatGPT offre un'esportazione dei dati nelle impostazioni, che ti invia via email un file ZIP con la cronologia delle conversazioni. È completa e utile per l'archiviazione, ma è strutturata come dati grezzi anziché come documento leggibile, quindi per condividere una singola conversazione dovresti comunque convertirla.",
    },
  },
  faqs: [
    { question: "Come salvo una conversazione ChatGPT in PDF?", answer: "Copia la conversazione, ristrutturala con Convertire conversazioni ChatGPT in documento in modo che ogni turno diventi una sezione etichettata, poi usa Convertire Markdown in PDF e salva dalla finestra di stampa. In questo modo eviti i messaggi tagliati e i blocchi di codice mancanti che otterresti stampando la pagina della chat." },
    { question: "Perché stampando la pagina di ChatGPT i messaggi vengono tagliati?", answer: "I messaggi si trovano in contenitori a scorrimento propri e le conversazioni lunghe sono virtualizzate, quindi la stampa cattura solo ciò che è attualmente renderizzato e visibile. I blocchi di codice con scorrimento orizzontale vengono troncati al bordo del contenitore per lo stesso motivo." },
    { question: "Posso esportare una conversazione ChatGPT in Word?", answer: "Sì. Converti la conversazione copiata in un .docx con Convertire Markdown in Word. Poiché produce veri stili di titolo invece di testo in grassetto, il riquadro di spostamento funziona e puoi generare un sommario automatico." },
    { question: "ChatGPT ha un'esportazione integrata?", answer: "Nelle impostazioni c'è un'esportazione dei dati che ti invia via email un archivio della cronologia delle conversazioni. È ottima per il backup, ma è strutturata come dati grezzi anziché come documento leggibile, quindi la conversione resta la strada pratica per condividere una singola conversazione." },
    { question: "È sicuro incollare una conversazione privata in un convertitore?", answer: "Dipende interamente dallo strumento. I nostri elaborano il testo nel browser e non caricano nulla, ed è per questo che la conversazione resta sul tuo dispositivo. Qualsiasi strumento che invia il testo a un server va trattato come una pubblicazione, il che conta per materiale di lavoro o dei clienti." },
  ],
};
