import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Perché il testo IA incollato mostra ** e ## in Word",
  description: "Asterischi e cancelletti sono Markdown. Ecco perché Word li mostra letteralmente e i tre modi per incollare l’output IA con la formattazione intatta.",
  h1: "Perché il testo IA incollato mostra ** e ## in Word?",
  dek: "I simboli sono vere istruzioni di formattazione: Word semplicemente non sa come leggerle.",
  answer: "Quei simboli sono Markdown, un linguaggio di formattazione in testo semplice usato dai modelli di chat. Gli asterischi indicano il grassetto, i cancelletti i titoli e le barre verticali costruiscono le tabelle. Word non ha un parser Markdown, quindi li tratta come caratteri normali e li stampa letteralmente. Convertendo il testo prima di incollarlo, i simboli diventano vera formattazione.",
  sections: {
    "what-the-symbols-are": {
      heading: "Cosa significano davvero i simboli",
      body: "Markdown è una convenzione per descrivere la formattazione usando solo caratteri digitabili. È stato progettato affinché un documento resti leggibile anche quando nulla lo interpreta. I modelli di chat scrivono in Markdown perché è compatto, inequivocabile e viene visualizzato correttamente nell’interfaccia della chat.\n\nEcco tutto il vocabolario che probabilmente incontrerai:\n\n| Cosa vedi | Cosa significa |\n| --- | --- |\n| `**grassetto**` | Testo in grassetto |\n| `*corsivo*` o `_corsivo_` | Testo in corsivo |\n| `# Titolo` | Titolo di livello 1 (più cancelletti, titolo più piccolo) |\n| `- voce` o `* voce` | Voce di elenco puntato |\n| `1. voce` | Voce di elenco numerato |\n| Backtick attorno a `code` | Codice inline |\n| `> citazione` | Citazione in blocco |\n| `[testo](url)` | Collegamento ipertestuale |\n| `\\| a \\| b \\|` | Riga di tabella |\n\nNulla è rotto e nulla si è corrotto nel passaggio. Stai guardando istruzioni formate correttamente che sono finite in un posto senza interprete.",
    },
    "why-word-cannot-read-it": {
      heading: "Perché Word non riesce a leggerlo",
      body: "Word memorizza la formattazione come dati strutturati all’interno del documento. Il grassetto è un attributo associato a una sequenza di caratteri, non una coppia di asterischi che la circonda. Quando incolli testo semplice, Word prende ogni carattere alla lettera, perché dal suo punto di vista un asterisco è un segno di punteggiatura che qualcuno ha digitato deliberatamente.\n\nEcco perché le solite scappatoie deludono:\n\n- **Incolla speciale → Testo formattato** non serve, perché negli appunti non c’era alcuna formattazione da conservare. Gli appunti contenevano caratteri semplici.\n- **Trova e sostituisci** rimuove gli asterischi ma lascia il testo senza grassetto, quindi perdi del tutto la struttura invece di ottenerla.\n- **Formattazione automatica** gestisce alcuni schemi come i caratteri degli elenchi puntati, ma non è un parser Markdown e non toccherà `**grassetto**` o `## Titolo`.\n\nGoogle Docs si comporta allo stesso modo per la stessa ragione. Notion, Obsidian e la maggior parte degli editor per sviluppatori *interpretano* il Markdown: ecco perché lì lo stesso incolla funziona correttamente, creando l’impressione che sia Word a fare qualcosa di sbagliato.",
    },
    "three-ways-to-fix": {
      heading: "Tre modi per ottenere testo formattato correttamente",
      body: "Quale scegliere dipende dal fatto che ti serva la formattazione o che tu voglia semplicemente eliminarla.\n\n**1. Convertire in un documento Word.** L’opzione più completa. [Convertire Markdown in Word](/markdown-to-word) trasforma la risposta in un vero `.docx` con stili di titolo autentici, grassetto, elenchi e tabelle: il tipo di elementi che il riquadro di spostamento e l’indice di Word sanno riconoscere davvero. Usalo quando l’output diventerà un report o qualsiasi cosa che altri dovranno modificare.\n\n**2. Convertire in testo formattato e incollare.** [Convertire Markdown in Google Docs](/markdown-to-google-docs) produce testo formattato che puoi copiare direttamente in Google Docs, Word, Outlook o qualsiasi editor che accetti HTML incollato. Usalo quando stai inserendo una sezione in un documento già esistente.\n\n**3. Eliminare del tutto i simboli.** A volte vuoi solo prosa pulita senza alcuna formattazione: per un’email, un campo di un modulo, una casella di un CMS o un messaggio in chat. [Rimuovere la formattazione Markdown](/remove-markdown-formatting) cancella i caratteri della sintassi lasciando ogni parola intatta, cosa che trova e sostituisci non riesce a fare in sicurezza.\n\nTutti e tre funzionano nel browser. Nulla viene caricato.",
    },
    "stopping-it-at-the-source": {
      heading: "Evitare il problema alla fonte",
      body: "Puoi anche chiedere al modello di non usare Markdown fin dall’inizio. Un prompt come *«rispondi in prosa semplice senza formattazione Markdown, senza asterischi, senza cancelletti e senza elenchi puntati»* funziona abbastanza bene per risposte brevi.\n\nÈ meno affidabile di quanto sembri. La conformità tende a indebolirsi nel corso di una risposta lunga, e i contenuti strutturati — qualsiasi cosa con passaggi, confronti o dati — riporteranno il modello verso elenchi e tabelle, perché è davvero il modo più chiaro di presentarli. Se la tua risposta contiene una tabella, quasi sicuramente vuoi quella tabella; la vuoi solo come tabella vera.\n\nPer qualsiasi contenuto lungo o strutturato, convertire dopo è l’abitudine più affidabile. In più, così mantieni la versione leggibile nella finestra della chat e ne ottieni una formattata correttamente nel documento.\n\nSe il problema specifico con cui stai combattendo è una tabella anziché la prosa, quello ha le sue particolarità: vedi [come incollare una tabella di ChatGPT in Excel](/guides/paste-chatgpt-table-into-excel).",
    },
  },
  faqs: [
    { question: "Perché il testo di ChatGPT mostra asterischi quando lo incollo in Word?", answer: "Gli asterischi sono sintassi Markdown che indica grassetto e corsivo. Word non ha un parser Markdown, quindi li tratta come caratteri normali e li mostra letteralmente. Convertendo prima il Markdown in un documento Word o in testo formattato, diventano vera formattazione." },
    { question: "Come incollo l’output di ChatGPT in Word con la formattazione?", answer: "Convertilo prima. Convertire Markdown in Word produce un .docx con veri stili di titolo, grassetto, elenchi e tabelle; Convertire Markdown in Google Docs produce testo formattato che puoi incollare direttamente in un documento esistente. Incollando la risposta grezza vedrai sempre i caratteri della sintassi." },
    { question: "Incolla speciale risolve i simboli Markdown?", answer: "No. Incolla speciale conserva la formattazione già presente negli appunti, e il Markdown in testo semplice non ne ha: la formattazione è codificata come caratteri, non come attributi. Non c’è nulla che Incolla speciale possa mantenere." },
    { question: "Cosa significa ## nel testo generato dall’IA?", answer: "Indica un titolo. Un cancelletto è un titolo di primo livello, due un titolo di secondo livello, e così via fino a sei. In un editor compatibile con Markdown i cancelletti scompaiono e la riga viene visualizzata come titolo formattato." },
    { question: "Posso semplicemente trovare e sostituire gli asterischi?", answer: "Puoi, ma eliminerai la formattazione invece di applicarla: il testo smette di essere in grassetto e perde semplicemente i segnaposto. Rimuovere il Markdown in sicurezza significa anche gestire titoli, marcatori di elenco, link e blocchi di codice, cosa che uno strumento dedicato fa in un solo passaggio." },
  ],
};
