import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Come incollare una tabella ChatGPT in Excel",
  description: "Le tabelle IA si incollano in una sola colonna perché sono testo semplice, non celle. Ecco come ottenere righe e colonne vere in Excel, Sheets o Numbers.",
  h1: "Come incollare una tabella ChatGPT in Excel o Google Sheets",
  dek: "Perché l’intera tabella finisce nella colonna A e i due modi affidabili per risolvere.",
  answer: "Una tabella ChatGPT è una tabella Markdown con barre verticali: testo semplice che usa il carattere | per suggerire le colonne. I fogli di calcolo si aspettano confini di cella, non barre, quindi ogni riga finisce in un’unica colonna. Convertire prima la tabella in XLSX o CSV produce righe e colonne vere che si aprono correttamente in Excel, Sheets e Numbers.",
  sections: {
    "why-it-lands-in-one-column": {
      heading: "Perché l’intera tabella finisce nella colonna A",
      body: "Quello che la finestra della chat ti mostra è una tabella già renderizzata. Quello che gli appunti ricevono è di solito questo:\n\n```\n| Region | Q1 | Q2 |\n| --- | ---: | ---: |\n| Europe | 412 | 486 |\n| Asia | 377 | 381 |\n```\n\nÈ una tabella Markdown con barre verticali. Le barre sono caratteri normali che *sembrano* divisori di colonna a chi legge. La seconda riga, con i suoi trattini e due punti, indica a un renderer Markdown dove finisce l’intestazione e come allineare ogni colonna.\n\nExcel divide il testo incollato in base ai caratteri di tabulazione, non alle barre. Poiché non ci sono tabulazioni, ogni riga è un valore singolo e l’intera tabella si impila nella colonna A con le barre ancora visibili. Google Sheets e Numbers si comportano allo stesso modo.\n\nLa riga di allineamento è la prova che non si è mai trattato di dati da foglio di calcolo. Nessuna esportazione da un foglio contiene una riga di trattini e due punti.",
    },
    "the-fastest-fix": {
      heading: "La soluzione più veloce: convertire prima di incollare",
      body: "Invece di incollare e poi riparare, converti la tabella in un formato che i fogli di calcolo già comprendono.\n\n**Per Excel e Numbers**, [Convertire tabella Markdown in Excel](/markdown-table-to-excel) produce un vero file `.xlsx`. Incolla la tabella, scarica il foglio, aprilo. I numeri restano numeri, la riga di intestazione resta un’intestazione e non c’è nulla da dividere dopo.\n\n**Per Google Sheets**, [Convertire tabella Markdown in CSV](/markdown-table-to-csv) è di solito più pratico. Il CSV si importa nativamente tramite *File → Importa* ed eviti il giro di scaricamento e caricamento che l’XLSX richiede nel browser. Il convertitore gestisce correttamente virgolette e virgole incorporate, che è esattamente dove le conversioni fatte a mano falliscono.\n\nEntrambi gli strumenti funzionano localmente nel browser, quindi i dati non lasciano mai il tuo dispositivo: un dettaglio da non sottovalutare se la tabella contiene qualcosa che non incolleresti su un sito qualunque.",
    },
    "manual-methods": {
      heading: "I metodi manuali e quando vale la pena usarli",
      body: "Se preferisci non uscire dal foglio di calcolo, ci sono due strade integrate.\n\n**Testo in colonne (Excel).** Incolla la tabella grezza nella colonna A, selezionala, poi *Dati → Testo in colonne → Delimitato* e imposta come delimitatore la barra verticale. Dovrai comunque eliminare la riga di allineamento e rimuovere le colonne vuote create dalle barre iniziali e finali.\n\n**SPLIT (Google Sheets).** Con la tabella grezza nella colonna A, usa `=SPLIT(A1, \"|\")` e trascina verso il basso, poi copia e incolla come valori. Vale la stessa pulizia di prima.\n\nVanno bene per una singola tabella piccola. Diventano presto noiosi, ed entrambi lasciano spazi di riempimento dentro ogni cella: gli spazi che Markdown usa per la leggibilità diventano parte del valore, quindi ` Europe ` non corrisponderà a `Europe` in una formula di ricerca. Questo problema degli spazi finali è la causa più comune di una tabella convertita che sembra giusta ma si comporta male.\n\n**Una nota sul copia:** se selezioni trascinando la tabella *renderizzata* nella finestra della chat invece di usare il pulsante di copia, alcuni browser mettono negli appunti testo separato da tabulazioni, che si incolla correttamente nelle colonne. Il comportamento però varia tra browser e interfacce di chat, quindi vale la pena provarlo ma non farci affidamento.",
    },
    "tables-buried-in-prose": {
      heading: "Quando la tabella è sepolta in una risposta più lunga",
      body: "Spesso la tabella che ti serve è solo una parte di una risposta molto più lunga, mescolata con spiegazioni prima e dopo.\n\n[Estrarre tabelle dal testo](/extract-table-from-text) trova le righe simili a tabelle dentro il testo circostante — delimitate da barre o da tabulazioni — e restituisce solo la tabella in CSV. Incolla l’intera risposta ed estrai i dati, invece di selezionare le righe a mano sperando di aver colto i confini giusti.\n\nDue cose da controllare su qualsiasi tabella convertita prima di costruirci sopra:\n\n- **Numeri memorizzati come testo.** Se una colonna arriva allineata a sinistra in Excel, i valori sono testo. La causa abituale sono simboli di valuta, separatori delle migliaia e segni di percentuale nell’originale. Seleziona la colonna e usa *Dati → Testo in colonne → Fine* per convertirli.\n- **Celle unite o con ritorni a capo.** Le tabelle Markdown non possono esprimere celle unite, quindi un modello che presenta dati complessi a volte le simula con valori ripetuti o interruzioni di riga dentro una cella. Questi casi richiedono una decisione umana, non un convertitore.\n\nSe anche il resto della risposta deve viaggiare — titoli, elenchi, la spiegazione intorno alla tabella — leggi [perché il testo IA incollato mostra ** e ##](/guides/markdown-symbols-in-word).",
    },
  },
  faqs: [
    { question: "Perché una tabella ChatGPT si incolla in una sola colonna in Excel?", answer: "Perché è una tabella Markdown con barre verticali, cioè testo semplice che usa il carattere | come divisore visivo. Excel divide il testo incollato in base alle tabulazioni, non alle barre, quindi ogni riga viene trattata come un unico valore e l’intera tabella si impila in una sola colonna." },
    { question: "Come converto una tabella Markdown in Excel?", answer: "Incollala in Convertire tabella Markdown in Excel e scarica il file .xlsx risultante. Produce righe e colonne vere con l’intestazione preservata, quindi non c’è nulla da dividere o pulire dopo l’apertura." },
    { question: "Cos’è la riga di trattini e due punti in una tabella IA?", answer: "È la riga di allineamento Markdown. Separa l’intestazione dal corpo e imposta l’allineamento delle colonne: i due punti a destra indicano allineamento a destra, su entrambi i lati il testo centrato. È sintassi di formattazione, non dati, e va rimossa durante la conversione." },
    { question: "Perché le mie celle convertite hanno spazi extra?", answer: "Markdown riempie le celle di spazi per la leggibilità, e la divisione manuale mantiene quel riempimento dentro il valore. Conta perché ' Europe ' non corrisponde a 'Europe' in una ricerca. Un buon convertitore elimina il riempimento; se dividi a mano, racchiudi i risultati in ANNULLA.SPAZI." },
    { question: "Posso incollare una tabella IA direttamente in Google Sheets?", answer: "Non con le colonne intatte. Convertire prima in CSV e importare tramite File → Importa è la strada più affidabile, perché il CSV è un formato che Sheets interpreta nativamente ed evita il giro di scaricamento e caricamento dell’XLSX." },
  ],
};
