import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Quanti token ha il mio prompt?",
  description: "I token sono frammenti di parole, non parole. Come funziona la tokenizzazione, perché i conteggi variano tra modelli e come stimare i costi.",
  h1: "Quanti token ha il mio prompt?",
  dek: "Perché 1.000 parole non sono mai 1.000 token, e cosa significa per i limiti di contesto e i costi.",
  answer: "I token sono frammenti di parole, quindi i conteggi non coincidono mai con il numero di parole. Per l’inglese comune, un token corrisponde in media a circa quattro caratteri o tre quarti di parola: 1.000 parole equivalgono a circa 1.300 token. Il codice, le scritture non inglesi e le parole insolite consumano più token per carattere, a volte molte volte di più.",
  sections: {
    "what-a-token-is": {
      heading: "Che cos’è davvero un token",
      body: "I modelli linguistici non leggono caratteri né parole. Leggono token: frammenti prodotti suddividendo il testo secondo un vocabolario fisso appreso dai dati di addestramento.\n\nLe parole comuni sono di solito un singolo token. Le parole rare vengono spezzate in più pezzi. Gli spazi vengono in genere attaccati all’inizio del token successivo: ecco perché la stessa parola può contare in modo diverso a seconda che apra o meno una frase.\n\nLa parola *unbelievable* non è un solo token: probabilmente viene divisa in qualcosa come `Un` + `believ` + `able`. Invece *the* è un singolo token, e lo è anche *international*, perché è comparsa abbastanza spesso nell’addestramento da meritare una voce propria.\n\nÈ per questo che i conteggi dei token sembrano imprevedibili. L’unità non è linguistica, è statistica. È la frequenza nel corpus di addestramento a determinare se qualcosa vale un token o quattro.",
    },
    "rules-of-thumb": {
      heading: "Regole pratiche che funzionano davvero",
      body: "Per la prosa in inglese:\n\n- **1 token ≈ 4 caratteri**\n- **1 token ≈ 0,75 parole**\n- **1.000 parole ≈ 1.300 token**\n- **Una pagina standard (~500 parole) ≈ 650 token**\n\nQueste stime crollano rapidamente fuori dalla prosa ordinaria:\n\n| Tipo di contenuto | Approssimativamente |\n| --- | --- |\n| Prosa in inglese | 0,75 parole per token |\n| Codice | 2–3 volte più token rispetto alla prosa equivalente |\n| JSON con chiavi lunghe | Molto alto: punteggiatura e virgolette sono token separati |\n| Cinese, giapponese, coreano | Spesso 1–2 token *per carattere* |\n| Cirillico, Devanagari, arabo | In genere 2–3 volte l’inglese a parità di significato |\n| URL e hash | Altissimo: le stringhe casuali si tokenizzano male |\n| Spaziature ripetute | Ogni sequenza può essere un token a sé |\n\nIl divario multilingue è notevole e sottovalutato: la stessa frase in giapponese può costare diverse volte quanto costa in inglese, con effetti sia sui costi sia su quanto entra nella finestra di contesto.",
    },
    "why-models-differ": {
      heading: "Perché il conteggio cambia tra i modelli",
      body: "Ogni famiglia di modelli usa il proprio tokenizer con il proprio vocabolario, quindi lo stesso testo produce conteggi diversi.\n\nI modelli GPT usano varianti del byte-pair encoding: `cl100k_base` per i modelli dell’era GPT-4, `o200k_base` per quelli più recenti. Claude usa un tokenizer diverso, con un vocabolario diverso. I modelli aperti come Llama e Mistral ne hanno ciascuno uno proprio.\n\nDifferenze del 10–20% tra famiglie sullo stesso testo inglese sono normali, e il divario si allarga su codice e testi non inglesi, dove i vocabolari divergono di più.\n\nIn pratica questo significa:\n\n- Un conteggio fatto con un tokenizer è una **stima** per qualsiasi altro modello.\n- Solo il tokenizer del fornitore dà un numero esatto per la sua fatturazione.\n- Pianifica il budget con un margine, invece di aderire esattamente al limite.\n\nIl nostro [Contatore di token](/token-counter) mostra fianco a fianco un conteggio GPT-4o e una stima Claude, che di solito basta per capire se un prompt è comodamente dentro il limite o pericolosamente vicino.",
    },
    "why-it-matters": {
      heading: "Perché il numero conta",
      body: "**Costo.** I prezzi delle API sono per token, con input e output tariffati separatamente; l’output costa in genere molte volte di più. Raddoppiare un system prompt raddoppia quel costo a ogni singola chiamata: il genere di cosa invisibile nei test e costosa su larga scala.\n\n**Limiti di contesto.** La finestra copre *tutto*: system prompt, cronologia della conversazione, documenti recuperati, il messaggio corrente e lo spazio riservato alla risposta. Le chat lunghe falliscono non perché un messaggio sia lungo, ma perché la cronologia si accumula.\n\n**Troncamento.** Quando l’input supera il limite, qualcosa viene eliminato: spesso in silenzio, e spesso i contenuti più vecchi. Un modello che ha «dimenticato» le tue istruzioni molto spesso le ha semplicemente viste troncate.\n\n**Suddivisione per il retrieval.** Spezzare i documenti per l’embedding funziona a token, non a caratteri. Blocchi dimensionati per numero di caratteri risultano incoerenti, e blocchi tagliati a metà frase si recuperano male. Per dividere testi lunghi in pezzi gestibili, [Suddividi testo](/text-splitter) taglia vicino ai confini dei paragrafi invece che a metà parola.",
    },
    "reducing-tokens": {
      heading: "Ridurre il conteggio senza perdere significato",
      body: "Le riduzioni più efficaci, approssimativamente in ordine:\n\n1. **Riduci la cronologia della conversazione.** In una chat lunga supera di gran lunga tutto il resto. Riassumi i turni vecchi invece di reinviarli parola per parola.\n2. **Elimina le istruzioni ridondanti.** Ripetere una regola in tre modi non la rende tre volte più probabile da seguire. Triplica però in modo affidabile il costo di quella regola.\n3. **Rimuovi gli artefatti di formattazione.** Caratteri invisibili, spaziature ripetute e righe decorative di separazione vengono tutti tokenizzati, e una fila di quaranta trattini può costare più della frase che la precede. [Rimuovere caratteri invisibili](/remove-invisible-characters) elimina quelli che non si vedono.\n4. **Accorcia le chiavi JSON** nei prompt strutturati. `{\"n\": ...}` contro `{\"customer_full_name\": ...}`, moltiplicato su mille record, fa una grande differenza.\n5. **Invia solo gli estratti pertinenti.** Recuperare tre paragrafi rilevanti batte incollare un intero documento, e di solito produce anche risposte migliori oltre che più economiche.\n\nCosa *non* aiuta: rimuovere la normale punteggiatura, cancellare gli articoli o scrivere in stile telegrafico. Il risparmio è marginale e il danno alla qualità dell’output no.",
    },
  },
  faqs: [
    { question: "Quanti token sono 1.000 parole?", answer: "Circa 1.300 token per la prosa comune in inglese, sulla base di circa 0,75 parole per token. Codice, JSON e testi non inglesi vanno molto più in alto: cinese, giapponese e coreano usano spesso da uno a due token per carattere." },
    { question: "Perché il conteggio dei token è diverso per GPT e Claude?", answer: "Ogni famiglia di modelli usa il proprio tokenizer con un vocabolario appreso diverso, quindi lo stesso testo viene diviso in modo diverso. Differenze del 10–20% sulla prosa inglese sono normali, e il divario si allarga su codice e testi non inglesi." },
    { question: "Che cos’è un token in un modello IA?", answer: "Un frammento di testo tratto dal vocabolario fisso del modello. Le parole comuni sono di solito un singolo token, mentre quelle rare si spezzano in più pezzi: «unbelievable» può diventare tre token mentre «international» ne resta uno solo." },
    { question: "Spazi e punteggiatura contano come token?", answer: "Sì. Gli spazi vengono normalmente attaccati all’inizio del token successivo e la punteggiatura è spesso un token a sé. Lunghe sequenze di spaziature ripetute o righe decorative possono consumare un numero sorprendente di token." },
    { question: "Come posso ridurre l’uso dei token?", answer: "Per prima cosa riduci la cronologia accumulata della conversazione: nelle chat lunghe domina tutto il resto. Poi elimina le istruzioni duplicate, rimuovi caratteri invisibili e spaziature ripetute, accorcia le chiavi JSON e invia solo l’estratto pertinente di un documento invece dell’intero testo." },
  ],
};
