import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "7 segnali che un testo è stato scritto dall’IA",
  description: "I sette schemi di formattazione e stile tipici dei testi generati dall’IA, come verificarli e perché nessuno di essi è una prova da solo.",
  h1: "Sette segnali che un testo è stato scritto dall’IA",
  dek: "Quattro si possono misurare, tre si possono solo notare — e i limiti onesti di entrambi.",
  answer: "I segnali più affidabili sono meccanici: trattini lunghi a ritmo costante, virgolette curve tipografiche, caratteri Unicode invisibili ed elenchi puntati aperti da emoji. I segnali stilistici — lessico prudente, la costruzione «non solo X, ma Y» e paragrafi di lunghezza insolitamente uniforme — sono più deboli. Nessuno di essi dimostra qualcosa da solo: sono schemi, non prove.",
  sections: {
    "mechanical-signs": {
      heading: "I quattro segnali meccanici che si possono davvero misurare",
      body: "Sono elementi contabili. Puoi passarli a uno strumento e ottenere un numero invece di un’impressione, ed è questo che li rende più utili di un’analisi basata sulle sensazioni.\n\n**1. Trattini lunghi a ritmo costante.** I modelli conversazionali producono il trattino lungo (—) con molta più regolarità delle persone, perché digitarlo richiede una scorciatoia da tastiera che la maggior parte di chi scrive non ha mai imparato. Uno o due in un documento lungo sono normali. Circa uno per paragrafo, distribuiti in modo uniforme, non lo è. La [guida ai trattini lunghi](/guides/why-chatgpt-uses-em-dashes) spiega perché questa abitudine è così radicata.\n\n**2. Virgolette curve e punteggiatura tipografica.** L’output dell’IA tende ad arrivare con virgolette direzionali (“ ”), apostrofi curvi (’) e il carattere di ellissi (…) invece di tre punti. Anche i word processor li producono automaticamente, quindi sono significativi solo in contesti in cui la correzione automatica non è mai entrata in gioco: un campo di testo semplice, un commento nel codice, un file CSV.\n\n**3. Caratteri Unicode invisibili.** Spazi a larghezza zero, spazi unificatori e spazi unificatori stretti sopravvivono spesso a un copia-incolla da una finestra di chat. Sono impercettibili a occhio nudo e sono il più forte marcatore meccanico in assoluto, perché quasi nulla di ciò che una persona digita a mano li introduce.\n\n**4. Elenchi puntati aperti da emoji.** Risposte strutturate con un’emoji decorativa all’inizio di ogni punto, titoli di sezione costruiti con il grassetto invece di veri titoli ed elenchi annidati su tre livelli sono uno stile che le interfacce di chat incoraggiano e che la maggior parte di chi scrive a mano non usa.",
    },
    "stylistic-signs": {
      heading: "I tre segnali stilistici — più deboli, ma utili da conoscere",
      body: "Gli schemi a livello stilistico si prestano molto più facilmente a errori, perché molti testi umani accurati li condividono. Considerali uno spunto per guardare più da vicino, mai una conclusione.\n\n**5. Impostazione prudente ed equilibrata.** Frasi che presentano ogni questione come se avesse due facce ragionevoli, paragrafi che si aprono riformulando la domanda e chiusure che riassumono senza aggiungere nulla. Deriva da un addestramento che premia l’essere utili e non schierati allo stesso tempo.\n\n**6. La costruzione «non solo X, ma Y».** Insieme a «vale la pena notare che», «approfondire», «navigare le complessità di» e «nel mondo frenetico di oggi». Queste frasi non sono parole proibite: sono inglese (e italiano) ordinario. Ciò che colpisce è quanto spesso si concentrano insieme in un unico testo breve.\n\n**7. Struttura insolitamente uniforme.** Paragrafi di lunghezza quasi identica, sezioni con un numero sospettosamente uguale di punti elenco e una conclusione che rispecchia l’introduzione. Le bozze umane sono più irregolari: un paragrafo si allunga perché chi scriveva aveva più cose da dire proprio su quel punto.\n\nI segnali lessicali in particolare si esauriscono in fretta. Ogni elenco di «parole dell’IA» che circola viene assorbito nel modo in cui le persone scrivono e nel modo in cui viene regolata la generazione successiva di modelli. I segnali meccanici sono più duraturi perché sono sottoprodotti della codifica, non dello stile.",
    },
    "how-to-check": {
      heading: "Come controllare un documento in un’unica passata",
      body: "Un ordine pratico delle operazioni, dal controllo più economico in poi:\n\n1. **Cerca i caratteri invisibili.** È il controllo con il miglior rapporto tra segnale e sforzo. Incolla il testo nello [strumento per rimuovere i caratteri invisibili](/remove-invisible-characters): elenca ogni spazio a larghezza zero, trattino morbido, byte-order mark e segno direzionale trovato, con i conteggi.\n2. **Conta gli artefatti meccanici tutti insieme.** Lo strumento per [pulire il testo IA](/clean-ai-text) segnala trattini lunghi, virgolette curve, caratteri invisibili ed emoji in un’unica passata, così puoi vedere se più segnali compaiono insieme invece di inseguirli uno alla volta.\n3. **Leggi alla ricerca degli schemi stilistici.** Solo dopo aver ottenuto i conteggi. Partire dai numeri ti impedisce di convincerti da solo di una conclusione.\n4. **Valuta il contesto.** Un testo incollato da Word avrà le virgolette curve indipendentemente da chi l’ha scritto. Un testo digitato in una semplice textarea no.\n\nCiò che conta è la co-occorrenza. Un singolo trattino lungo non significa nulla. Trattini lunghi *e* virgolette curve *e* due spazi a larghezza zero *e* elenchi con emoji, in un documento digitato direttamente in un modulo di testo semplice, sono una combinazione davvero insolita.",
    },
    "why-not-proof": {
      heading: "Perché niente di tutto questo è una prova",
      body: "Ogni segnale elencato sopra ha una spiegazione innocente.\n\nWord e Google Docs convertono automaticamente i doppi trattini in trattini lunghi e le virgolette dritte in virgolette curve. Copiare da qualsiasi sito moderno può portare con sé caratteri invisibili. I redattori professionisti scrivono esattamente in quel registro equilibrato e prudente che sembra generato da una macchina. Chi scrive in una lingua che non è la propria usa spesso uno stile più formale e strutturalmente regolare, ed è proprio per questo che i rilevatori IA commerciali segnalano i suoi testi con frequenza nettamente maggiore.\n\nC’è poi una circolarità evidente: una persona può incollare l’output dell’IA in un editor, fare una passata di pulizia e rimuovere ogni segnale meccanico in circa dieci secondi. I segnali più facili da misurare sono anche i più facili da cancellare.\n\nQuindi la posizione onesta è questa. L’analisi della formattazione ti dice **quali caratteri ci sono in un documento**. Non può dirti chi ce li ha messi. I nostri strumenti riportano deliberatamente solo conteggi e non emettono mai un verdetto, perché un verdetto sarebbe un’ipotesi travestita da numero. Se devi sapere se una persona ha scritto qualcosa, la risposta viene dal parlarne con lei — cronologia delle bozze, fonti e capacità di spiegare il proprio ragionamento — non dal contare i trattini.",
    },
  },
  faqs: [
    { question: "Qual è il segnale più affidabile che un testo è stato scritto dall’IA?", answer: "I caratteri Unicode invisibili, come gli spazi a larghezza zero, sono il marcatore meccanico più forte, perché la digitazione normale non li produce quasi mai, mentre un copia-incolla da una finestra di chat spesso sì. Detto questo, possono arrivare anche copiando testo da un sito web, quindi indicano la provenienza dell’incolla, non la paternità del testo." },
    { question: "I rilevatori di testo IA funzionano davvero?", answer: "Non in modo affidabile. Producono falsi positivi su testi umani — colpendo in modo sproporzionato chi non scrive nella propria lingua madre — e possono essere aggirati con modifiche leggere. L’analisi della formattazione può contare artefatti concreti, ma nessuno strumento, compresi i nostri, può stabilire la paternità di un testo basandosi solo sul testo." },
    { question: "Usare trattini lunghi o virgolette curve significa che verrò accusato di usare l’IA?", answer: "Non dovrebbe, ed è una pessima base per un’accusa. Word e Google Docs li generano entrambi automaticamente durante la normale digitazione. Se ti preoccupa come appare un documento, convertire la punteggiatura in ASCII semplice rimuove gli artefatti senza cambiare una sola parola di ciò che hai scritto." },
    { question: "Posso rimuovere questi segnali da un testo generato dall’IA?", answer: "Sì, e in fretta — ed è esattamente il motivo per cui sono prove deboli. Sostituire i trattini lunghi, normalizzare le virgolette ed eliminare i caratteri invisibili richiede pochi secondi. È un motivo per essere scettici sulle promesse di rilevamento, non una tecnica per spacciare come proprio il lavoro altrui." },
  ],
};
