import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Perché ChatGPT usa così tanti trattini lunghi?",
  description: "ChatGPT usa i trattini lunghi perché ha imparato dalla prosa editata. Ecco perché l'abitudine è così costante e come rimuoverli in modo pulito.",
  h1: "Perché ChatGPT usa così tanti trattini lunghi?",
  dek: "Il segno di punteggiatura diventato una firma dell'IA, e cosa fare al riguardo.",
  answer: "ChatGPT usa i trattini lunghi perché è stato addestrato su prosa editata professionalmente — libri, saggi e giornalismo — dove il trattino lungo è lo standard per incastonare una frase. Il modello riproduce questa abitudine in modo molto più costante degli scrittori umani occasionali, che raramente digitano quel carattere. È questa differenza di costanza, non il segno in sé, a farlo percepire come una firma dell'IA.",
  sections: {
    "where-it-comes-from": {
      heading: "Da dove viene questa abitudine",
      body: "I grandi modelli linguistici imparano la punteggiatura come imparano tutto il resto: assorbendo schemi dai dati di addestramento. Quei dati sono fortemente orientati verso **testi pubblicati ed editati professionalmente** — libri, giornalismo long-form, saggi e documentazione. In quel mondo il trattino lungo è del tutto ordinario. I correttori di bozze lo usano continuamente per incastonare un inciso, introdurre una sintesi o creare una pausa prima di una frase conclusiva.\n\nLa scrittura informale di internet è tutt'altra cosa. Nei messaggi di chat, nei post dei forum e nelle email, le persone usano virgole, parentesi e punti. La maggior parte non digita mai un trattino lungo, perché su una tastiera standard non esiste un tasto dedicato.\n\nC'è una seconda pressione che si aggiunge ai dati di addestramento. I modelli vengono ottimizzati per produrre una prosa che i lettori giudicano chiara e ben scritta, e il trattino lungo è insolitamente bravo in questo compito. È il segno più flessibile della punteggiatura inglese — può sostituire una virgola, i due punti, un punto e virgola o una coppia di parentesi. Quando una frase potrebbe accettare diversi segni, scegliere il trattino lungo è sempre difendibile. Un sistema ottimizzato per un testo fluente e sicuro di sé ci ricadrà più e più volte.",
    },
    "why-it-reads-as-ai": {
      heading: "Perché il trattino lungo è diventato un segnale dell'IA",
      body: "Il trattino lungo non è diventato sospetto perché è raro. È diventato sospetto per **la costanza con cui appare**.\n\nDigitarne uno richiede uno sforzo deliberato. Su un Mac è <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>; su Windows è <kbd>Alt</kbd> + <kbd>0151</kbd> o una regola di correzione automatica. La maggior parte delle tastiere dei telefoni lo nasconde dietro una pressione prolungata. Quindi quando un essere umano scrive un trattino lungo, di solito è una scelta stilistica consapevole, e compare in modo sporadico — poche volte in un documento lungo, concentrato dove lo scrittore voleva una pausa drammatica.\n\nUn modello linguistico non ha questo attrito. Ogni carattere costa uguale. Il risultato è un'impronta statistica riconoscibile:\n\n- I trattini lunghi compaiono a un ritmo costante in ogni paragrafo, invece che a grappoli.\n- Sono spesso usati **in coppia**, a racchiudere una frase incidentale, dove la maggior parte delle persone userebbe le virgole.\n- Compaiono in contesti che normalmente non li ospiterebbero, come una risposta breve, una voce di elenco puntato o una segnalazione di bug.\n\nNessuno di questi schemi è sbagliato. Sono semplicemente più regolari di quanto tenda a essere la scrittura umana, e la regolarità è esattamente ciò che i lettori notano.",
    },
    "how-to-remove": {
      heading: "Come rimuovere i trattini lunghi senza rompere le frasi",
      body: "L'errore è sostituire ogni trattino lungo con un trattino semplice. Il trattino semplice è un carattere diverso con una funzione diversa, e il risultato sembra un refuso invece che prosa pulita. Adatta la sostituzione al lavoro che il trattino stava facendo.\n\n**Una coppia di trattini lunghi che racchiude un inciso** diventa di solito una coppia di virgole. Se l'inciso è una vera digressione, le parentesi funzionano meglio.\n\n**Un trattino lungo singolo prima di una conclusione** sta sostituendo i due punti. Scambialo con quelli, oppure chiudi la frase e iniziane una nuova.\n\n**Un trattino lungo singolo a metà frase** segna spesso una rottura più netta di quanto la frase richieda davvero. Spezzarla in due frasi quasi sempre funziona meglio di qualsiasi segno sostitutivo.\n\n| Cosa sta facendo il trattino | Sostituto migliore |\n| --- | --- |\n| Racchiude un inciso leggero | Virgole |\n| Racchiude una digressione | Parentesi |\n| Introduce una sintesi | Due punti |\n| Segna una rottura netta | Punto, dividi la frase |\n| Indica un intervallo (2020—2024) | Trattino medio, non lungo |\n\nSe stai lavorando su un documento lungo, lo strumento [Rimuovere i trattini lunghi](/remove-em-dashes) sostituisce ogni trattino lungo con il sostituto che scegli e indica quanti ne ha modificati, così puoi verificare il conteggio con la tua lettura invece di fidarti di un trova-e-sostituisci silenzioso.",
    },
    "when-to-keep": {
      heading: "Quando conviene tenere il trattino lungo",
      body: "Eliminare ogni trattino lungo dai tuoi testi è una correzione eccessiva. Il segno esiste perché fa qualcosa che le alternative non fanno: crea una pausa con più forza di una virgola e meno definitività di un punto, senza la sensazione burocratica del punto e virgola.\n\nTienilo quando:\n\n- La frase ha davvero bisogno di un'interruzione netta, e una virgola sarebbe troppo morbida.\n- Stai citando una fonte che lo ha usato. Modificare la punteggiatura dentro una citazione altera la citazione.\n- Lo stile della casa editrice lo prevede. La maggior parte degli editori di libri e molte redazioni usano liberamente i trattini lunghi.\n- Stai scrivendo narrativa o saggi personali, dove il ritmo conta più dell'apparire neutrale rispetto alle macchine.\n\nL'obiettivo realistico non è zero trattini lunghi. È avere trattini lunghi che compaiono perché li hai scelti, a un ritmo che riflette la tua voce. Uno o due in un articolo lungo sembrano deliberati. Uno in ogni paragrafo sembra un'impostazione predefinita.",
    },
    "other-habits": {
      heading: "Il trattino lungo è solo una delle abitudini",
      body: "Il trattino attira l'attenzione perché è un singolo carattere che si può cercare. Non è l'unica regolarità, e le altre nascono dalle stesse due pressioni: dati di addestramento pieni di scrittura editata e strutturata, e una messa a punto orientata verso risposte che i lettori giudicano chiare.\n\n- **Grassetto su frasi chiave.** Non i titoli, ma una frase o due messe in evidenza dentro un paragrafo, spesso le prime parole di una voce di elenco. Rende una risposta scorrevole da scansionare, che è ciò per cui un'interfaccia di chat è ottimizzata.\n- **Elenchi puntati dove basterebbe la prosa.** Un'idea di tre frasi arriva come tre punti elenco. Gli elenchi ottengono buoni punteggi come risposte, quindi i modelli li usano di default anche quando i punti non sono davvero paralleli.\n- **Titoli su risposte brevi.** Una risposta di quattro paragrafi con due intestazioni di sezione sopra. La struttura è presa in prestito dalla documentazione, dove ha senso, e applicata a un testo troppo corto per aver bisogno di navigazione.\n- **Emoji come arredo.** Usate come indicatori di elenco o icone di sezione invece che come espressione — un segno di spunta davanti a ogni voce, un razzo sopra il blocco \"prossimi passi\".\n- **«Non è solo X — è Y».** La mossa di correzione-poi-elevazione, insieme a «vale la pena notare che» e «il punto chiave è». Costruzioni ordinarie; ciò che colpisce è quanto spesso si concentrano in un unico testo breve.\n- **La regola del tre.** Tre esempi, tre punti elenco, tre aggettivi, perché tre suona completo. Le bozze umane sono più irregolari — due motivi, o cinque, a seconda di quanti ce ne fossero davvero.\n\nNessuna di queste è una filigrana. Nessun fornitore imprime un segnale nascosto nel testo ordinario, e nessuna di queste abitudini è stata progettata come un indizio. Sono impostazioni di stile predefinite, e possono essere rimosse o richieste via come qualsiasi altra impostazione di stile predefinita. Se vuoi eliminarle da un documento che hai già, [Umanizzare il testo IA](/humanize-ai-text) rimuove lo strato meccanico — la punteggiatura, i caratteri invisibili, le emoji decorative — e [Convertire elenchi puntati in paragrafo](/bullet-points-to-paragraph) trasforma un testo troppo elencato di nuovo in prosa. Nessuno dei due promette di sconfiggere un rilevatore, e dovresti diffidare di qualsiasi cosa che lo faccia.\n\nL'insieme completo, compresi quelli che si possono contare, è nella guida sui [segni del testo scritto dall'IA](/guides/signs-of-ai-written-text).",
    },
    "not-proof": {
      heading: "I trattini lunghi non sono una prova di scrittura IA",
      body: "Questo va detto chiaramente, perché molti consigli online sbagliano: **la presenza di trattini lunghi non prova nulla.**\n\nMolti testi umani ne sono pieni. Microsoft Word e Google Docs convertono automaticamente un doppio trattino in un trattino lungo, quindi gli scrittori li producono senza mai scegliere consapevolmente quel carattere. Chiunque sia formato nella scrittura editoriale li usa d'istinto. Intere pubblicazioni li impongono.\n\nNon esiste un modo affidabile per rilevare un testo generato dall'IA dalla punteggiatura, e gli strumenti commerciali che affermano il contrario hanno tassi di falsi positivi ben documentati — con gli scrittori non madrelingua inglesi colpiti in modo sproporzionato. Trattare un trattino lungo come una prova ha costi reali quando l'accusa cade su uno studente o un collega.\n\nCiò che l'analisi della formattazione può dirti onestamente è meccanico: quanti trattini lunghi ci sono in questo documento, quante virgolette curve, quanti caratteri invisibili. Sono conteggi, non verdetti. Il nostro [Pulire il testo di ChatGPT e IA](/clean-ai-text) riporta esattamente quei numeri e non fa alcuna affermazione su chi o cosa abbia scritto il testo, che è l'unica cosa difendibile che uno strumento di formattazione possa fare.\n\nSe vuoi il quadro completo di quali artefatti di formattazione viaggiano con l'output dell'IA, la guida sui [segni del testo scritto dall'IA](/guides/signs-of-ai-written-text) copre il resto.",
    },
  },
  faqs: [
    { question: "Usare i trattini lunghi fa sembrare il mio testo generato dall'IA?", answer: "Non da solo. I trattini lunghi sono standard nell'inglese editato e compaiono in tutta la scrittura umana, anche perché Word e Google Docs li creano automaticamente dai doppi trattini. Ciò che sembra meccanico è un ritmo alto e uniforme — circa uno per paragrafo in tutto il documento — di solito insieme ad altri artefatti come virgolette curve ed elenchi aperti da emoji." },
    { question: "Con cosa dovrei sostituire un trattino lungo?", answer: "Adatta la sostituzione alla sua funzione. Una coppia che racchiude un inciso diventa virgole o parentesi; un trattino singolo che introduce una conclusione diventa due punti; un trattino che segna una rottura netta di solito funziona meglio come due frasi separate. Evita di sostituire un trattino lungo con un trattino semplice, che è un carattere diverso con uno scopo diverso." },
    { question: "Perché ChatGPT usa i trattini lunghi invece delle virgole?", answer: "Il trattino lungo è il segno più flessibile dell'inglese, capace di sostituire virgola, due punti, punto e virgola o parentesi. Quando diversi segni sarebbero grammaticalmente accettabili, è sempre una scelta sicura, quindi un modello ottimizzato per produrre prosa fluente lo seleziona in modo sproporzionato." },
    { question: "Posso impedire a ChatGPT di usare i trattini lunghi?", answer: "Puoi chiederlo direttamente nel prompt, per esempio «non usare trattini lunghi; usa virgole o frasi separate». La conformità è imperfetta e tende a svanire in una risposta lunga, quindi di solito è più veloce scrivere normalmente e rimuovere i trattini in seguito." },
    { question: "Un trattino lungo è uguale a un trattino semplice?", answer: "No. Il trattino semplice (-, U+002D) unisce le parole composte. Il trattino medio (–, U+2013) segna gli intervalli come 2020–2024. Il trattino lungo (—, U+2014) incastona una frase dentro un'altra frase. Sono tre caratteri distinti di larghezza crescente e non sono intercambiabili." },
  ],
};
