import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "¿ChatGPT oculta caracteres invisibles?",
  description: "Los textos de IA sí contienen Unicode invisible. Descubre qué hay realmente, de dónde viene y si alguna parte es una marca de agua.",
  h1: "¿ChatGPT oculta caracteres invisibles en tu texto?",
  dek: "La teoría de la marca de agua, lo que muestran realmente los bytes y cómo comprobar tu propio texto.",
  answer: "Los textos de IA suelen contener Unicode invisible, sobre todo espacios de no separación y espacios estrechos de no separación. Pero son subproductos triviales del formato del texto, no una marca de agua oculta. La marca de agua de texto real existe y funciona sesgando estadísticamente la elección de palabras, sin dejar caracteres especiales que encontrar. Puedes comprobar cualquier texto tú mismo en pocos segundos.",
  sections: {
    "the-claim": {
      heading: "La afirmación y por qué se difundió",
      body: "Cada pocos meses se hace viral una publicación que muestra que el texto copiado de ChatGPT contiene caracteres ocultos, con la conclusión de que OpenAI marca en secreto sus respuestas para poder rastrearlas.\n\nLa observación es real. La conclusión no está respaldada.\n\nLo que la gente encuentra es genuino: pega una respuesta del chat en un inspector de caracteres y verás con frecuencia puntos de código que no se representan como nada. El salto ocurre en la interpretación. Una marca de agua tiene que sobrevivir a la edición, ser difícil de eliminar y codificar algo. Unos caracteres que desaparecen en cuanto alguien hace un buscar y reemplazar, y que no contienen ninguna carga recuperable, no cumplen ninguna de esas condiciones.",
    },
    "what-is-there": {
      heading: "Qué hay realmente en el texto",
      body: "Los caracteres invisibles que aparecen en los textos de IA son, en su inmensa mayoría, caracteres tipográficos corrientes:\n\n| Carácter | Punto de código | Por qué aparece |\n| --- | --- | --- |\n| Espacio de no separación | U+00A0 | Mantiene un número y su unidad en la misma línea |\n| Espacio estrecho de no separación | U+202F | Espaciado fino antes de signos de puntuación y en números |\n| Espacio de ancho cero | U+200B | Sugerencias de salto de línea, a menudo heredadas de texto web |\n| Guión suave | U+00AD | Marca dónde puede dividirse una palabra al ajustar la línea |\n| Marca de orden de bytes | U+FEFF | Artefacto de codificación de un archivo anterior |\n\nCada uno tiene un propósito tipográfico legítimo y cada uno existe desde décadas antes de los modelos de lenguaje. Llegan por las mismas vías de siempre: el modelo los aprendió de textos de entrenamiento que los contenían, la interfaz del chat muestra la salida formateada como HTML, y copiar desde una página web renderizada arrastra lo que contuviera el marcado.\n\nEsa última vía importa más de lo que la gente cree. Gran parte de lo que se atribuye al modelo lo introduce en realidad la *copia del navegador*, no la generación. Copiar la misma respuesta a través de la API suele producir un texto notablemente más limpio que copiarla desde la ventana del chat.",
    },
    "does-watermarking-exist": {
      heading: "¿Existe siquiera la marca de agua en textos de IA?",
      body: "Sí, pero no funciona como asumen las publicaciones virales.\n\nSynthID-Text de Google DeepMind es el enfoque mejor documentado, publicado en *Nature* en 2024. Funciona sesgando sutilmente qué palabras elige el modelo en cada paso, de modo que el texto final lleva una firma estadística detectable por un verificador correspondiente. No intervienen caracteres especiales. No se inserta nada. La marca de agua reside en la *elección de palabras corrientes*, y por eso sobrevive a la copia y a la edición ligera, y por eso no puedes encontrarla inspeccionando puntos de código.\n\nOpenAI ha hablado públicamente de investigar marcas de agua en textos y no ha lanzado ninguna implementación confirmada de cara al consumidor para las respuestas de ChatGPT.\n\nLa implicación práctica va en contra del pánico: si un modelo que usas tiene marca de agua, eliminar los caracteres invisibles no la quitará. Y si encuentras caracteres invisibles, eso no es prueba de marca de agua: es prueba de formato.",
    },
    "why-it-matters": {
      heading: "Por qué los caracteres invisibles importan de todos modos",
      body: "Haya marca de agua o no, normalmente querrás eliminarlos, porque rompen cosas silenciosamente:\n\n- **La búsqueda y el buscar y reemplazar fallan.** Un espacio de ancho cero entre dos letras hace que buscar la palabra no encuentre nada, sin motivo visible.\n- **La validación de formularios rechaza la entrada.** Una dirección de correo o una clave de licencia con un espacio de no separación al final falla en una comparación que en pantalla parece correcta.\n- **El código se rompe en unos lenguajes y en otros no.** Un espacio de no separación donde debería haber un espacio normal es un error de sintaxis en Python, Go, Ruby, shell y JSON, y apunta a una línea que parece perfecta. JavaScript, TypeScript y C aceptan U+00A0 como espacio en blanco corriente y compilan sin rechistar, lo que es un problema en sí mismo: el carácter sobrevive en el archivo hasta que llega a una herramienta que sí lo rechaza.\n- **Las importaciones de CSV se corrompen.** Una marca de orden de bytes se adhiere al primer encabezado de columna, así que el primer campo no se asigna y nadie se entera.\n- **Aparecen registros duplicados.** Dos entradas que parecen idénticas son cadenas distintas, así que la desduplicación las pasa por alto.\n\nEstos fallos son especialmente molestos porque el texto parece correcto. Todo instinto de depuración apunta a otro sitio.",
    },
    "how-to-check": {
      heading: "Cómo comprobar y limpiar tu propio texto",
      body: "Pega el texto en el [Detector de caracteres invisibles](/remove-invisible-characters). Los elimina si lo pides e informa de tres números: el total de caracteres ocultos encontrados, cuántos de ellos eran de ancho cero y cuántos eran guiones suaves. La cifra de ancho cero incluye también las marcas direccionales de izquierda a derecha y de derecha a izquierda, y una marca de orden de bytes suma al total sin tener una línea propia. Cuando necesitas saber qué carácter hay exactamente en cada sitio, [Ver caracteres invisibles](/show-invisible-characters) etiqueta cada uno en su posición en lugar de borrarlo. Nada sale de tu navegador: ambas se ejecutan localmente.\n\nSi quieres una visión más amplia, el [Limpiador de texto de IA](/clean-ai-text) cubre los caracteres invisibles junto con rayas largas, comillas tipográficas y emojis en una sola pasada.\n\nUn hábito que vale la pena adquirir: haz la comprobación cada vez que un texto cruce la frontera entre sistemas. De la ventana del chat al editor de código, de la página web a la hoja de cálculo, del PDF al formulario. Ahí es donde los caracteres invisibles hacen daño, y es el momento en que eliminarlos cuesta menos.\n\nPara ver la lista completa de qué son estos caracteres y qué hace cada uno, consulta la [referencia de Unicode invisible](/guides/invisible-unicode-characters).",
    },
  },
  faqs: [
    { question: "¿ChatGPT marca su texto con caracteres invisibles?", answer: "No hay pruebas de ello. Los caracteres invisibles que se encuentran en las respuestas de ChatGPT son caracteres tipográficos corrientes, como los espacios de no separación y los espacios estrechos de no separación, que existen desde hace décadas y no contienen ninguna carga. Además, desaparecen con cualquier limpieza básica, lo que los haría inútiles como marca de agua." },
    { question: "¿Se puede marcar con marca de agua un texto generado por IA?", answer: "Sí. SynthID-Text de Google DeepMind, publicado en Nature en 2024, sesga las elecciones de palabras del modelo para que la salida lleve una firma estadística. No inserta caracteres especiales, así que inspeccionar puntos de código nunca lo revelará, y eliminar caracteres invisibles no lo quita." },
    { question: "¿Por qué el texto copiado de ChatGPT contiene caracteres ocultos?", answer: "Sobre todo porque estás copiando HTML renderizado de una página web. La interfaz del chat muestra la salida con formato, y la copia arrastra los caracteres de espaciado que ese formato usaba. Obtener la misma respuesta a través de la API suele producir un texto notablemente más limpio." },
    { question: "¿Cómo encuentro caracteres invisibles en mi texto?", answer: "Pégalo en un detector. Nuestro Detector de caracteres invisibles informa de cuántos caracteres ocultos hay, cuántos son de ancho cero y cuántos son guiones suaves, y luego los elimina si lo pides. Para ver qué carácter hay en cada sitio, Ver caracteres invisibles etiqueta cada uno en su posición. Ambas funcionan por completo en tu navegador." },
    { question: "¿Los caracteres invisibles son peligrosos?", answer: "No peligrosos, pero sí realmente disruptivos. Rompen la búsqueda, hacen fallar la validación de formularios, producen errores de sintaxis en el código, corrompen encabezados CSV y crean registros duplicados que parecen idénticos. Como el texto parece normal, estos errores son inusualmente difíciles de diagnosticar." },
  ],
};
