import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Raya larga, raya media y guion: la diferencia",
  description: "Tres caracteres, tres funciones. Cuándo usar cada raya, cómo escribirlas en cualquier teclado y por qué cambiar una por otra rompe cosas.",
  h1: "Raya larga, raya media y guion",
  dek: "Tres caracteres Unicode distintos que se parecen y no son intercambiables.",
  answer: "El guion (-) une palabras compuestas: bien conocido. La raya media (–) marca rangos y conexiones: páginas 20–24. La raya larga (—) separa una frase dentro de una oración, como una coma más fuerte. Son tres caracteres Unicode distintos de anchura creciente, y los analizadores, las búsquedas y la composición tipográfica los tratan de forma diferente.",
  sections: {
    "the-three-characters": {
      heading: "Los tres caracteres de un vistazo",
      body: "Los nombres vienen de la tipografía histórica: la raya media tenía la anchura de una N mayúscula y la raya larga la de una M mayúscula.\n\n| Signo | Nombre | Punto de código | Anchura | Uso principal |\n| --- | --- | --- | --- | --- |\n| - | Guion-menos | U+002D | La menor | Palabras compuestas |\n| – | Raya media | U+2013 | Media | Rangos y conexiones |\n| — | Raya larga | U+2014 | La mayor | Pausas dentro de una oración |\n\nEl primero está en tu teclado. Los otros dos no, y esa es la raíz práctica de casi toda la confusión: la gente escribe un guion donde corresponde una raya media o larga, porque es el único disponible sin atajo de teclado.",
    },
    "the-hyphen": {
      heading: "El guion",
      body: "El guion une elementos en una sola unidad.\n\n- **Modificadores compuestos delante de un nombre**: un autor *bien conocido*, un perro de *doce años de edad*, una instalación de *última generación*. Fíjate en que el guion desaparece cuando la frase va detrás del nombre: el autor está *bien conocido*.\n- **Algunos prefijos**, sobre todo para evitar una colisión o una ambigüedad: *reelegir* en inglés se escribe *re-elect*, y *re-cover* una silla (volver a tapizarla) se distingue de *recover* (recuperarse de una enfermedad).\n- **Las divisiones de palabras al final de línea**, en la composición justificada.\n- **Números compuestos**: *twenty-three* (veintitrés).\n\nTécnicamente, el carácter del teclado es el *guion-menos*: un único punto de código que hace de guion, de signo menos y de marca de opción en la línea de comandos, heredado de las máquinas de escribir y del ASCII primitivo. Unicode tiene un guion específico (U+2010) y un signo menos específico (U+2212), pero casi nada los usa, y no deberías empezar a hacerlo: `-` es lo que esperan los analizadores, los shells y las URL.",
    },
    "the-en-dash": {
      heading: "La raya media",
      body: "La raya media significa *a*, *hasta* o *entre*. Conecta en lugar de unir.\n\n- **Rangos numéricos**: páginas *20–24*, *2020–2024*, *de 9–17 h*. Las guías de estilo desaconsejan mezclarla con palabras: escribe *de 2020 a 2024*, no *de 2020–2024*.\n- **Conexiones y conflictos entre entidades separadas**: el rally *París–Dakar*, la relación *médico–paciente*, el eje *este–oeste*. Aquí la distinción con el guion importa: *Franco-German* con guion sugiere una sola cosa fusionada, mientras que *France–Germany* con raya media significa dos partes en relación.\n- **Modificadores compuestos donde una parte ya tiene varias palabras**: un acuerdo *post–Segunda Guerra Mundial*. Con un guion, este se uniría solo a «Segunda».\n- **Resultados y votaciones**: una victoria por *3–1*.\n\nLa raya media es la menos usada de las tres y la que más a menudo se sustituye por un guion. En prosa normal, esa sustitución es una imprecisión tipográfica menor que pocos lectores notan. En datos no es menor: un rango de fechas escrito con raya media no coincidirá con una expresión regular que busca un guion.",
    },
    "the-em-dash": {
      heading: "La raya larga",
      body: "La raya larga separa una frase, creando una pausa más fuerte que una coma y más suave que un punto.\n\n- **En pareja, alrededor de un inciso**: *Los resultados —que nadie esperaba— fueron claros.*\n- **Sola, antes de una conclusión o un giro**: *Lo revisó todo dos veces —y aun así se le escapó.*\n- **Para marcar el habla interrumpida** en los diálogos.\n\nEl **espaciado** es el único desacuerdo de estilo real, y va por tres caminos. Chicago, APA y MLA escriben la raya larga pegada: *palabra—palabra*. El estilo AP deja un espacio a cada lado: *palabra — palabra*. Los estilos editoriales británicos que siguen New Hart's Rules usan en su lugar una raya media con espacios: *palabra – palabra*. Las tres son correctas; lo importante es la coherencia dentro de un documento. Los textos de IA suelen usar la raya larga con espacios, que es estilo AP y no un híbrido: solo parece un error a los editores que dan por sentado que Chicago es la única convención estadounidense.\n\nLa raya larga es también el signo que se ha convertido en una firma no oficial del texto generado por IA, porque los modelos la usan con mucha más regularidad que las personas. Eso se explica en [por qué ChatGPT usa tantas rayas largas](/guides/why-chatgpt-uses-em-dashes).",
    },
    "typing-them": {
      heading: "Cómo escribir cada una",
      body: "| Plataforma | Raya media (–) | Raya larga (—) |\n| --- | --- | --- |\n| macOS | <kbd>Option</kbd> + <kbd>-</kbd> | <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd> |\n| Windows | <kbd>Alt</kbd> + <kbd>0150</kbd> | <kbd>Alt</kbd> + <kbd>0151</kbd> |\n| Linux | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2013 | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2014 |\n| Microsoft Word | Escribir `palabra - palabra` y luego un espacio lo autocorrige | Escribir `palabra--palabra` y luego un espacio lo autocorrige |\n| Google Docs | Insertar &rarr; Caracteres especiales | Sin conversión por defecto; Insertar &rarr; Caracteres especiales, o añade tu propia sustitución de `--` |\n| HTML | `&ndash;` | `&mdash;` |\n| iOS / Android | Mantén pulsada la tecla del guion | Mantén pulsada la tecla del guion |\n\nLos códigos Alt de Windows requieren un teclado numérico, razón por la que tantos usuarios de portátil sencillamente nunca escriben estos caracteres.",
    },
    "when-it-breaks-things": {
      heading: "Cuándo la diferencia rompe cosas de verdad",
      body: "En prosa, usar un guion donde corresponde una raya media es un detalle tipográfico. Fuera de la prosa, son tres puntos de código distintos y la diferencia es funcional:\n\n- **La búsqueda y el buscar y reemplazar** coinciden con caracteres exactos. Buscar `2020-2024` no encontrará `2020–2024`.\n- **Los comandos de shell** necesitan U+002D. Un `--force` pegado desde un documento donde la autocorrección lo convirtió en raya larga no es una opción, y el mensaje de error no mencionará las rayas.\n- **CSV y JSON** tratan las rayas media y larga como texto normal, lo que suele estar bien, hasta que un valor que debería coincidir con una clave no lo hace.\n- **Las URL y los slugs** solo aceptan el guion ASCII.\n- **La ordenación y la deduplicación** tratan los tres como caracteres distintos, así que entradas que parecen idénticas no se agrupan.\n\nSi necesitas normalizar las rayas en un documento, [Eliminar rayas largas del texto](/remove-em-dashes) las sustituye por el reemplazo que elijas e informa del recuento, para que puedas confirmar que el número coincide con lo esperado en lugar de fiarte de un reemplazo silencioso. La trampa equivalente con las comillas se explica en [por qué las comillas tipográficas rompen el código](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "¿Cuál es la diferencia entre la raya larga y la raya media?", answer: "La raya media (–, U+2013) significa a o hasta y marca rangos como 2020–2024. La raya larga (—, U+2014) separa una frase dentro de una oración, como una coma más fuerte. La raya larga es aproximadamente el doble de ancha, y son caracteres Unicode distintos." },
    { question: "¿Cuándo debo usar un guion en lugar de una raya?", answer: "Usa el guion para unir palabras en una sola unidad: bien conocido, veintitrés. Si te refieres a un rango, a una conexión entre dos partes o a una pausa en una oración, lo que necesitas es una raya media o larga." },
    { question: "¿Las rayas largas llevan espacios alrededor?", answer: "Depende de la guía de estilo. Chicago, APA y MLA las escriben pegadas (palabra—palabra). El estilo AP deja un espacio a cada lado (palabra — palabra). Los estilos editoriales británicos que siguen New Hart's Rules usan en su lugar una raya media con espacios (palabra – palabra). Todas son correctas; lo importante es la coherencia dentro de un mismo documento." },
    { question: "¿Cómo escribo una raya larga?", answer: "En macOS pulsa Option + Shift + guion. En Windows mantén pulsada Alt y escribe 0151 en el teclado numérico. En Word, escribir dos guiones entre palabras la genera automáticamente; Google Docs no tiene atajo integrado ni conversión por defecto, así que usa Insertar > Caracteres especiales o añade tu propia regla de sustitución. En el móvil, mantén pulsada la tecla del guion." },
    { question: "¿Importa si uso un guion en lugar de una raya media?", answer: "En prosa es una imprecisión menor que la mayoría de los lectores no notará. En datos, código, URL o cualquier cosa que se busque o se analice importa mucho, porque los tres son caracteres distintos y una coincidencia exacta fallará." },
  ],
};
