import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Exportar una conversación de ChatGPT a PDF o Word",
  description: "Imprimir a PDF recorta el chat y pierde el formato. Aprende a convertir una conversación en un PDF o documento Word limpio y legible.",
  h1: "Cómo exportar una conversación de ChatGPT a PDF o Word",
  dek: "Por qué imprimir la página falla y cómo conseguir un documento que de verdad enviarías a alguien.",
  answer: "Imprimir la página del chat directamente suele recortar los mensajes largos, perder los bloques de código y arrastrar al archivo todos los elementos de la interfaz. Copiar la conversación como texto, reestructurarla para que cada turno se convierta en una sección etiquetada y luego convertirla a PDF o DOCX produce un documento realmente legible y editable.",
  sections: {
    "why-printing-fails": {
      heading: "Por qué falla imprimir la página del chat",
      body: "Pulsar <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>P</kbd> en la ventana del chat es el gesto obvio, y produce resultados decepcionantes por razones estructurales.\n\nLas interfaces de chat están construidas como vistas de aplicación con desplazamiento, no como documentos. Eso lleva a fallos de impresión predecibles:\n\n- **Los mensajes largos se recortan.** Cada mensaje está dentro de su propio contenedor con scroll, así que la impresión solo captura la parte visible.\n- **Los bloques de código pierden contenido.** El código con scroll horizontal se corta en el borde del contenedor, de modo que la parte derecha de cada línea larga simplemente desaparece.\n- **Los elementos de la interfaz se cuelan.** Barras laterales, avatares, selectores de modelo y botones de regenerar: todo se imprime.\n- **Los saltos de página caen mal.** Nada le indica al navegador dónde hay un corte sensato, así que los títulos quedan huérfanos al final de las páginas.\n- **Solo existen los mensajes cargados.** Las conversaciones largas se virtualizan, por lo que los mensajes anteriores que no se han renderizado no aparecen en absoluto en la impresión.\n\nEl resultado es un archivo que técnicamente contiene tu conversación, pero que no adjuntarías a un correo.",
    },
    "the-reliable-route": {
      heading: "La vía fiable: copiar, estructurar, convertir",
      body: "Trata la conversación como texto, no como una página web.\n\n1. **Selecciona la conversación y cópiala.** Arrastra para seleccionar desde el primer mensaje hasta el último. Obtendrás el texto de ambas partes, normalmente con la estructura Markdown intacta.\n2. **Reestructurela como documento.** Pégala en [Convertir conversación de ChatGPT a documento](/chatgpt-conversation-to-document). Detecta los turnos de cada interlocutor y los reconstruye como secciones claras y etiquetadas, en lugar de un muro de texto indiferenciado.\n3. **Convierte al formato que necesites.** Para un archivo para compartir, [Convertir Markdown a PDF](/markdown-to-pdf) ofrece una vista lista para imprimir que puedes guardar directamente en PDF. Para algo editable, [Convertir Markdown a Word](/markdown-to-word) genera un `.docx` con estilos de título reales.\n\nEl resultado es un documento con título, secciones de interlocutores con encabezado, bloques de código y tablas conservados, y saltos de página en lugares sensatos.",
    },
    "labelling-speakers": {
      heading: "Cómo acertar con las etiquetas de los interlocutores",
      body: "La única parte que merece un momento de atención es cómo distingue el texto copiado quién dijo qué.\n\nSegún la interfaz y el navegador, una conversación copiada puede llegar con etiquetas explícitas o sin nada que separe los turnos. Si tu pegado no tiene etiquetas, añádelas antes de convertir: una línea que contenga solo `You:` o `ChatGPT:` encima de cada turno es suficiente para que el conversor encuentre los límites.\n\nUn formato que funciona de forma consistente:\n\n```\nYou:\nSummarize the Q2 results.\n\nChatGPT:\nRevenue rose 12% year over year, driven by...\n```\n\nEn conversaciones técnicas largas, conviene eliminar los callejones sin salida exploratorios antes de convertir. Una transcripción de cuarenta intercambios en los que solo seis importaban no es más útil por ser completa: es menos útil, porque el lector tiene que encontrar esos seis. Exporta la conversación que te gustaría leer.",
    },
    "practical-notes": {
      heading: "Notas prácticas sobre el archivo final",
      body: "**Configuración de página del PDF.** Al guardar desde el diálogo de impresión, activa los gráficos de fondo si quieres que los bloques de código conserven su sombreado, y comprueba que los márgenes no recorten las tablas anchas. La orientación horizontal suele ser la elección acertada para una conversación llena de datos.\n\n**Documentos de Word y títulos.** Como el conversor genera estilos de título reales en lugar de texto en negrita, el panel de navegación de Word funciona y puedes insertar una tabla de contenidos automática. Esa es la principal ventaja práctica frente a cualquier método de copiar y pegar.\n\n**Código largo.** El código que tenía scroll horizontal en la ventana del chat se ajustará en el documento. Si los saltos de línea exactos importan (un archivo de configuración, un comando de shell), revisa esos bloques después de convertir.\n\n**Privacidad.** Ambos conversores funcionan por completo en tu navegador; no se sube nada. Eso importa más que de costumbre aquí, ya que las conversaciones suelen contener contexto de trabajo, datos de clientes o material no publicado. Si dudarías en pegarlo en una web desconocida, el procesamiento local es la razón por la que este enfoque es seguro.\n\n**Una nota sobre las exportaciones oficiales.** ChatGPT ofrece una exportación de datos en la configuración, que te envía por correo un ZIP con tu historial de conversaciones. Es completa y útil para archivar, pero está estructurada como datos en bruto y no como un documento legible, así que igualmente tendrías que convertirla para compartir una sola conversación con alguien.",
    },
  },
  faqs: [
    { question: "¿Cómo guardo una conversación de ChatGPT como PDF?", answer: "Copia la conversación, reestructúrala con Convertir conversación de ChatGPT a documento para que cada turno se convierta en una sección etiquetada, luego usa Convertir Markdown a PDF y guarda desde el diálogo de impresión. Así evitas los mensajes recortados y los bloques de código perdidos que produce imprimir la página del chat." },
    { question: "¿Por qué al imprimir la página de ChatGPT se cortan mis mensajes?", answer: "Los mensajes están dentro de sus propios contenedores con scroll y las conversaciones largas se virtualizan, por lo que la impresión solo captura lo que está renderizado y visible en ese momento. Los bloques de código con scroll horizontal se cortan en el borde del contenedor por la misma razón." },
    { question: "¿Puedo exportar una conversación de ChatGPT a Word?", answer: "Sí. Convierte la conversación copiada a un .docx con Convertir Markdown a Word. Como produce estilos de título reales en lugar de texto en negrita, el panel de navegación funciona y puedes generar una tabla de contenidos automática." },
    { question: "¿ChatGPT tiene una exportación integrada?", answer: "Hay una exportación de datos en la configuración que te envía por correo un archivo con tu historial de conversaciones. Sirve bien como copia de seguridad, pero está estructurada como datos en bruto y no como un documento legible, así que convertir sigue siendo la vía práctica para compartir una sola conversación." },
    { question: "¿Es seguro pegar una conversación privada en un conversor?", answer: "Depende por completo de la herramienta. Las nuestras procesan el texto en tu navegador y no suben nada, por eso la conversación se queda en tu equipo. Cualquier herramienta que envíe el texto a un servidor debe tratarse como si lo publicara, algo importante cuando se trata de material de trabajo o de clientes." },
  ],
};
