import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Por qué el texto de IA pegado muestra ** y ## en Word",
  description: "Esos asteriscos y almohadillas son Markdown. Te explicamos por qué Word los muestra literalmente y tres formas de pegar texto de IA con el formato intacto.",
  h1: "¿Por qué el texto de IA pegado muestra ** y ## en Word?",
  dek: "Los símbolos son instrucciones de formato reales: Word simplemente no sabe cómo interpretarlos.",
  answer: "Esos símbolos son Markdown, un lenguaje de formato en texto plano en el que escriben los modelos de chat. Los asteriscos marcan negrita, las almohadillas marcan títulos y las barras verticales construyen tablas. Word no tiene un analizador de Markdown, así que los trata como caracteres normales y los muestra literalmente. Convertir el texto antes de pegarlo los transforma en formato real.",
  sections: {
    "what-the-symbols-are": {
      heading: "Qué significan realmente los símbolos",
      body: "Markdown es una convención para describir formato usando solo caracteres que puedes escribir. Se diseñó para que un documento se lea con sentido incluso cuando nada lo interpreta. Los modelos de chat escriben en él porque es compacto, inequívoco y se muestra correctamente en la interfaz del chat.\n\nEste es todo el vocabulario con el que probablemente te encontrarás:\n\n| Lo que ves | Lo que significa |\n| --- | --- |\n| `**bold**` | Texto en negrita |\n| `*italic*` o `_italic_` | Texto en cursiva |\n| `# Heading` | Título de nivel 1 (más almohadillas, título más pequeño) |\n| `- item` o `* item` | Elemento de lista con viñetas |\n| `1. item` | Elemento de lista numerada |\n| Acentos graves alrededor de `code` | Código en línea |\n| `> quote` | Cita en bloque |\n| `[text](url)` | Hipervínculo |\n| `\\| a \\| b \\|` | Fila de tabla |\n\nNada está roto y nada se corrompió por el camino. Estás viendo instrucciones bien formadas que han llegado a un lugar sin intérprete.",
    },
    "why-word-cannot-read-it": {
      heading: "Por qué Word no puede leerlo",
      body: "Word almacena el formato como datos estructurados dentro del documento. La negrita es un atributo asociado a un fragmento de caracteres, no un par de asteriscos a su alrededor. Cuando pegas texto plano, Word toma cada carácter al pie de la letra, porque desde su perspectiva un asterisco es un signo de puntuación que alguien escribió deliberadamente.\n\nPor eso las soluciones habituales decepcionan:\n\n- **Pegado especial → Texto con formato** no hace nada, porque no había ningún formato en el portapapeles que conservar. El portapapeles contenía caracteres planos.\n- **Buscar y reemplazar** elimina los asteriscos pero deja el texto sin negrita, así que pierdes la estructura por completo en lugar de ganarla.\n- **Formato automático** maneja algunos patrones como los caracteres de viñeta, pero no es un analizador de Markdown y no tocará `**bold**` ni `## Heading`.\n\nGoogle Docs se comporta igual por la misma razón. Notion, Obsidian y la mayoría de editores para desarrolladores *sí* interpretan Markdown, por eso el mismo pegado funciona correctamente ahí y crea la impresión de que es Word quien hace algo mal.",
    },
    "three-ways-to-fix": {
      heading: "Tres formas de obtener texto bien formateado",
      body: "Cuál te conviene depende de si necesitas el formato o solo quieres eliminarlo.\n\n**1. Convertir a un documento Word.** La opción más completa. [Convertir Markdown a Word](/markdown-to-word) convierte la respuesta en un `.docx` real con estilos de título auténticos, negritas, listas y tablas: el tipo de cosas que el panel de navegación y la tabla de contenidos de Word sí pueden ver. Úsala cuando el resultado vaya a convertirse en un informe o en cualquier cosa que otra persona vaya a editar.\n\n**2. Convertir a texto enriquecido y pegar.** [Convertir Markdown a Google Docs](/markdown-to-google-docs) genera texto enriquecido con formato que puedes copiar directamente en Google Docs, Word, Outlook o cualquier editor que acepte HTML pegado. Úsala cuando vas a insertar una sección en un documento que ya existe.\n\n**3. Eliminar los símbolos por completo.** A veces quieres prosa limpia sin ningún formato: para un correo, un campo de formulario, un cuadro de CMS o un mensaje de chat. [Eliminar formato Markdown](/remove-markdown-formatting) borra los caracteres de sintaxis dejando intacta cada palabra, que es justo lo que buscar y reemplazar no consigue hacer de forma segura.\n\nLas tres funcionan en tu navegador. No se sube nada.",
    },
    "stopping-it-at-the-source": {
      heading: "Evitarlo desde el origen",
      body: "También puedes pedirle al modelo que no use Markdown desde el principio. Un prompt como *\"responde en prosa sencilla sin formato Markdown, sin asteriscos, sin almohadillas y sin listas con viñetas\"* funciona razonablemente bien para respuestas cortas.\n\nEs menos fiable de lo que parece. El cumplimiento tiende a decaer a lo largo de una respuesta extensa, y el contenido estructurado —cualquier cosa con pasos, comparaciones o datos— empujará al modelo de vuelta a las listas y las tablas porque, sinceramente, es la forma más clara de presentarlo. Si tu respuesta contiene una tabla, casi seguro que quieres la tabla; solo la quieres como una tabla de verdad.\n\nPara cualquier cosa larga o estructurada, convertir después es el hábito más fiable. Además, así conservas la versión legible en la ventana del chat y obtienes una correctamente formateada en tu documento.\n\nSi con lo que estás luchando es una tabla en lugar de prosa, eso tiene sus propias peculiaridades: consulta [cómo pegar una tabla de ChatGPT en Excel](/guides/paste-chatgpt-table-into-excel).",
    },
  },
  faqs: [
    { question: "¿Por qué el texto de ChatGPT muestra asteriscos al pegarlo en Word?", answer: "Los asteriscos son sintaxis Markdown que marca texto en negrita y cursiva. Word no tiene un analizador de Markdown, así que los trata como caracteres normales y los muestra literalmente. Convertir primero el Markdown a un documento Word o a texto enriquecido los transforma en formato real." },
    { question: "¿Cómo pego una respuesta de ChatGPT en Word conservando el formato?", answer: "Conviértela primero. Convertir Markdown a Word genera un .docx con estilos de título reales, negritas, listas y tablas; Convertir Markdown a Google Docs genera texto enriquecido que puedes pegar directamente en un documento existente. Pegar la respuesta en bruto siempre mostrará los caracteres de sintaxis." },
    { question: "¿El pegado especial corrige los símbolos Markdown?", answer: "No. El pegado especial conserva el formato que ya existe en el portapapeles, y el Markdown en texto plano no tiene ninguno: el formato está codificado como caracteres, no como atributos. No hay nada que el pegado especial pueda conservar." },
    { question: "¿Qué significa ## en un texto generado por IA?", answer: "Marca un título. Una almohadilla es un título de primer nivel, dos es un título de segundo nivel, y así hasta seis. En un editor compatible con Markdown, las almohadillas desaparecen y la línea se muestra como un título con estilo." },
    { question: "¿Puedo simplemente buscar y reemplazar los asteriscos?", answer: "Puedes, pero borrarás el formato en lugar de aplicarlo: el texto deja de estar en negrita y simplemente pierde los marcadores. Eliminar Markdown de forma segura también implica gestionar títulos, marcadores de lista, enlaces y bloques de código, que es lo que una herramienta dedicada hace en una sola pasada." },
  ],
};
