import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Cómo pegar una tabla de ChatGPT en Excel",
  description: "Las tablas de IA se pegan en una sola columna porque son texto plano, no celdas. Así puedes obtener filas y columnas reales en Excel, Sheets o Numbers.",
  h1: "Cómo pegar una tabla de ChatGPT en Excel o Google Sheets",
  dek: "Por qué toda la tabla acaba en la columna A y las dos formas fiables de arreglarlo.",
  answer: "Una tabla de ChatGPT es una tabla Markdown con barras verticales: texto plano que usa el carácter | para sugerir columnas. Las hojas de cálculo esperan límites de celda, no barras, así que cada fila acaba en una sola columna. Convertir primero la tabla a XLSX o CSV genera filas y columnas reales que se abren correctamente en Excel, Sheets y Numbers.",
  sections: {
    "why-it-lands-in-one-column": {
      heading: "Por qué toda la tabla acaba en la columna A",
      body: "Lo que ves en la ventana del chat es una tabla renderizada. Lo que recibe tu portapapeles suele ser esto:\n\n```\n| Region | Q1 | Q2 |\n| --- | ---: | ---: |\n| Europe | 412 | 486 |\n| Asia | 377 | 381 |\n```\n\nEso es una tabla Markdown con barras verticales. Las barras son caracteres normales que *parecen* separadores de columna para un lector humano. La segunda línea, con sus guiones y dos puntos, le indica a un renderizador de Markdown dónde termina el encabezado y cómo alinear cada columna.\n\nExcel divide el texto pegado por tabulaciones, no por barras verticales. Como no hay tabulaciones, cada línea es un único valor y toda la tabla se apila en la columna A con las barras todavía visibles. Google Sheets y Numbers se comportan exactamente igual.\n\nLa fila de alineación es la prueba de que esto nunca fueron datos de hoja de cálculo. Ninguna exportación de hoja de cálculo contiene una fila de guiones y dos puntos.",
    },
    "the-fastest-fix": {
      heading: "La solución más rápida: convertir antes de pegar",
      body: "En lugar de pegar y reparar, convierte la tabla a un formato que las hojas de cálculo ya entienden.\n\n**Para Excel y Numbers**, [Convertir tabla Markdown a Excel](/markdown-table-to-excel) genera un archivo `.xlsx` de verdad. Pega la tabla, descarga la hoja de cálculo y ábrela. Los números siguen siendo números, la fila de encabezado sigue siendo un encabezado y no hay que dividir nada después.\n\n**Para Google Sheets**, [Convertir tabla Markdown a CSV](/markdown-table-to-csv) suele ser más cómodo. CSV se importa de forma nativa desde *Archivo → Importar*, y te ahorras el ciclo de descargar y volver a subir que exige un XLSX en el navegador. El conversor escapa correctamente las comillas y las comas incrustadas, que es justo donde suelen fallar las conversiones hechas a mano.\n\nAmbas herramientas funcionan localmente en tu navegador, así que los datos no salen de tu equipo, algo a tener en cuenta si la tabla contiene algo que no pegarías en una web cualquiera.",
    },
    "manual-methods": {
      heading: "Los métodos manuales y cuándo merecen la pena",
      body: "Si prefieres no salir de la hoja de cálculo, hay dos opciones integradas que funcionan.\n\n**Texto en columnas (Excel).** Pega la tabla sin formato en la columna A, selecciónala y ve a *Datos → Texto en columnas → Delimitado*, y establece el delimitador como el carácter de barra vertical. Aun así tendrás que eliminar la fila de alineación y recortar las columnas vacías que crean las barras del principio y del final.\n\n**SPLIT (Google Sheets).** Con la tabla sin formato en la columna A, usa `=SPLIT(A1, \"|\")` y arrastra hacia abajo, luego copia y pega solo valores. La misma limpieza se aplica aquí.\n\nEstos métodos valen para una sola tabla pequeña. Se vuelven tediosos enseguida, y ambos dejan espacios de relleno dentro de cada celda: los espacios que Markdown usa por legibilidad pasan a formar parte del valor, así que ` Europe ` no coincidirá con `Europe` en una fórmula de búsqueda. Ese problema del espacio final es la razón más común por la que una tabla convertida parece correcta pero se comporta mal.\n\n**Un apunte sobre copiar:** si seleccionas arrastrando la tabla *renderizada* en la ventana del chat en lugar de usar el botón de copiar, algunos navegadores ponen texto separado por tabulaciones en el portapapeles, que se pega correctamente en columnas. Es inconsistente entre navegadores e interfaces de chat, así que merece la pena probarlo, pero no fiarse de él.",
    },
    "google-sheets": {
      heading: "Cómo llevar la tabla a Google Sheets",
      body: "Sheets falla del mismo modo que Excel: las barras verticales no son un delimitador que reconozca, así que cada fila acaba en una sola celda de la columna A, pero las salidas son ligeramente distintas, y una de ellas es realmente cómoda.\n\n**Dividir texto en columnas.** Pega la tabla sin formato en una columna, mantén el rango pegado seleccionado y usa *Datos → Dividir texto en columnas*. Sheets ofrece una elección de separador, incluido uno personalizado, así que puedes ajustarlo al carácter de barra vertical. También muestra un pequeño control junto a los datos pegados justo después de pegar texto delimitado, que hace lo mismo sin pasar por el menú. Igual que con Texto en columnas de Excel, te queda la fila de alineación por eliminar, columnas vacías en cada extremo por las barras inicial y final, y un espacio de relleno dentro de cada valor.\n\n**Importar un CSV en su lugar.** *Archivo → Importar* analiza un archivo en lugar de un texto pegado, y te deja indicar cuál es el separador y si conviene convertir el texto en números y fechas. Esa es la diferencia que importa: una importación decide los tipos de columna de forma deliberada, mientras que un pegado los adivina. Pasa la tabla primero por [Convertir tabla Markdown a CSV](/markdown-table-to-csv) y no queda nada por adivinar: la fila de alineación desaparece, el relleno se recorta y las comas dentro de las celdas quedan correctamente entrecomilladas.\n\n**Sheets como escala intermedia.** Una vez que una tabla está en celdas reales, copiar ese rango arrastra la cuadrícula consigo. Pegar desde Sheets en Excel, Word, Slides, Docs o un correo mantiene intactas las filas y columnas, porque el portapapeles ahora contiene datos tabulares en lugar de una línea de texto con barras. Si una tabla tiene que llegar a una aplicación sin importación propia, pasar primero por una hoja de cálculo es más fiable que pelearse con el destino.\n\nUna cosa específica de Sheets que conviene vigilar: valores como `3-4` o `1/2` en una celda convertida se interpretarán como fechas. Si una columna llega llena de fechas que no pediste, deshaz, formatea la columna de destino como texto plano y vuelve a pegar.",
    },
    "tables-buried-in-prose": {
      heading: "Cuando la tabla está enterrada en una respuesta larga",
      body: "A menudo la tabla que quieres es solo una parte de una respuesta mucho más larga, mezclada con explicaciones por encima y por debajo.\n\n[Extraer tablas de un texto](/extract-table-from-text) encuentra filas con formato de tabla dentro del texto que las rodea, ya sean delimitadas por barras verticales o por tabulaciones, y devuelve solo la tabla como CSV. Pega la respuesta completa y extrae los datos, en lugar de seleccionar filas a mano y cruzar los dedos para haber acertado los límites.\n\nDos cosas que conviene comprobar en cualquier tabla convertida antes de seguir trabajando con ella:\n\n- **Números guardados como texto.** Si una columna llega alineada a la izquierda en Excel, los valores son texto. Los símbolos de moneda, los separadores de miles y los signos de porcentaje del original son la causa habitual. Selecciona la columna y usa *Datos → Texto en columnas → Finalizar* para convertirlos.\n- **Celdas combinadas o con saltos de línea.** Las tablas Markdown no pueden expresar celdas combinadas, así que un modelo que presenta datos complejos a veces lo simula con valores repetidos o saltos de línea dentro de una celda. Eso requiere una decisión humana, no un conversor.\n\nSi el resto de la respuesta también necesita trasladarse —títulos, listas, la explicación alrededor de la tabla—, consulta [por qué el texto de IA pegado muestra ** y ##](/guides/markdown-symbols-in-word).",
    },
  },
  faqs: [
    { question: "¿Por qué una tabla de ChatGPT se pega en una sola columna en Excel?", answer: "Porque es una tabla Markdown con barras verticales, es decir, texto plano que usa el carácter | como separador visual. Excel divide el texto pegado por tabulaciones, no por barras, así que cada línea se trata como un único valor y toda la tabla se apila en una sola columna." },
    { question: "¿Cómo convierto una tabla Markdown a Excel?", answer: "Pégala en Convertir tabla Markdown a Excel y descarga el archivo .xlsx resultante. Genera filas y columnas reales con el encabezado conservado, así que no hay nada que dividir ni limpiar después de abrirlo." },
    { question: "¿Qué es la fila de guiones y dos puntos en una tabla de IA?", answer: "Es la fila de alineación de Markdown. Separa el encabezado del cuerpo y define la alineación de cada columna: dos puntos a la derecha significa alineada a la derecha, en ambos lados, centrada. Es sintaxis de formato, no datos, y debe eliminarse durante la conversión." },
    { question: "¿Por qué mis celdas convertidas tienen espacios de más?", answer: "Markdown rellena las celdas con espacios por legibilidad, y la división manual conserva ese relleno dentro del valor. Importa porque ' Europe ' no coincidirá con 'Europe' en una búsqueda. Un buen conversor recorta el relleno; si divides a mano, envuelve los resultados en TRIM." },
    { question: "¿Puedo pegar una tabla de IA directamente en Google Sheets?", answer: "No con las columnas intactas. Convertirla primero a CSV e importarla desde Archivo → Importar es la vía más fiable, ya que CSV es un formato que Sheets analiza de forma nativa y evita el ciclo de descarga y subida del XLSX." },
  ],
};
