import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "¿Cuántos tokens tiene mi prompt?",
  description: "Los tokens son fragmentos de palabras, no palabras. Cómo funciona la tokenización, por qué varía entre modelos y cómo estimar el coste.",
  h1: "¿Cuántos tokens tiene mi prompt?",
  dek: "Por qué 1.000 palabras nunca son 1.000 tokens, y qué significa eso para los límites de contexto y el coste.",
  answer: "Los tokens son fragmentos de palabras, así que los recuentos nunca coinciden con el número de palabras. En inglés corriente, un token equivale de media a unos cuatro caracteres o tres cuartos de palabra: 1.000 palabras son aproximadamente 1.300 tokens. El código, los alfabetos no latinos y las palabras poco comunes consumen más tokens por carácter, a veces varias veces más.",
  sections: {
    "what-a-token-is": {
      heading: "Qué es realmente un token",
      body: "Los modelos de lenguaje no leen caracteres ni palabras. Leen tokens: fragmentos que se obtienen al dividir el texto según un vocabulario fijo aprendido de los datos de entrenamiento.\n\nLas palabras frecuentes suelen ser un solo token. Las palabras raras se dividen en piezas. Los espacios en blanco suelen adjuntarse al principio del token siguiente, por lo que la misma palabra puede contar de forma distinta según empiece o no una frase.\n\nLa palabra *increíble* no es un solo token: probablemente se divide en algo como `in` + `cre` + `íble`. En cambio, *el* es un único token, y también lo es *internacional*, porque apareció con suficiente frecuencia en el entrenamiento como para tener su propia entrada.\n\nPor eso los recuentos de tokens parecen impredecibles. La unidad no es lingüística, es estadística. La frecuencia en el corpus de entrenamiento determina si algo es un token o cuatro.",
    },
    "rules-of-thumb": {
      heading: "Reglas aproximadas que sí funcionan",
      body: "Para texto en inglés:\n\n- **1 token ≈ 4 caracteres**\n- **1 token ≈ 0,75 palabras**\n- **1.000 palabras ≈ 1.300 tokens**\n- **Una página estándar (~500 palabras) ≈ 650 tokens**\n\nEstas reglas dejan de valer rápidamente fuera del texto corriente:\n\n| Tipo de contenido | Aproximadamente |\n| --- | --- |\n| Texto en inglés | 0,75 palabras por token |\n| Código | 2–3× más tokens que el texto equivalente |\n| JSON con claves largas | Muy alto: la puntuación y las comillas son tokens aparte |\n| Chino, japonés, coreano | A menudo 1–2 tokens *por carácter* |\n| Cirílico, devanagari, árabe | Normalmente 2–3× el inglés para el mismo significado |\n| URL y hashes | Extremadamente alto: las cadenas aleatorias se tokenizan mal |\n| Espacios repetidos | Cada secuencia puede ser un token propio |\n\nLa brecha multilingüe es importante y poco conocida: la misma frase en japonés puede costar varias veces lo que cuesta en inglés, lo que afecta tanto al coste como a cuánto cabe en la ventana de contexto.",
    },
    "why-models-differ": {
      heading: "Por qué el recuento varía entre modelos",
      body: "Cada familia de modelos usa su propio tokenizador con su propio vocabulario, así que el mismo texto produce recuentos distintos.\n\nLos modelos GPT usan variantes de codificación por pares de bytes: `cl100k_base` para los modelos de la época de GPT-4 y `o200k_base` para los más recientes. Claude usa un tokenizador distinto con un vocabulario diferente. Los modelos abiertos como Llama y Mistral tienen, a su vez, los suyos propios.\n\nDiferencias del 10–20 % entre familias sobre el mismo texto en inglés son normales, y la brecha se amplía en el código y el texto en otros idiomas, donde los vocabularios divergen más.\n\nEn la práctica, esto significa:\n\n- Un recuento de un tokenizador es una **estimación** para cualquier otro modelo.\n- Solo el tokenizador del propio proveedor da un número exacto para su facturación.\n- Presupuesta con margen en lugar de ajustarte exactamente a un límite.\n\nNuestro [Contador de tokens](/token-counter) muestra un recuento para GPT-4o y una estimación para Claude lado a lado, lo que suele bastar para saber si un prompt está cómodamente dentro de un límite o incómodamente cerca de él.",
    },
    "why-it-matters": {
      heading: "Por qué importa el número",
      body: "**Coste.** El precio de las API es por token, con la entrada y la salida tarifadas por separado, y la salida suele costar varias veces más. Duplicar un prompt de sistema duplica ese coste en cada llamada: algo invisible en las pruebas y caro a gran escala.\n\n**Límites de contexto.** La ventana lo abarca *todo*: el prompt de sistema, el historial de la conversación, los documentos recuperados, el mensaje actual y el espacio reservado para la respuesta. Los chats largos fallan no porque un mensaje concreto sea largo, sino porque el historial se acumula.\n\n**Truncamiento.** Cuando la entrada supera el límite, algo se descarta, a menudo en silencio y a menudo el contenido más antiguo. Un modelo que «olvidó» tus instrucciones con frecuencia simplemente las perdió por truncamiento.\n\n**Fragmentación para recuperación.** Dividir documentos para generar embeddings se hace en tokens, no en caracteres. Los fragmentos dimensionados por número de caracteres quedan inconsistentes, y los que cortan una frase por la mitad se recuperan mal. Para dividir textos largos en piezas manejables, [Dividir texto en fragmentos](/text-splitter) corta cerca de los límites de los párrafos en lugar de a mitad de palabra.",
    },
    "reducing-tokens": {
      heading: "Reducir el recuento sin perder significado",
      body: "Las reducciones con más impacto, aproximadamente en este orden:\n\n1. **Recorta el historial de la conversación.** En un chat largo, eclipsa todo lo demás. Resume los turnos antiguos en lugar de reenviarlos literalmente.\n2. **Elimina instrucciones redundantes.** Repetir una regla de tres maneras no hace que se cumpla tres veces más. Lo que sí hace es triplicar el coste de esa regla.\n3. **Quita los artefactos de formato.** Los caracteres invisibles, los espacios repetidos y las líneas decorativas de separación también se tokenizan, y una fila de cuarenta guiones puede costar más que la frase que tiene encima. [Eliminar caracteres invisibles](/remove-invisible-characters) limpia los que no puedes ver.\n4. **Acorta las claves JSON** en los prompts estructurados. `{\"n\": ...}` frente a `{\"customer_full_name\": ...}`, multiplicado por mil registros, supone una gran diferencia.\n5. **Envía solo los fragmentos relevantes.** Recuperar tres párrafos pertinentes es mejor que pegar un documento entero, y suele producir respuestas mejores además de más baratas.\n\nLo que *no* ayuda: quitar la puntuación normal, borrar artículos o escribir en un estilo telegráfico entrecortado. El ahorro es marginal y el daño a la calidad del resultado no lo es.",
    },
  },
  faqs: [
    { question: "¿Cuántos tokens son 1.000 palabras?", answer: "Unos 1.300 tokens para texto corriente en inglés, con una media aproximada de 0,75 palabras por token. El código, el JSON y el texto en otros idiomas consumen bastante más: el chino, el japonés y el coreano suelen usar de uno a dos tokens por carácter." },
    { question: "¿Por qué el recuento de tokens es distinto en GPT y en Claude?", answer: "Cada familia de modelos usa su propio tokenizador con un vocabulario aprendido diferente, así que el mismo texto se divide de forma distinta. Diferencias del 10–20 % en texto en inglés son normales, y la brecha es mayor en el código y en idiomas distintos del inglés." },
    { question: "¿Qué es un token en un modelo de IA?", answer: "Un fragmento de texto del vocabulario fijo del modelo. Las palabras frecuentes suelen ser un solo token, mientras que las raras se dividen en varias piezas, de modo que «increíble» podría convertirse en tres tokens mientras que «internacional» es solo uno." },
    { question: "¿Los espacios y la puntuación cuentan como tokens?", answer: "Sí. Los espacios en blanco se adjuntan normalmente al principio del token siguiente, y la puntuación es con frecuencia un token propio. Las secuencias largas de espacios repetidos o las líneas decorativas de separación pueden consumir una cantidad sorprendente." },
    { question: "¿Cómo puedo reducir mi consumo de tokens?", answer: "Recorta primero el historial acumulado de la conversación: en los chats largos domina todo lo demás. Después elimina las instrucciones duplicadas, quita los caracteres invisibles y los espacios repetidos, acorta las claves JSON y envía solo el fragmento relevante de un documento en lugar del documento completo." },
  ],
};
