import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "¿Por qué ChatGPT usa tantas rayas largas?",
  description: "ChatGPT abusa de las rayas largas porque aprendió de textos editados. Aquí explicamos por qué el hábito es tan constante y cómo eliminarlas.",
  h1: "¿Por qué ChatGPT usa tantas rayas largas?",
  dek: "El signo de puntuación que se convirtió en firma de la IA, y qué hacer al respecto.",
  answer: "ChatGPT usa rayas largas porque se entrenó con textos editados profesionalmente —libros, ensayos y periodismo— donde la raya larga es habitual para destacar una frase. El modelo reproduce ese hábito con mucha más constancia que los escritores humanos, que rara vez escriben ese carácter. Esa diferencia de regularidad, y no el signo en sí, es lo que lo hace parecer una firma de la IA.",
  sections: {
    "where-it-comes-from": {
      heading: "De dónde viene el hábito",
      body: "Los modelos de lenguaje aprenden la puntuación igual que aprenden todo lo demás: absorbiendo patrones de sus datos de entrenamiento. Esos datos están muy orientados a la **escritura publicada y editada profesionalmente** —libros, periodismo de largo formato, ensayos y documentación—. En ese mundo, la raya larga es algo totalmente corriente. Los correctores la usan constantemente para destacar un inciso, introducir un resumen o crear una pausa antes de la cláusula final.\n\nLa escritura informal de internet no se parece en nada. En mensajes de chat, publicaciones en foros y correos, la gente usa comas, paréntesis y puntos. La mayoría nunca escribe una raya larga, porque en un teclado estándar no hay tecla para ella.\n\nAdemás de los datos de entrenamiento hay una segunda presión. Los modelos se ajustan para producir textos que los lectores valoren como claros y bien escritos, y la raya larga es excepcionalmente buena en esa tarea. Es el signo más flexible de la puntuación inglesa: puede sustituir a una coma, a los dos puntos, a un punto y coma o a un par de paréntesis. Cuando una frase admite varios signos distintos, recurrir a la raya larga siempre es defendible. Un sistema optimizado para generar texto fluido y con seguridad acabará usándola una y otra vez.",
    },
    "why-it-reads-as-ai": {
      heading: "Por qué la raya larga se convirtió en señal de IA",
      body: "La raya larga no se volvió sospechosa por ser rara. Se volvió sospechosa por **la constancia con la que aparece**.\n\nEscribir una requiere un esfuerzo deliberado. En un Mac es <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>; en Windows es <kbd>Alt</kbd> + <kbd>0151</kbd> o una regla de autocorrección. La mayoría de los teclados de móvil la esconden tras una pulsación larga. Así que cuando una persona escribe una raya larga, suele ser una decisión estilística consciente, y aparece de forma esporádica: unas pocas veces en un documento largo, concentradas donde el autor quería una pausa dramática.\n\nUn modelo de lenguaje no tiene esa fricción. Cada carácter cuesta lo mismo. El resultado es una huella estadística característica:\n\n- Las rayas largas aparecen a un ritmo constante en todos los párrafos, en lugar de a ráfagas.\n- Se usan con frecuencia en **pares**, envolviendo una frase parentética, donde la mayoría usaría comas.\n- Aparecen en registros que normalmente nunca las llevarían, como una respuesta breve, un elemento de una lista con viñetas o un informe de error.\n\nNinguno de esos patrones es incorrecto. Simplemente son más regulares de lo que suele ser la escritura humana, y la regularidad es exactamente lo que notan los lectores.",
    },
    "how-to-remove": {
      heading: "Cómo eliminar las rayas largas sin romper las frases",
      body: "El error está en sustituir cada raya larga por un guion. Un guion es un carácter distinto con una función distinta, y el resultado parece una errata en lugar de un texto limpio. Ajusta el reemplazo al trabajo que hacía la raya.\n\n**Un par de rayas largas que envuelven un inciso** suele convertirse en un par de comas. Si el inciso es una verdadera digresión, los paréntesis funcionan mejor.\n\n**Una raya larga sola antes de una conclusión** está sustituyendo a los dos puntos. Cámbiala por unos, o termina la frase y empieza una nueva.\n\n**Una raya larga sola a mitad de frase** a menudo marca un corte más brusco del que la frase necesita. Dividirla en dos frases casi siempre se lee mejor que cualquier signo sustituto.\n\n| Qué hace la raya | Mejor sustituto |\n| --- | --- |\n| Envuelve un inciso leve | Comas |\n| Envuelve una digresión | Paréntesis |\n| Introduce un resumen | Dos puntos |\n| Marca un corte brusco | Punto, divide la frase |\n| Indica un rango (2020—2024) | Raya media, no raya larga |\n\nSi estás trabajando con un documento largo, la herramienta [Eliminar rayas largas del texto](/remove-em-dashes) sustituye cada raya larga por el sustituto que elijas e informa de cuántas ha cambiado, para que puedas comprobar el recuento con tu propia lectura en lugar de fiarte de un buscar y reemplazar silencioso.",
    },
    "when-to-keep": {
      heading: "Cuándo conviene conservar la raya larga",
      body: "Eliminar todas las rayas largas de tu escritura es una sobrecorrección. El signo existe porque hace algo que las alternativas no pueden: crea una pausa con más fuerza que una coma y menos finalidad que un punto, sin el aire burocrático del punto y coma.\n\nConsérvala cuando:\n\n- La frase necesita de verdad una interrupción brusca, y una coma sería demasiado suave.\n- Estás citando una fuente que la usó. Editar la puntuación dentro de una cita cambia la cita.\n- El manual de estilo lo exige. La mayoría de las editoriales de libros y muchas redacciones usan rayas largas con libertad.\n- Escribes ficción o ensayos personales, donde el ritmo importa más que parecer neutro frente a las máquinas.\n\nEl objetivo realista no es cero rayas largas. Es que las rayas largas aparezcan porque tú las elegiste, a un ritmo que refleje tu propia voz. Una o dos en un artículo largo parecen deliberadas. Una en cada párrafo parece un valor por defecto.",
    },
    "not-proof": {
      heading: "Las rayas largas no prueban que un texto sea de IA",
      body: "Conviene decirlo claramente, porque muchos consejos en internet se equivocan: **la presencia de rayas largas no prueba nada.**\n\nMuchos textos escritos por personas están llenos de ellas. Tanto Microsoft Word como Google Docs convierten automáticamente un guion doble en raya larga, así que los escritores las producen sin haber elegido nunca ese carácter. Cualquiera formado en escritura editorial las usa por instinto. Publicaciones enteras las imponen.\n\nNo existe ninguna forma fiable de detectar texto generado por IA a partir de la puntuación, y las herramientas comerciales que afirman lo contrario tienen tasas de falsos positivos bien documentadas, que afectan de forma desproporcionada a quienes no escriben en su lengua materna. Tratar una raya larga como prueba tiene costes reales cuando la acusación recae sobre un estudiante o un colega.\n\nLo que el análisis de formato puede decirte con honestidad es mecánico: cuántas rayas largas hay en este documento, cuántas comillas tipográficas, cuántos caracteres invisibles. Son recuentos, no veredictos. Nuestra herramienta [Limpiar texto de ChatGPT e IA](/clean-ai-text) informa exactamente de esos números y no afirma nada sobre quién o qué escribió el texto, que es lo único defendible que puede hacer una herramienta de formato.\n\nSi quieres el panorama completo de qué artefactos de formato acompañan a los textos de IA, la guía sobre las [señales de los textos escritos por IA](/guides/signs-of-ai-written-text) cubre el resto.",
    },
  },
  faqs: [
    { question: "¿Usar rayas largas hace que mi texto parezca generado por IA?", answer: "No por sí solo. Las rayas largas son habituales en el inglés editado y aparecen en muchos textos humanos, en parte porque Word y Google Docs las crean automáticamente a partir de guiones dobles. Lo que parece propio de máquinas es un ritmo alto y uniformemente espaciado —aproximadamente una por párrafo en todo el documento—, normalmente junto a otros artefactos como comillas tipográficas y listas con encabezados de emoji." },
    { question: "¿Por qué debo sustituir una raya larga?", answer: "Ajusta el reemplazo a su función. Un par que envuelve un inciso se convierte en comas o paréntesis; una raya sola que introduce una conclusión se convierte en dos puntos; una raya que marca un corte brusco suele leerse mejor como dos frases separadas. Evita sustituir una raya larga por un guion, que es un carácter distinto con una finalidad distinta." },
    { question: "¿Por qué ChatGPT usa rayas largas en lugar de comas?", answer: "La raya larga es el signo más flexible del inglés, capaz de sustituir a una coma, a los dos puntos, al punto y coma o a los paréntesis. Cuando varios signos serían gramaticalmente aceptables, siempre es una opción segura, así que un modelo ajustado para producir texto fluido la elige con una frecuencia desproporcionada." },
    { question: "¿Puedo evitar que ChatGPT use rayas largas?", answer: "Puedes pedírselo directamente en tu prompt, por ejemplo: «no uses rayas largas; usa comas o frases separadas». El cumplimiento es imperfecto y tiende a decaer a lo largo de una respuesta larga, así que suele ser más rápido escribir con normalidad y eliminar las rayas después." },
    { question: "¿Una raya larga es lo mismo que un guion?", answer: "No. Un guion (-, U+002D) une palabras compuestas. Una raya media (–, U+2013) marca rangos como 2020–2024. Una raya larga (—, U+2014) destaca una frase dentro de una oración. Son tres caracteres distintos de anchura creciente y no son intercambiables." },
  ],
};
