import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Tiret cadratin ou trait d'union : quelle différence ?",
  description: "Trois caractères, trois rôles. Quand utiliser chacun, comment les taper sur tout clavier, et pourquoi les confondre pose problème.",
  h1: "Tiret cadratin, demi-cadratin ou trait d'union",
  dek: "Trois caractères Unicode distincts qui se ressemblent et ne sont pas interchangeables.",
  answer: "Le trait d'union (-) relie les mots composés : bien connu devient un mot bien-connu. Le tiret demi-cadratin (–) marque les plages et les relations : pages 20–24. Le tiret cadratin (—) isole une incise dans une phrase, comme une virgule plus forte. Ce sont trois caractères Unicode distincts, de largeur croissante, et les analyseurs, la recherche et la composition typographique les traitent différemment.",
  sections: {
    "the-three-characters": {
      heading: "Les trois caractères en un coup d'œil",
      body: "Les noms viennent de la typographie historique : le tiret demi-cadratin avait la largeur d'un N majuscule, le tiret cadratin celle d'un M majuscule.\n\n| Signe | Nom | Point de code | Largeur | Usage principal |\n| --- | --- | --- | --- | --- |\n| - | Trait d'union-moins | U+002D | La plus courte | Mots composés |\n| – | Tiret demi-cadratin | U+2013 | Moyenne | Plages et relations |\n| — | Tiret cadratin | U+2014 | La plus longue | Incises dans une phrase |\n\nLe premier figure sur votre clavier. Les deux autres n'y figurent pas, ce qui est la cause pratique de la plupart des confusions : on tape un trait d'union là où il faudrait un tiret demi-cadratin ou cadratin, parce que c'est le seul disponible sans raccourci.",
    },
    "the-hyphen": {
      heading: "Le trait d'union",
      body: "Le trait d'unité relie des éléments en une seule unité.\n\n- **Les modificateurs composés devant un nom** : un auteur *bien-connu*, un chien de *douze-ans*, une installation *dernière-génération*. Notez que le trait d'union disparaît quand la locution se place après le nom : l'auteur est *bien connu*.\n- **Certains préfixes**, surtout pour éviter une collision ou une ambiguïté : *ré-élire*, *co-propriétaire*, *re-couvrir* une chaise (par opposition à *recouvrer* la santé).\n- **Les coupures de mots en fin de ligne**, dans la composition justifiée.\n- **Les nombres composés** : *vingt-trois*.\n\nTechniquement, le caractère du clavier est le *trait d'union-moins* : un seul point de code qui sert à la fois de trait d'union, de signe moins et d'indicateur d'option en ligne de commande, hérité des machines à écrire et des débuts d'ASCII. Unicode possède un trait d'union dédié (U+2010) et un signe moins dédié (U+2212), mais presque rien ne les utilise, et il ne faut pas commencer : `-` est ce qu'attendent les analyseurs, les shells et les URL.",
    },
    "the-en-dash": {
      heading: "Le tiret demi-cadratin",
      body: "Le tiret demi-cadratin signifie *à*, *jusqu'à* ou *entre*. Il met en relation plutôt qu'il ne soude.\n\n- **Les plages numériques** : pages *20–24*, *2020–2024*, *9h–17h*. Les guides de style déconseillent de le mélanger avec des mots : écrivez *de 2020 à 2024*, et non *de 2020–2024*.\n- **Les liens et oppositions entre entités distinctes** : le rallye *Paris–Dakar*, une relation *médecin–patient*, l'axe *est–ouest*. La distinction avec le trait d'union compte ici : *franco-allemand* avec un trait d'union suggère une seule entité fusionnée, tandis que *France–Allemagne* avec un tiret demi-cadratin désigne deux parties en relation.\n- **Les modificateurs composés dont un élément est déjà formé de plusieurs mots** : un accord de *l'après–Seconde Guerre mondiale*. Un trait d'union ne se rattacherait qu'à un seul mot.\n- **Les scores et les votes** : une victoire *3–1*.\n\nLe tiret demi-cadratin est le moins utilisé des trois et le plus souvent remplacé par un trait d'union. Dans la prose courante, cette substitution est une imprécision typographique mineure que peu de lecteurs remarquent. Dans les données, elle ne l'est pas : une plage de dates écrite avec un tiret demi-cadratin ne correspondra pas à une expression régulière qui cherche un trait d'union.",
    },
    "the-em-dash": {
      heading: "Le tiret cadratin",
      body: "Le tiret cadratin isole une incise, créant une coupure plus forte qu'une virgule et plus douce qu'un point.\n\n- **Par paires, autour d'une incise** : *Les résultats — que personne n'attendait — étaient clairs.*\n- **Seul, avant une conclusion ou un retournement** : *Elle a tout vérifié deux fois — et l'a quand même manqué.*\n- **Pour marquer une parole interrompue** dans un dialogue.\n\n**L'espacement** est le seul véritable désaccord de style. La convention américaine (Chicago Manual of Style) compose les tirets cadratins sans espaces : *mot—mot*. La convention britannique (Oxford et la plupart des journaux anglais) utilise plutôt un tiret demi-cadratin espacé : *mot – mot*. Les deux sont correctes ; c'est la cohérence au sein d'un document qui compte. Les textes générés par IA utilisent généralement le tiret cadratin espacé — *mot — mot* — un hybride des deux, ce qui explique pourquoi il peut paraître subtilement faux aux relecteurs formés à l'une ou l'autre tradition.\n\nLe tiret cadratin est aussi le signe devenu une signature officieuse des textes générés par IA, car les modèles l'emploient avec bien plus de régularité que les humains. Le sujet est traité dans [pourquoi ChatGPT utilise autant de tirets cadratins](/guides/why-chatgpt-uses-em-dashes).",
    },
    "typing-them": {
      heading: "Comment taper chacun d'eux",
      body: "| Plateforme | Tiret demi-cadratin (–) | Tiret cadratin (—) |\n| --- | --- | --- |\n| macOS | <kbd>Option</kbd> + <kbd>-</kbd> | <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd> |\n| Windows | <kbd>Alt</kbd> + <kbd>0150</kbd> | <kbd>Alt</kbd> + <kbd>0151</kbd> |\n| Linux | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2013 | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>, 2014 |\n| Word / Docs | Deux traits d'union entre mots corrigés automatiquement | Deux traits d'union corrigés automatiquement |\n| HTML | `&ndash;` | `&mdash;` |\n| iOS / Android | Appui long sur la touche du trait d'union | Appui long sur la touche du trait d'union |\n\nLes codes Alt de Windows exigent un pavé numérique, ce qui explique pourquoi tant d'utilisateurs d'ordinateurs portables ne tapent tout simplement jamais ces caractères.",
    },
    "when-it-breaks-things": {
      heading: "Quand la différence casse vraiment les choses",
      body: "Dans la prose, utiliser un trait d'union là où il faudrait un tiret demi-cadratin est une raffinement typographique. Hors de la prose, ce sont trois points de code distincts et la différence est fonctionnelle :\n\n- **La recherche et le rechercher-remplacer** correspondent à des caractères exacts. Chercher `2020-2024` ne trouvera pas `2020–2024`.\n- **Les commandes shell** exigent U+002D. Un `--force` collé depuis un document où l'autocorrection l'a transformé en tiret cadratin n'est pas une option, et le message d'erreur ne mentionnera pas les tirets.\n- **CSV et JSON** traitent les tirets demi-cadratins et cadratins comme du texte ordinaire, ce qui ne pose généralement pas de problème — jusqu'à ce qu'une valeur censée correspondre à une clé n'y parvienne pas.\n- **Les URL et les slugs** n'acceptent que le trait d'union ASCII.\n- **Le tri et la déduplication** considèrent les trois comme des caractères différents : des entrées qui semblent identiques ne se regroupent donc pas.\n\nSi vous devez normaliser les tirets dans tout un document, [Supprimer les tirets cadratins](/remove-em-dashes) les remplace par le substitut de votre choix et affiche le comptage, ce qui vous permet de vérifier que le nombre correspond à vos attentes plutôt que de faire confiance à un remplacement silencieux. Le piège voisin avec les guillemets est traité dans [pourquoi les guillemets courbes cassent le code](/guides/smart-quotes-break-code).",
    },
  },
  faqs: [
    { question: "Quelle est la différence entre un tiret cadratin et un tiret demi-cadratin ?", answer: "Le tiret demi-cadratin (–, U+2013) signifie « à » ou « jusqu'à » et marque les plages comme 2020–2024. Le tiret cadratin (—, U+2014) isole une incise dans une phrase, comme une virgule plus forte. Le tiret cadratin est environ deux fois plus large, et ce sont deux caractères Unicode distincts." },
    { question: "Quand faut-il utiliser un trait d'union plutôt qu'un tiret ?", answer: "Utilisez le trait d'union pour souder des mots en une seule unité : bien-connu, vingt-trois, ré-élire. Si vous voulez exprimer une plage, une relation entre deux parties ou une coupure dans une phrase, c'est un tiret demi-cadratin ou cadratin qu'il vous faut." },
    { question: "Faut-il des espaces autour des tirets cadratins ?", answer: "Cela dépend du guide de style. La convention américaine les compose sans espaces (mot—mot), tandis que la convention britannique utilise généralement un tiret demi-cadratin espacé (mot – mot). Les deux sont correctes ; c'est la cohérence au sein d'un même document qui compte." },
    { question: "Comment taper un tiret cadratin ?", answer: "Sur macOS, appuyez sur Option + Maj + trait d'union. Sous Windows, maintenez Alt et tapez 0151 sur le pavé numérique. Dans Word et Google Docs, taper deux traits d'union entre des mots déclenche la conversion automatique. Sur téléphone, faites un appui long sur la touche du trait d'union." },
    { question: "Est-ce grave d'utiliser un trait d'union à la place d'un tiret demi-cadratin ?", answer: "Dans la prose, c'est une imprécision mineure que la plupart des lecteurs ne remarqueront pas. Dans les données, le code, les URL ou tout ce qui est recherché ou analysé, cela compte énormément, car ce sont trois caractères distincts et une correspondance exacte échouera." },
  ],
};
