import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Exporter une conversation ChatGPT en PDF ou Word",
  description: "L'impression en PDF tronque le texte et perd la mise en forme. Voici comment obtenir un document PDF ou Word propre et lisible.",
  h1: "Comment exporter une conversation ChatGPT en PDF ou Word",
  dek: "Pourquoi l'impression de la page échoue, et comment obtenir un document que vous enverriez vraiment à quelqu'un.",
  answer: "Imprimer directement la page de conversation tronque généralement les longs messages, supprime les blocs de code et emporte les éléments d'interface dans le fichier. Copier la conversation sous forme de texte, la restructurer pour que chaque prise de parole devienne une section intitulée, puis convertir en PDF ou DOCX produit un document réellement lisible et modifiable.",
  sections: {
    "why-printing-fails": {
      heading: "Pourquoi l'impression de la page de conversation échoue",
      body: "Utiliser <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>P</kbd> dans la fenêtre de conversation est le réflexe évident, et il produit des résultats décevants pour des raisons structurelles.\n\nLes interfaces de conversation sont conçues comme des vues applicatives défilantes, pas comme des documents. Cela entraîne des échecs d'impression prévisibles :\n\n- **Les longs messages sont tronqués.** Chaque message se trouve dans son propre conteneur défilant, donc l'impression ne capture que la partie visible.\n- **Les blocs de code perdent leur contenu.** Le code qui défile horizontalement est coupé au bord du conteneur, et la partie droite de chaque ligne longue disparaît tout simplement.\n- **Les éléments d'interface sont imprimés.** Barres latérales, avatars, sélecteurs de modèle et boutons de régénération apparaissent tous à l'impression.\n- **Les sauts de page tombent mal.** Rien n'indique au navigateur où un saut serait judicieux, donc les titres se retrouvent orphelins en bas de page.\n- **Seuls les messages chargés existent.** Les longues conversations sont virtualisées : les messages anciens qui n'ont pas été rendus sont totalement absents de l'impression.\n\nLe résultat est un fichier qui contient techniquement votre conversation, mais que vous ne joindriez pas à un e-mail.",
    },
    "the-reliable-route": {
      heading: "La méthode fiable : copier, structurer, convertir",
      body: "Traitez la conversation comme du texte, pas comme une page web.\n\n1. **Sélectionnez la conversation et copiez-la.** Faites glisser la sélection du premier message au dernier. Vous obtiendrez le texte des deux interlocuteurs, généralement avec la structure Markdown intacte.\n2. **Restructurez-la en document.** Collez-la dans [Convertir une conversation ChatGPT en document](/chatgpt-conversation-to-document). L'outil détecte les prises de parole et les reconstruit en sections claires et intitulées, plutôt qu'en un bloc de texte indifférencié.\n3. **Convertissez au format souhaité.** Pour un fichier à partager, [Convertir Markdown en PDF](/markdown-to-pdf) offre une vue prête à imprimer que vous pouvez enregistrer directement en PDF. Pour un document modifiable, [Convertir Markdown en Word](/markdown-to-word) produit un `.docx` avec de véritables styles de titre.\n\nLe résultat est un document avec un titre, des sections de prises de parole titrées, des blocs de code et des tableaux préservés, et des sauts de page qui tombent aux bons endroits.",
    },
    "labelling-speakers": {
      heading: "Bien gérer les étiquettes des interlocuteurs",
      body: "Le seul point qui mérite un moment d'attention est la façon dont le texte copié distingue qui dit quoi.\n\nSelon l'interface et le navigateur, une conversation copiée peut arriver avec des étiquettes explicites, ou sans rien du tout pour séparer les prises de parole. Si votre collage n'a pas d'étiquettes, ajoutez-les avant la conversion : une ligne contenant simplement `You:` ou `ChatGPT:` au-dessus de chaque prise de parole suffit au convertisseur pour trouver les limites.\n\nUn format qui fonctionne de manière fiable :\n\n```\nYou:\nSummarize the Q2 results.\n\nChatGPT:\nRevenue rose 12% year over year, driven by...\n```\n\nPour les longues conversations techniques, il vaut la peine de supprimer les impasses exploratoires avant la conversion. Une transcription de quarante échanges dont six comptaient n'est pas plus utile parce qu'elle est complète — elle l'est moins, car le lecteur doit retrouver les six. Exportez la conversation que vous auriez envie de lire.",
    },
    "practical-notes": {
      heading: "Remarques pratiques sur le fichier final",
      body: "**Mise en page du PDF.** Lors de l'enregistrement depuis la boîte de dialogue d'impression, activez les graphiques d'arrière-plan si vous voulez que les blocs de code conservent leur ombrage, et vérifiez que les marges ne tronquent pas les tableaux larges. L'orientation paysage est souvent le bon choix pour une conversation riche en données.\n\n**Documents Word et titres.** Comme le convertisseur génère de véritables styles de titre plutôt que du texte en gras, le volet de navigation de Word fonctionne et vous pouvez insérer une table des matières automatique. C'est le principal avantage pratique par rapport à toute approche par copier-coller.\n\n**Code long.** Le code qui défilait horizontalement dans la fenêtre de conversation passera à la ligne dans un document. Si les sauts de ligne exacts comptent — un fichier de configuration, une commande shell — vérifiez ces blocs après la conversion.\n\n**Confidentialité.** Les deux convertisseurs fonctionnent entièrement dans votre navigateur ; rien n'est téléversé. Cela compte plus que d'habitude ici, car les conversations contiennent souvent un contexte professionnel, des informations sur des clients ou des documents non publiés. Si vous hésiteriez à les coller sur un site inconnu, le traitement local est la raison pour laquelle cette approche est sûre.\n\n**Un mot sur les exports officiels.** ChatGPT propose un export de données dans les paramètres, qui vous envoie par e-mail un ZIP contenant votre historique de conversations. C'est complet et utile pour l'archivage, mais les données sont structurées en données brutes plutôt qu'en document lisible : il faudrait donc quand même les convertir pour partager une conversation précise avec quelqu'un.",
    },
  },
  faqs: [
    { question: "Comment enregistrer une conversation ChatGPT en PDF ?", answer: "Copiez la conversation, restructurez-la avec Convertir une conversation ChatGPT en document pour que chaque prise de parole devienne une section intitulée, puis utilisez Convertir Markdown en PDF et enregistrez depuis la boîte de dialogue d'impression. Vous évitez ainsi les messages tronqués et les blocs de code manquants de l'impression directe de la page." },
    { question: "Pourquoi l'impression de la page ChatGPT coupe-t-elle mes messages ?", answer: "Les messages se trouvent dans leurs propres conteneurs défilants et les longues conversations sont virtualisées : l'impression ne capture donc que ce qui est actuellement rendu et visible. Les blocs de code qui défilent horizontalement sont coupés au bord du conteneur pour la même raison." },
    { question: "Puis-je exporter une conversation ChatGPT vers Word ?", answer: "Oui. Convertissez la conversation copiée en .docx avec Convertir Markdown en Word. Comme l'outil produit de véritables styles de titre plutôt que du texte en gras, le volet de navigation fonctionne et vous pouvez générer une table des matières automatique." },
    { question: "ChatGPT propose-t-il un export intégré ?", answer: "Il existe un export de données dans les paramètres qui vous envoie par e-mail une archive de votre historique de conversations. C'est pratique pour la sauvegarde, mais les données sont brutes plutôt que sous forme de document lisible : la conversion reste donc la voie pratique pour partager une conversation précise." },
    { question: "Est-il sûr de coller une conversation privée dans un convertisseur ?", answer: "Cela dépend entièrement de l'outil. Les nôtres traitent le texte dans votre navigateur et ne téléversent rien, c'est pourquoi la conversation reste sur votre machine. Tout outil qui envoie le texte à un serveur doit être considéré comme une publication, ce qui compte pour les documents professionnels ou clients." },
  ],
};
