import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Pourquoi le texte IA collé affiche ** et ## dans Word",
  description: "Ces astérisques et dièses sont du Markdown. Découvrez pourquoi Word les affiche tels quels et trois façons de coller la sortie d'une IA mise en forme.",
  h1: "Pourquoi le texte IA collé affiche-t-il ** et ## dans Word ?",
  dek: "Ces symboles sont de véritables instructions de mise en forme — Word ne sait simplement pas comment les lire.",
  answer: "Ces symboles sont du Markdown, un langage de mise en forme en texte brut dans lequel les modèles de conversation écrivent. Les astérisques marquent le gras, les dièses les titres et les barres verticales construisent des tableaux. Word n'a pas d'analyseur Markdown : il les traite donc comme des caractères ordinaires et les affiche littéralement. Convertir le texte avant de le coller les transforme en vraie mise en forme.",
  sections: {
    "what-the-symbols-are": {
      heading: "Ce que les symboles signifient réellement",
      body: "Markdown est une convention qui décrit la mise en forme uniquement avec des caractères que l'on peut taper. Il a été conçu pour qu'un document reste lisible même lorsque rien ne le rend. Les modèles de conversation écrivent en Markdown parce que c'est compact, sans ambiguïté et que l'interface de chat l'affiche correctement.\n\nVoici tout le vocabulaire que vous êtes susceptible de rencontrer :\n\n| Vous voyez | Cela signifie |\n| --- | --- |\n| `**bold**` | Texte en gras |\n| `*italic*` ou `_italic_` | Texte en italique |\n| `# Heading` | Titre de niveau 1 (plus il y a de dièses, plus le titre est petit) |\n| `- item` ou `* item` | Élément de liste à puces |\n| `1. item` | Élément de liste numérotée |\n| Des accents graves autour de `code` | Code en ligne |\n| `> quote` | Citation en bloc |\n| `[text](url)` | Lien hypertexte |\n| `\\| a \\| b \\|` | Ligne de tableau |\n\nRien n'est cassé et rien n'a été corrompu en route. Vous regardez des instructions correctement formées qui ont atterri dans un endroit dépourvu d'interpréteur.",
    },
    "why-word-cannot-read-it": {
      heading: "Pourquoi Word ne peut pas le lire",
      body: "Word stocke la mise en forme sous forme de données structurées à l'intérieur du document. Le gras est un attribut attaché à une suite de caractères, pas une paire d'astérisques qui l'entoure. Quand vous collez du texte brut, Word prend chaque caractère au pied de la lettre, car de son point de vue un astérisque est un signe de ponctuation que quelqu'un a tapé délibérément.\n\nC'est pourquoi les solutions de contournement habituelles déçoivent :\n\n- **Collage spécial → Texte mis en forme** ne change rien, car il n'y avait aucune mise en forme dans le presse-papiers à préserver. Le presse-papiers ne contenait que des caractères bruts.\n- **Rechercher et remplacer** supprime les astérisques mais laisse le texte sans gras : vous perdez donc entièrement la structure au lieu de la récupérer.\n- **Format automatique** gère quelques motifs comme les caractères de puces, mais ce n'est pas un analyseur Markdown et il ne touchera ni `**bold**` ni `## Heading`.\n\nGoogle Docs se comporte de la même façon pour la même raison. Notion, Obsidian et la plupart des éditeurs pour développeurs, eux, *analysent* le Markdown, c'est pourquoi le même collage y fonctionne correctement et donne l'impression que c'est Word qui fait quelque chose de travers.",
    },
    "three-ways-to-fix": {
      heading: "Trois façons d'obtenir un texte correctement mis en forme",
      body: "Laquelle choisir dépend de si vous avez besoin de la mise en forme ou si vous voulez simplement qu'elle disparaisse.\n\n**1. Convertir en document Word.** L'option la plus complète. [Convertir Markdown en Word](/markdown-to-word) transforme la réponse en véritable `.docx` avec de vrais styles de titre, du texte en gras, des listes et des tableaux — le genre d'éléments que le volet de navigation et la table des matières de Word peuvent réellement reconnaître. Utilisez cette option quand le résultat doit devenir un rapport ou tout document que quelqu'un d'autre va modifier.\n\n**2. Convertir en texte enrichi puis coller.** [Convertir Markdown en Google Docs](/markdown-to-google-docs) produit du texte enrichi mis en forme que vous pouvez copier directement dans Google Docs, Word, Outlook ou tout éditeur acceptant du HTML collé. Utilisez cette option quand vous insérez une section dans un document déjà existant.\n\n**3. Supprimer entièrement les symboles.** Parfois, vous voulez une prose propre sans aucune mise en forme — pour un e-mail, un champ de formulaire, une zone de CMS ou un message de chat. [Supprimer le formatage Markdown](/remove-markdown-formatting) efface les caractères de syntaxe tout en laissant chaque mot intact, ce que le rechercher-remplacer ne parvient pas à faire en toute sécurité.\n\nLes trois outils fonctionnent dans votre navigateur. Rien n'est téléversé.",
    },
    "stopping-it-at-the-source": {
      heading: "L'éviter à la source",
      body: "Vous pouvez aussi demander au modèle de ne pas utiliser Markdown du tout. Un prompt tel que *« réponds en prose simple sans mise en forme Markdown, sans astérisques, sans dièses et sans listes à puces »* fonctionne assez bien pour les réponses courtes.\n\nC'est moins fiable qu'il n'y paraît. La conformité a tendance à dériver au fil d'une longue réponse, et le contenu structuré — tout ce qui comporte des étapes, des comparaisons ou des données — ramènera le modèle vers les listes et les tableaux, car c'est véritablement la façon la plus claire de le présenter. Si votre réponse contient un tableau, vous voulez presque certainement ce tableau ; vous le voulez simplement comme un vrai tableau.\n\nPour tout ce qui est long ou structuré, convertir après coup est l'habitude la plus fiable. Cela vous permet aussi de garder la version lisible dans la fenêtre de conversation et d'obtenir une version correctement mise en forme dans votre document.\n\nSi le problème précis auquel vous vous heurtez est un tableau plutôt que de la prose, celui-ci a ses propres subtilités — voyez [comment coller un tableau ChatGPT dans Excel](/guides/paste-chatgpt-table-into-excel).",
    },
  },
  faqs: [
    { question: "Pourquoi le texte ChatGPT affiche-t-il des astérisques quand je le colle dans Word ?", answer: "Les astérisques sont de la syntaxe Markdown qui marque le texte en gras et en italique. Word n'a pas d'analyseur Markdown : il les traite donc comme des caractères ordinaires et les affiche littéralement. Convertir le Markdown en document Word ou en texte enrichi au préalable les transforme en vraie mise en forme." },
    { question: "Comment coller la sortie de ChatGPT dans Word avec la mise en forme ?", answer: "Convertissez-la d'abord. Convertir Markdown en Word produit un .docx avec de vrais styles de titre, du gras, des listes et des tableaux ; Convertir Markdown en Google Docs produit du texte enrichi que vous pouvez coller directement dans un document existant. Coller la réponse brute affichera toujours les caractères de syntaxe." },
    { question: "Le collage spécial corrige-t-il les symboles Markdown ?", answer: "Non. Le collage spécial préserve une mise en forme qui existe déjà dans le presse-papiers, et le Markdown en texte brut n'en a aucune — la mise en forme est encodée sous forme de caractères, pas d'attributs. Il n'y a rien que le collage spécial puisse conserver." },
    { question: "Que signifie ## dans un texte généré par une IA ?", answer: "Cela marque un titre. Un dièse indique un titre de premier niveau, deux un titre de deuxième niveau, et ainsi de suite jusqu'à six. Dans un éditeur compatible Markdown, les dièses disparaissent et la ligne s'affiche comme un titre stylé." },
    { question: "Puis-je simplement rechercher et remplacer les astérisques ?", answer: "Vous pouvez, mais vous supprimerez la mise en forme au lieu de l'appliquer — le texte cesse d'être en gras et perd simplement ses marqueurs. Supprimer le Markdown en toute sécurité implique aussi de traiter les titres, les marqueurs de liste, les liens et les blocs de code, ce qu'un outil dédié fait en une seule passe." },
  ],
};
