import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Coller un tableau ChatGPT dans Excel",
  description: "Les tableaux IA se collent dans une seule colonne car c'est du texte brut. Obtenez de vraies lignes et colonnes dans Excel, Sheets ou Numbers.",
  h1: "Comment coller un tableau ChatGPT dans Excel ou Google Sheets",
  dek: "Pourquoi tout le tableau atterrit dans la colonne A, et les deux méthodes fiables pour y remédier.",
  answer: "Un tableau ChatGPT est un tableau Markdown à barres verticales — du texte brut utilisant le caractère | pour suggérer des colonnes. Les tableurs attendent de vraies limites de cellules, pas des barres verticales : chaque ligne atterrit donc dans une seule colonne. Convertir d'abord le tableau en XLSX ou CSV produit de vraies lignes et colonnes qui s'ouvrent correctement dans Excel, Sheets et Numbers.",
  sections: {
    "why-it-lands-in-one-column": {
      heading: "Pourquoi tout le tableau atterrit dans la colonne A",
      body: "Ce que la fenêtre de conversation vous montre est un tableau mis en forme. Ce que votre presse-papiers reçoit ressemble plutôt à ceci :\n\n```\n| Region | Q1 | Q2 |\n| --- | ---: | ---: |\n| Europe | 412 | 486 |\n| Asia | 377 | 381 |\n```\n\nC'est un tableau Markdown à barres verticales. Les barres verticales sont des caractères ordinaires qui *ressemblent* à des séparateurs de colonnes pour un lecteur humain. La deuxième ligne, avec ses tirets et ses deux-points, indique à un moteur de rendu Markdown où s'arrête l'en-tête et comment aligner chaque colonne.\n\nExcel découpe le texte collé sur les tabulations, pas sur les barres verticales. Comme il n'y a aucune tabulation, chaque ligne devient une seule valeur, et tout le tableau s'empile dans la colonne A avec les barres encore visibles. Google Sheets et Numbers se comportent exactement de la même façon.\n\nLa ligne d'alignement est l'indice qui révèle qu'il ne s'agissait jamais de données de tableur. Aucun export de tableur ne contient une ligne de tirets et de deux-points.",
    },
    "the-fastest-fix": {
      heading: "La solution la plus rapide : convertir avant de coller",
      body: "Plutôt que de coller puis de réparer, convertissez le tableau dans un format que les tableurs comprennent déjà.\n\n**Pour Excel et Numbers**, [Convertir un tableau Markdown en Excel](/markdown-table-to-excel) produit un véritable fichier `.xlsx`. Collez le tableau, téléchargez la feuille de calcul, ouvrez-la. Les nombres restent des nombres, la ligne d'en-tête reste une ligne d'en-tête, et rien n'a besoin d'être redécoupé ensuite.\n\n**Pour Google Sheets**, [Convertir un tableau Markdown en CSV](/markdown-table-to-csv) est généralement plus fluide. Le CSV s'importe nativement via *Fichier → Importer*, ce qui évite l'aller-retour téléchargement-téléversement qu'impose le XLSX dans un navigateur. Le convertisseur échappe correctement les guillemets et les virgules internes, exactement là où les conversions faites à la main échouent d'habitude.\n\nLes deux s'exécutent localement dans votre navigateur : les données ne quittent jamais votre machine — un point important si le tableau contient des informations que vous ne colleriez pas sur un site au hasard.",
    },
    "manual-methods": {
      heading: "Les méthodes manuelles, et quand elles valent le coup",
      body: "Si vous préférez ne pas quitter le tableur, deux méthodes intégrées fonctionnent.\n\n**Convertir (Excel).** Collez le tableau brut dans la colonne A, sélectionnez-le, puis *Données → Convertir → Délimité*, et définissez la barre verticale comme séparateur. Il vous restera à supprimer la ligne d'alignement et à retirer les colonnes vides créées par les barres verticales en début et fin de ligne.\n\n**SPLIT (Google Sheets).** Avec le tableau brut en colonne A, utilisez `=SPLIT(A1, \"|\")` et étirez vers le bas, puis copiez et collez en valeurs. Le même nettoyage s'applique.\n\nCes méthodes conviennent pour un seul petit tableau. Elles deviennent vite fastidieuses, et toutes deux laissent des espaces de remplissage dans chaque cellule — les espaces que Markdown utilise pour la lisibilité font partie de la valeur : ` Europe ` ne correspondra donc pas à `Europe` dans une formule de recherche. Ce problème d'espace finale est la raison la plus fréquente pour laquelle un tableau converti semble correct mais se comporte mal.\n\n**Une remarque sur la copie :** si vous sélectionnez à la souris le tableau *mis en forme* dans la fenêtre de conversation plutôt que d'utiliser le bouton copier, certains navigateurs placent du texte séparé par des tabulations dans le presse-papiers, ce qui se colle correctement en colonnes. Le comportement varie selon les navigateurs et les interfaces de conversation : cela vaut le coup d'essayer, mais pas d'y compter.",
    },
    "tables-buried-in-prose": {
      heading: "Quand le tableau est enfoui dans une réponse plus longue",
      body: "Souvent, le tableau qui vous intéresse n'est qu'une partie d'une réponse bien plus longue, noyée entre des explications au-dessus et en dessous.\n\n[Extraire des tableaux d'un texte](/extract-table-from-text) repère les lignes en forme de tableau au milieu du texte environnant — délimitées par des barres verticales ou des tabulations — et renvoie uniquement le tableau en CSV. Collez la réponse entière et extrayez les données, au lieu de sélectionner les lignes à la main en espérant avoir bien cerné les limites.\n\nDeux points à vérifier sur tout tableau converti avant de vous appuyer dessus :\n\n- **Les nombres stockés comme du texte.** Si une colonne arrive alignée à gauche dans Excel, les valeurs sont du texte. Les symboles monétaires, les séparateurs de milliers et les signes de pourcentage d'origine en sont généralement la cause. Sélectionnez la colonne et utilisez *Données → Convertir → Terminer* pour les forcer en nombres.\n- **Les cellules fusionnées ou à la ligne.** Les tableaux Markdown ne peuvent pas exprimer de cellules fusionnées : un modèle présentant des données complexes simule parfois l'effet avec des valeurs répétées ou des sauts de ligne dans une cellule. Cela demande une décision humaine, pas un convertisseur.\n\nSi le reste de la réponse doit aussi être récupéré — titres, listes, explications autour du tableau — consultez [pourquoi le texte IA collé affiche ** et ##](/guides/markdown-symbols-in-word).",
    },
  },
  faqs: [
    { question: "Pourquoi un tableau ChatGPT se colle-t-il dans une seule colonne dans Excel ?", answer: "Parce qu'il s'agit d'un tableau Markdown à barres verticales, c'est-à-dire du texte brut utilisant le caractère | comme séparateur visuel. Excel découpe le texte collé sur les tabulations, pas sur les barres verticales : chaque ligne est donc traitée comme une seule valeur et tout le tableau s'empile dans une seule colonne." },
    { question: "Comment convertir un tableau Markdown en Excel ?", answer: "Collez-le dans Convertir un tableau Markdown en Excel et téléchargez le fichier .xlsx obtenu. Il produit de vraies lignes et colonnes avec l'en-tête conservé, il n'y a donc rien à redécouper ni à nettoyer après l'ouverture." },
    { question: "Qu'est-ce que la ligne de tirets et de deux-points dans un tableau IA ?", answer: "C'est la ligne d'alignement Markdown. Elle sépare l'en-tête du corps du tableau et définit l'alignement des colonnes — un deux-points à droite signifie aligné à droite, des deux côtés signifie centré. C'est de la syntaxe de mise en forme, pas des données, et elle doit être supprimée lors de la conversion." },
    { question: "Pourquoi mes cellules converties contiennent-elles des espaces en trop ?", answer: "Markdown remplit les cellules d'espaces pour la lisibilité, et un découpage manuel conserve ce remplissage dans la valeur. C'est important car « Europe » avec espaces ne correspondra pas à « Europe » dans une recherche. Un bon convertisseur supprime ces espaces ; si vous découpez manuellement, enveloppez les résultats dans SUPPRESPACE." },
    { question: "Puis-je coller un tableau IA directement dans Google Sheets ?", answer: "Pas en conservant les colonnes. Convertir d'abord en CSV puis importer via Fichier → Importer est la méthode la plus fiable : le CSV est un format que Sheets analyse nativement, et cela évite l'aller-retour téléchargement-téléversement du XLSX." },
  ],
};
