import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "7 signes qu'un texte a été écrit par une IA",
  description: "Les sept signes de mise en forme et de style typiques des textes générés par une IA, comment les repérer, et pourquoi aucun ne constitue une preuve.",
  h1: "Sept signes qu'un texte a été écrit par une IA",
  dek: "Quatre que l'on peut mesurer, trois que l'on ne peut que remarquer — et les limites honnêtes des deux.",
  answer: "Les signes les plus fiables sont mécaniques : des tirets cadratins à cadence régulière, des guillemets courbes, des caractères Unicode invisibles et des listes à puces ornées d'emojis. Les signes stylistiques — vocabulaire prudent, construction « pas seulement X, mais Y » et paragraphes d'une longueur anormalement uniforme — sont plus faibles. Aucun ne prouve quoi que ce soit à lui seul ; ce sont des motifs, pas des preuves.",
  sections: {
    "mechanical-signs": {
      heading: "Les quatre signes mécaniques réellement mesurables",
      body: "Ceux-ci se comptent. On peut les passer à un outil et obtenir un chiffre plutôt qu'une impression, ce qui les rend plus utiles qu'une détection au feeling.\n\n**1. Des tirets cadratins à cadence régulière.** Les modèles de conversation produisent le tiret cadratin (—) bien plus régulièrement que les humains, car sa saisie exige un raccourci clavier que la plupart des rédacteurs n'ont jamais appris. Un ou deux dans un long document, c'est normal. Environ un par paragraphe, répartis uniformément, ça ne l'est pas. Le [guide sur les tirets cadratins](/guides/why-chatgpt-uses-em-dashes) explique pourquoi cette habitude est si ancrée.\n\n**2. Des guillemets courbes et une ponctuation typographique.** Les textes d'IA arrivent souvent avec des guillemets directionnels (\" \"), des apostrophes courbes (') et un vrai caractère de points de suspension (…) plutôt que trois points. Les traitements de texte les génèrent aussi automatiquement : ils n'ont donc de sens que dans des contextes sans aucune correction automatique — un champ en texte brut, un commentaire de code, un fichier CSV.\n\n**3. Des caractères Unicode invisibles.** Les espaces sans chasse, les espaces insécables et les espaces fines insécables survivent fréquemment à un copier-coller depuis une fenêtre de conversation. Ils sont indétectables à l'œil nu et constituent le marqueur mécanique le plus fort, car presque rien de ce qu'un humain tape à la main ne les introduit.\n\n**4. Des listes à puces ornées d'emojis.** Les réponses structurées avec un emoji décoratif au début de chaque puce, les titres de section faits de texte en gras plutôt que de véritables titres, et les listes imbriquées sur trois niveaux forment un style de maison que les interfaces de conversation encouragent et que la plupart des rédacteurs humains n'utilisent pas.",
    },
    "stylistic-signs": {
      heading: "Les trois signes stylistiques — plus faibles, mais à connaître",
      body: "Les motifs stylistiques se prêtent bien plus facilement à l'erreur, car beaucoup d'écrits humains soignés les partagent. Considérez-les comme des invitations à regarder de plus près, jamais comme des conclusions.\n\n**5. Un cadrage prudent et systématiquement équilibré.** Des phrases qui présentent chaque question comme ayant deux côtés raisonnables, des paragraphes qui s'ouvrent en reformulant la question, et des phrases de conclusion qui résument sans rien ajouter. Cela vient d'un entraînement qui récompense à la fois l'utilité et l'absence d'engagement.\n\n**6. La construction « pas seulement X, mais Y ».** Avec des tournures comme « il convient de noter que », « plonger au cœur de », « naviguer dans les complexités de » ou « dans le monde trépidant d'aujourd'hui ». Ces expressions ne sont pas des mots interdits — c'est de l'anglais ordinaire dans la langue d'origine. Ce qui frappe, c'est la fréquence à laquelle elles se regroupent dans un même texte court.\n\n**7. Une structure anormalement uniforme.** Des paragraphes de longueur quasi identique, des sections comptant un nombre suspectement égal de puces, et une conclusion qui reflète l'introduction. Les brouillons humains sont plus irréguliers ; un paragraphe s'étire parce que le rédacteur avait davantage à dire sur ce point précis.\n\nLes signaux de vocabulaire, en particulier, s'usent vite. Chaque liste de « mots d'IA » qui circule finit absorbée dans la façon d'écrire des gens et dans le réglage de la génération de modèles suivante. Les signes mécaniques sont plus durables, car ce sont des sous-produits de l'encodage, pas du style.",
    },
    "how-to-check": {
      heading: "Comment vérifier un document en une seule passe",
      body: "Un ordre d'opérations pratique, du contrôle le moins coûteux au plus coûteux :\n\n1. **Recherchez les caractères invisibles.** C'est le contrôle au meilleur rapport signal/effort. Collez le texte dans le [scanner de caractères invisibles](/remove-invisible-characters) — il répertorie chaque espace sans chasse, césure conditionnelle, indicateur BOM et marque directionnelle trouvés, avec les comptages.\n2. **Comptez les artefacts mécaniques ensemble.** Le [nettoyeur de textes IA](/clean-ai-text) rapporte tirets cadratins, guillemets courbes, caractères invisibles et emojis en une seule passe, ce qui permet de voir si plusieurs signaux coïncident plutôt que d'en traquer un à la fois.\n3. **Lisez en quête des motifs stylistiques.** Seulement après avoir les chiffres. Les nombres d'abord vous évitent de vous convaincre vous-même d'une conclusion.\n4. **Pesez le contexte.** Un texte collé depuis Word portera des guillemets courbes, peu importe qui l'a écrit. Un texte tapé dans un simple champ en texte brut, non.\n\nC'est la cooccurrence qui compte. Un seul tiret cadratin ne signifie rien. Des tirets cadratins *et* des guillemets courbes *et* deux espaces sans chasse *et* des puces à emojis, dans un document tapé directement dans un formulaire en texte brut, forment une combinaison réellement inhabituelle.",
    },
    "why-not-proof": {
      heading: "Pourquoi rien de tout cela n'est une preuve",
      body: "Chaque signe ci-dessus a une explication innocente.\n\nWord et Google Docs convertissent automatiquement les doubles traits d'union en tirets cadratins et les guillemets droits en guillemets courbes. Copier depuis n'importe quel site web moderne peut véhiculer des caractères invisibles. Les rédacteurs professionnels écrivent exactement dans ce registre équilibré et prudent qui passe pour généré par machine. Les locuteurs non natifs de l'anglais écrivent souvent dans un style plus formel et structurellement régulier, ce qui explique précisément pourquoi les détecteurs d'IA commerciaux signalent leurs textes à des taux nettement plus élevés.\n\nIl y a aussi la circularité évidente : une personne peut coller une sortie d'IA dans un éditeur de texte, lancer un passage de nettoyage et faire disparaître chaque signe mécanique en une dizaine de secondes. Les signaux les plus faciles à mesurer sont aussi les plus faciles à effacer.\n\nVoici donc la position honnête. L'analyse de la mise en forme vous dit **quels caractères se trouvent dans un document**. Elle ne peut pas vous dire qui les y a mis. Nos outils rapportent délibérément des comptages et ne rendent jamais de verdict, car un verdict serait une supposition déguisée en chiffre. Si vous devez savoir si une personne a écrit quelque chose, la réponse vient d'une discussion avec elle — historique des brouillons, sources et capacité à expliquer son propre raisonnement — pas d'un comptage de tirets.",
    },
  },
  faqs: [
    { question: "Quel est le signe le plus fiable qu'un texte a été écrit par une IA ?", answer: "Les caractères Unicode invisibles comme les espaces sans chasse sont le marqueur mécanique le plus fort, car une saisie ordinaire n'en produit presque jamais alors qu'un copier-coller depuis une fenêtre de conversation en véhicule souvent. Malgré tout, ils peuvent aussi provenir d'un texte copié depuis un site web : ils indiquent donc l'origine du collage plutôt que la paternité du texte." },
    { question: "Les détecteurs d'IA fonctionnent-ils vraiment ?", answer: "Pas de façon fiable. Ils produisent des faux positifs sur des écrits humains — les locuteurs non natifs de l'anglais étant touchés de manière disproportionnée — et peuvent être déjoués par une légère retouche. L'analyse de la mise en forme peut compter des artefacts concrets, mais aucun outil, y compris les nôtres, ne peut établir la paternité d'un texte à partir du texte seul." },
    { question: "Utiliser des tirets cadratins ou des guillemets courbes me fera-t-il accuser d'utiliser une IA ?", answer: "Cela ne devrait pas, et ce serait une mauvaise base d'accusation. Word et Google Docs génèrent les deux automatiquement à partir d'une saisie ordinaire. Si la façon dont un document se présente vous inquiète, convertir la ponctuation en ASCII simple supprime les artefacts sans changer un seul mot de votre texte." },
    { question: "Puis-je supprimer ces signes d'un texte généré par une IA ?", answer: "Oui, et rapidement — c'est exactement pourquoi ils constituent une preuve faible. Remplacer les tirets cadratins, normaliser les guillemets et retirer les caractères invisibles prend quelques secondes. C'est une raison d'être sceptique face aux prétentions de détection, pas une technique pour faire passer un travail pour le sien." },
  ],
};
