import type { GuideTranslation } from "@/lib/i18n";

export const guide: GuideTranslation = {
  title: "Pourquoi ChatGPT aime-t-il tant les tirets cadratins ?",
  description: "ChatGPT abuse des tirets cadratins car il a appris sur des textes édités. Découvrez pourquoi cette habitude persiste et comment les supprimer proprement.",
  h1: "Pourquoi ChatGPT utilise-t-il tant de tirets cadratins ?",
  dek: "Le signe de ponctuation devenu une signature de l'IA, et ce qu'il faut en faire.",
  answer: "ChatGPT utilise des tirets cadratins parce qu'il a été entraîné sur des textes professionnellement édités — livres, essais et articles de presse — où le tiret cadratin est la norme pour isoler une phrase incise. Le modèle reproduit cette habitude de façon bien plus constante que les rédacteurs humains, qui tapent rarement ce caractère. C'est cet écart de régularité, et non le signe lui-même, qui le fait percevoir comme une signature de l'IA.",
  sections: {
    "where-it-comes-from": {
      heading: "D'où vient cette habitude",
      body: "Les grands modèles de langage apprennent la ponctuation comme tout le reste : en absorbant des schémas présents dans leurs données d'entraînement. Ces données sont fortement dominées par **des textes publiés et professionnellement édités** — livres, articles de fond, essais et documentation. Dans cet univers, le tiret cadratin est tout à fait banal. Les correcteurs l'utilisent en permanence pour isoler une incise, introduire un résumé ou créer une pause avant une dernière proposition.\n\nL'écriture informelle sur internet ne ressemble en rien à cela. Dans les messages, les forums et les e-mails, on utilise des virgules, des parenthèses et des points. La plupart des gens ne tapent jamais un tiret cadratin, tout simplement parce qu'aucune touche d'un clavier standard ne lui correspond.\n\nIl existe une seconde pression, qui s'ajoute aux données d'entraînement. Les modèles sont ajustés pour produire des textes que les lecteurs jugent clairs et bien écrits, et le tiret cadratin est remarquablement efficace pour cela. C'est le signe le plus souple de la ponctuation anglaise — il peut remplacer une virgule, les deux-points, un point-virgule ou une paire de parenthèses. Quand une phrase admet plusieurs signes possibles, choisir le tiret cadratin est toujours défendable. Un système optimisé pour produire un texte fluide et assuré y reviendra sans cesse.",
    },
    "why-it-reads-as-ai": {
      heading: "Pourquoi le tiret cadratin est devenu un indice d'IA",
      body: "Le tiret cadratin n'est pas devenu suspect parce qu'il est rare. Il l'est devenu à cause de **la régularité avec laquelle il apparaît**.\n\nLe taper demande un effort délibéré. Sur Mac, c'est <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd> ; sous Windows, <kbd>Alt</kbd> + <kbd>0151</kbd> ou une règle de correction automatique. Sur la plupart des claviers de téléphone, il se cache derrière un appui long. Quand un humain écrit un tiret cadratin, c'est donc généralement un choix stylistique conscient, qui apparaît de façon sporadique — quelques fois dans un long document, concentré là où le rédacteur voulait une pause dramatique.\n\nUn modèle de langage ne connaît pas cette friction. Chaque caractère coûte le même prix. Le résultat est une empreinte statistique caractéristique :\n\n- Les tirets cadratins apparaissent à un rythme régulier dans chaque paragraphe, plutôt que par à-coups.\n- Ils sont fréquemment utilisés **par paires**, pour encadrer une incise, là où la plupart des gens mettraient des virgules.\n- Ils surgissent dans des registres qui ne les comporteraient jamais normalement, comme une courte réponse, un élément de liste à puces ou un rapport de bug.\n\nAucun de ces schémas n'est fautif. Ils sont simplement plus réguliers que ne l'est l'écriture humaine, et c'est précisément cette régularité que les lecteurs remarquent.",
    },
    "how-to-remove": {
      heading: "Comment supprimer les tirets cadratins sans casser les phrases",
      body: "L'erreur consiste à remplacer chaque tiret cadratin par un trait d'union. Le trait d'union est un caractère différent, avec une fonction différente, et le résultat donne l'impression d'une coquille plutôt que d'un texte propre. Adaptez le remplacement au rôle que jouait le tiret.\n\n**Une paire de tirets cadratins encadrant une incise** devient généralement une paire de virgules. Si l'incise est une véritable digression, les parenthèses conviennent mieux.\n\n**Un tiret cadratin unique avant une conclusion** tient lieu de deux-points. Remplacez-le par ce signe, ou terminez la phrase et commencez-en une nouvelle.\n\n**Un tiret cadratin unique au milieu d'une phrase** marque souvent une coupure plus forte que nécessaire. Scinder la phrase en deux se lit presque toujours mieux que n'importe quel signe de substitution.\n\n| Rôle du tiret | Meilleur remplacement |\n| --- | --- |\n| Encadrer une légère incise | Virgules |\n| Encadrer une digression | Parenthèses |\n| Introduire un résumé | Deux-points |\n| Marquer une rupture franche | Point, puis deux phrases |\n| Indiquer une plage (2020—2024) | Tiret demi-cadratin, pas cadratin |\n\nSi vous travaillez sur un long document, l'outil [Supprimer les tirets cadratins](/remove-em-dashes) remplace chaque tiret cadratin par le substitut de votre choix et indique combien ont été modifiés, ce qui vous permet de vérifier le compte au lieu de faire confiance à un rechercher-remplacer silencieux.",
    },
    "when-to-keep": {
      heading: "Quand faut-il conserver le tiret cadratin",
      body: "Supprimer tous les tirets cadratins de vos textes serait une surcorrection. Ce signe existe parce qu'il fait quelque chose que les alternatives ne font pas : il crée une pause plus forte qu'une virgule et moins définitive qu'un point, sans la raideur bureaucratique du point-virgule.\n\nConservez-le quand :\n\n- La phrase a réellement besoin d'une interruption franche, et une virgule serait trop faible.\n- Vous citez une source qui en utilisait un. Modifier la ponctuation à l'intérieur d'une citation, c'est modifier la citation.\n- La charte éditoriale l'exige. La plupart des éditeurs de livres et de nombreuses rédactions en usent librement.\n- Vous écrivez de la fiction ou des essais personnels, où le rythme compte davantage que l'apparence de neutralité mécanique.\n\nL'objectif réaliste n'est pas zéro tiret cadratin. C'est des tirets cadratins qui apparaissent parce que vous les avez choisis, à un rythme qui reflète votre propre voix. Un ou deux dans un long article paraissent délibérés. Un par paragraphe paraît être un réglage par défaut.",
    },
    "other-habits": {
      heading: "Le tiret cadratin n'est qu'une habitude parmi d'autres",
      body: "Le tiret retient l'attention parce que c'est un caractère unique que l'on peut rechercher. Ce n'est pas la seule régularité, et les autres proviennent des deux mêmes pressions : des données d'entraînement pleines de textes édités et structurés, et un ajustement vers des réponses que les lecteurs jugent claires.\n\n- **Le gras sur des expressions clés.** Pas des titres, mais une expression ou deux mises en valeur au milieu d'un paragraphe, souvent les premiers mots d'un élément de liste. Cela rend une réponse facile à parcourir, ce qui est justement ce qu'une interface de conversation cherche à optimiser.\n- **Des puces là où de la prose suffirait.** Une idée de trois phrases arrive sous forme de trois puces. Les listes obtiennent de bons scores en tant que réponses, donc les modèles y recourent par défaut même quand les points ne sont pas vraiment parallèles.\n- **Des titres sur des réponses courtes.** Une réponse de quatre paragraphes avec deux titres de section au-dessus. La structure est empruntée à la documentation, où elle a sa place, et appliquée à un texte bien trop court pour avoir besoin de navigation.\n- **Les emojis comme éléments de décor.** Utilisés comme marqueurs de puce ou icônes de section plutôt que comme expression — une coche devant chaque élément, une fusée au-dessus du bloc « prochaines étapes ».\n- **« Ce n'est pas seulement X — c'est Y. »** Le mouvement correction-puis-élévation, avec « il convient de noter que » et « l'essentiel est ». Ce sont des tournures ordinaires ; ce qui frappe, c'est la fréquence à laquelle elles se regroupent dans un même texte court.\n- **La règle de trois.** Trois exemples, trois puces, trois adjectifs, parce que trois paraît complet. Les brouillons humains sont plus irréguliers — deux raisons, ou cinq, selon leur nombre réel.\n\nAucune de ces habitudes n'est un filigrane. Aucun fournisseur n'imprime un signal caché dans un texte ordinaire, et aucune de ces habitudes n'a été conçue comme un indice. Ce sont des réglages de style par défaut, et on peut les retirer ou demander à s'en passer comme n'importe quel autre réglage de style par défaut. Si vous voulez les faire disparaître d'un document que vous avez déjà, [Humaniser un texte IA](/humanize-ai-text) retire la couche mécanique — la ponctuation, les caractères invisibles, les emojis décoratifs — et [Puces vers paragraphe](/bullet-points-to-paragraph) transforme un texte trop listé en prose. Aucun des deux ne prétend déjouer un détecteur, et vous devriez vous méfier de tout ce qui le prétend.\n\nL'ensemble complet, y compris ceux que l'on peut compter, se trouve dans le guide [signes d'un texte écrit par une IA](/guides/signs-of-ai-written-text).",
    },
    "not-proof": {
      heading: "Les tirets cadratins ne prouvent pas qu'un texte vient d'une IA",
      body: "Cela mérite d'être dit clairement, car beaucoup de conseils en ligne se trompent : **la présence de tirets cadratins ne prouve rien.**\n\nDe nombreux textes écrits par des humains en regorgent. Microsoft Word convertit automatiquement un double trait d'union en tiret cadratin au fil de la frappe, si bien que des rédacteurs en produisent sans jamais choisir le caractère. Quiconque a été formé à l'écriture éditoriale les utilise par réflexe. Des publications entières les imposent.\n\nIl n'existe aucun moyen fiable de détecter un texte généré par IA à partir de sa ponctuation, et les outils commerciaux qui prétendent le contraire affichent des taux de faux positifs bien documentés — les locuteurs non natifs de l'anglais étant touchés de façon disproportionnée. Traiter un tiret cadratin comme une preuve a des conséquences réelles quand l'accusation tombe sur un étudiant ou un collègue.\n\nCe que l'analyse de la mise en forme peut honnêtement vous dire est mécanique : combien de tirets cadratins contient ce document, combien de guillemets courbes, combien de caractères invisibles. Ce sont des comptages, pas des verdicts. Notre outil [Nettoyer les textes ChatGPT et IA](/clean-ai-text) rapporte exactement ces chiffres et ne prétend rien dire sur qui ou quoi a écrit le texte, ce qui est la seule chose défendable pour un outil de mise en forme.\n\nSi vous voulez une vue d'ensemble des artefacts de mise en forme qui accompagnent les textes d'IA, le guide sur les [signes d'un texte écrit par une IA](/guides/signs-of-ai-written-text) couvre le reste.",
    },
  },
  faqs: [
    { question: "Utiliser des tirets cadratins donne-t-il l'impression que mon texte est généré par une IA ?", answer: "Pas à lui seul. Le tiret cadratin est standard dans l'anglais édité et présent partout dans l'écriture humaine, notamment parce que Word le crée automatiquement à partir d'un double trait d'union. Ce qui paraît mécanique, c'est un rythme élevé et régulièrement espacé — environ un par paragraphe dans tout le document — généralement accompagné d'autres artefacts comme les guillemets courbes et les listes à puces ornées d'emojis." },
    { question: "Par quoi remplacer un tiret cadratin ?", answer: "Adaptez le remplacement à sa fonction. Une paire encadrant une incise devient des virgules ou des parenthèses ; un tiret unique introduisant une conclusion devient deux-points ; un tiret marquant une rupture franche se lit généralement mieux sous forme de deux phrases distinctes. Évitez de remplacer un tiret cadratin par un trait d'union, qui est un caractère différent avec une fonction différente." },
    { question: "Pourquoi ChatGPT utilise-t-il des tirets cadratins plutôt que des virgules ?", answer: "Le tiret cadratin est le signe le plus souple de l'anglais, capable de remplacer une virgule, les deux-points, un point-virgule ou des parenthèses. Quand plusieurs signes sont grammaticalement acceptables, c'est toujours un choix sûr, donc un modèle ajusté pour produire un texte fluide le sélectionne de façon disproportionnée." },
    { question: "Puis-je empêcher ChatGPT d'utiliser des tirets cadratins ?", answer: "Vous pouvez le demander directement dans votre prompt, par exemple « n'utilise pas de tirets cadratins ; utilise des virgules ou des phrases séparées ». L'obéissance est imparfaite et tend à s'estomper au fil d'une longue réponse, il est donc souvent plus rapide de rédiger normalement puis de supprimer les tirets ensuite." },
    { question: "Un tiret cadratin est-il la même chose qu'un trait d'union ?", answer: "Non. Le trait d'union (-, U+002D) relie les mots composés. Le tiret demi-cadratin (–, U+2013) marque les plages comme 2020–2024. Le tiret cadratin (—, U+2014) isole une incise dans une phrase. Ce sont trois caractères distincts, de largeur croissante, et ils ne sont pas interchangeables." },
  ],
};
